// Single source of truth for the small-business category list.
// Used by:
//   - /edit-business-profile (the owner picks one)
//   - /discover (the "Looking for a local small business?" filter)
//
// Purple is the brand color for the business surface; the UI tints
// chips, badges and buttons with violet (#8b5cf6 family) wherever
// business categories show up to keep them visually distinct from the
// 150+ creator categories.

export const BUSINESS_CATEGORIES = [
  // Food & drink
  '🍽️ Food & Drinks',
  '🥐 Bakery',
  '☕ Coffee Shop',
  '🍱 Catering',
  '👨‍🍳 Personal Chef',
  '🥗 Meal Prep',
  '🚚 Food Truck',
  // Retail
  '👗 Boutique',
  '👟 Sneaker Reseller',
  '🛍️ Pop-Up Shop',
  // Beauty / personal care
  '💇 Hair Salon',
  '💈 Barber Shop',
  '💅 Nail Tech',
  '👁️ Lash Tech',
  '✨ Esthetician',
  '💄 Makeup Artist',
  '💆 Massage Therapy',
  '🧖 Spa',
  // Creative studios / classes
  '🎚️ Music Studio',
  '🧘 Yoga Class',
  '💃 Dance Class',
  '🏋️ Personal Trainer',
  '🥊 Boxing / MMA Gym',
  '🎨 Art Class',
  '📚 Tutoring',
  // Trades & home services
  '🚿 Plumber',
  '⚡ Electrician',
  '❄️ HVAC',
  '🧹 Maid Services',
  '🔨 Handyman',
  '🌿 Landscaping',
  '🪟 Window Cleaning',
  '🎨 Painting Services',
  '🔑 Locksmith',
  '🪜 Roofing',
  '🐀 Pest Control',
  // Auto
  '🔧 Auto Mechanic',
  '🚗 Mobile Detailing',
  '🚙 Car Wash',
  '🛞 Tire Shop',
  // Professional services
  '🛡️ Insurance',
  '📜 Notary',
  '⚖️ Legal Services',
  '📊 Tax Preparation',
  '💼 Financial Services',
  '🏠 Real Estate',
  '🖥️ IT Support',
  '🖥️ Web Design',
  '✏️ Graphic Design',
  '📢 Marketing Services',
  // Media / event
  '📸 Photography',
  '🎥 Videography',
  '🎧 DJ Services',
  '🎉 Event Planner',
  '💍 Wedding Planner',
  '🪞 Makeup for Events',
  // Pets & kids
  '🐾 Pet Grooming',
  '🐶 Dog Walking',
  '🍼 Daycare',
  '🐱 Pet Sitting',
  // Body art
  '🖋️ Tattoo Studio',
  '💎 Piercing Studio',

  // ---------------- Online shops ----------------
  '🛒 Online Store',
  '🛍️ Etsy Shop',
  '🛒 Shopify Store',
  '📦 Amazon Storefront',
  '🛒 eBay Seller',
  '👗 Online Boutique',
  '👕 Custom Clothing',
  '👟 Custom Sneakers',
  '👜 Handmade Bags',
  '💍 Custom Jewelry',
  '🖼️ Custom Art / Commissions',
  '🖨️ Print-on-Demand',
  '🕯️ Candles & Home Goods',
  '🌿 Skincare Brand',
  '💄 Beauty Brand',
  '🌸 Bath & Body',
  '🍶 Specialty Sauces / Spices',
  '🍪 Cottage Food (home-baked)',
  '🌱 Plants & Seeds',
  '👶 Baby Goods',
  '🐕 Pet Goods',
  '📿 Spiritual / Crystal Shop',
  '🎨 Sticker / Enamel Pin Shop',
  '👚 Vintage / Thrift Resale',
  '👟 Sneaker Resale (Online)',
  '🎽 Poshmark / Depop Seller',

  // ---------------- Digital products ----------------
  '📚 E-Book Author',
  '🍳 Cookbook Author',
  '🎓 Online Course / Class',
  '📝 Templates & Printables',
  '🎨 Digital Art / Wallpapers',
  '📸 Lightroom Presets',
  '🎞️ LUTs / Video Presets',
  '🎵 Beat / Sample Pack',
  '🎙️ Audio / SFX Library',
  '🔤 Font / Typeface Sales',
  '🧩 Notion Templates',
  '📊 Spreadsheet Templates',
  '🖼️ Stock Photos / Footage',
  '👁️ Lash Map Designs',
  '🎟️ Digital Planner',

  // ---------------- Online services ----------------
  '🎓 Online Tutoring',
  '🗣️ Language Lessons (Online)',
  '🎤 Voice Acting',
  '✍️ Freelance Writing',
  '📝 Copywriting',
  '✂️ Freelance Editing',
  '📐 Resume / Cover-letter Writing',
  '🌐 Translation Services',
  '🧠 Online Coaching / Therapy',
  '💼 Career Coaching',
  '🧘 Online Yoga / Fitness',
  '🍎 Online Nutrition',
  '🎨 Brand / Identity Designer',
  '🖥️ Web Design (freelance)',
  '📱 App Development',
  '📈 Social Media Management',
  '📣 Online Marketing Services',
  '📷 Photography (booking online)',
  '🎬 Videography (booking online)',
  '✈️ Virtual Assistant',
  '📋 Bookkeeping / Accounting',
  '⚖️ Online Legal Services',
  '📊 Online Financial Coaching',
  '🏠 Virtual Notary',

  // ---------------- Creator monetization ----------------
  '💌 Paid Newsletter / Substack',
  '🎙️ Sponsored Podcast',
  '💝 Patreon / Membership',
  '🛍️ Affiliate Marketing',
  '🛒 Brand Ambassador',
  '🎮 Streamer (paid)',
];
