// This or That prompt library.
//
// Short, rapid-fire taste comparisons — the "speed dating" sibling of
// Would You Rather. 200+ prompts grouped loosely by theme. The game
// shuffles within a session so the same prompt won't appear twice
// across many games.

export interface TotPrompt {
  a: string;
  b: string;
}

export const TOT_PROMPTS: TotPrompt[] = [
  // ---------- Food ----------
  { a: 'Pizza', b: 'Tacos' },
  { a: 'Sushi', b: 'Burgers' },
  { a: 'Pasta', b: 'Ramen' },
  { a: 'Steak', b: 'Salmon' },
  { a: 'Pancakes', b: 'Waffles' },
  { a: 'Bagels', b: 'Croissants' },
  { a: 'Bacon', b: 'Sausage' },
  { a: 'Cake', b: 'Pie' },
  { a: 'Cookies', b: 'Brownies' },
  { a: 'Ice cream', b: 'Frozen yogurt' },
  { a: 'Cheesecake', b: 'Tiramisu' },
  { a: 'Donuts', b: 'Cinnamon rolls' },
  { a: 'Mac & cheese', b: 'Loaded fries' },
  { a: 'BBQ', b: 'Korean BBQ' },
  { a: 'Italian', b: 'Mexican' },
  { a: 'Thai', b: 'Vietnamese' },
  { a: 'Indian', b: 'Chinese' },
  { a: 'Greek', b: 'Spanish' },
  { a: 'Brunch', b: 'Late dinner' },
  { a: 'Spicy', b: 'Sweet' },
  { a: 'Sour', b: 'Salty' },
  { a: 'Avocado toast', b: 'Egg sandwich' },
  { a: 'Tacos al pastor', b: 'Tacos de carnitas' },
  { a: 'Burrito', b: 'Quesadilla' },
  { a: 'Sushi roll', b: 'Sashimi' },
  { a: 'Burger', b: 'Hot dog' },
  { a: 'French fries', b: 'Sweet potato fries' },
  { a: 'Mashed potatoes', b: 'Roasted potatoes' },
  { a: 'Mango', b: 'Pineapple' },
  { a: 'Strawberries', b: 'Raspberries' },

  // ---------- Drinks ----------
  { a: 'Coffee', b: 'Tea' },
  { a: 'Espresso', b: 'Drip coffee' },
  { a: 'Latte', b: 'Cappuccino' },
  { a: 'Iced coffee', b: 'Hot coffee' },
  { a: 'Matcha', b: 'Chai' },
  { a: 'Red wine', b: 'White wine' },
  { a: 'Beer', b: 'Cocktail' },
  { a: 'Margarita', b: 'Mojito' },
  { a: 'Whiskey', b: 'Tequila' },
  { a: 'Coke', b: 'Pepsi' },
  { a: 'Sparkling water', b: 'Still water' },
  { a: 'Lemonade', b: 'Iced tea' },
  { a: 'Smoothie', b: 'Juice' },
  { a: 'Boba', b: 'Slushie' },
  { a: 'Hot chocolate', b: 'Apple cider' },

  // ---------- Lifestyle ----------
  { a: 'Morning person', b: 'Night owl' },
  { a: 'Beach', b: 'Mountains' },
  { a: 'City', b: 'Countryside' },
  { a: 'Driving', b: 'Walking' },
  { a: 'Sunrise', b: 'Sunset' },
  { a: 'Summer', b: 'Winter' },
  { a: 'Spring', b: 'Autumn' },
  { a: 'Hot weather', b: 'Cool weather' },
  { a: 'Quiet night in', b: 'Loud night out' },
  { a: 'Dinner party', b: 'Game night' },
  { a: 'Concert', b: 'Sporting event' },
  { a: 'Big city', b: 'Small town' },
  { a: 'Apartment', b: 'House' },
  { a: 'Renting', b: 'Owning' },
  { a: 'Camping', b: 'Glamping' },
  { a: 'Cruise', b: 'Road trip' },
  { a: 'Plan everything', b: 'Wing it' },
  { a: 'Save money', b: 'Spend it' },
  { a: 'Window seat', b: 'Aisle seat' },
  { a: 'Pack light', b: 'Pack heavy' },
  { a: 'Workout morning', b: 'Workout evening' },
  { a: 'Gym', b: 'Outdoors' },
  { a: 'Running', b: 'Yoga' },
  { a: 'Cardio', b: 'Weights' },
  { a: 'Cook at home', b: 'Order in' },
  { a: 'Meal prep', b: 'Spontaneous cooking' },

  // ---------- Music ----------
  { a: 'Hip-hop', b: 'R&B' },
  { a: 'Pop', b: 'Indie' },
  { a: 'Rock', b: 'Country' },
  { a: 'EDM', b: 'House' },
  { a: 'Jazz', b: 'Soul' },
  { a: 'Folk', b: 'Bluegrass' },
  { a: 'Punk', b: 'Metal' },
  { a: 'Reggae', b: 'Reggaeton' },
  { a: 'Classical', b: 'Lo-fi' },
  { a: 'Spotify', b: 'Apple Music' },
  { a: 'Vinyl', b: 'Streaming' },
  { a: 'Playlist', b: 'Full album' },
  { a: 'Big concert', b: 'Tiny venue' },
  { a: 'Headphones', b: 'Speakers' },
  { a: 'Beyoncé', b: 'Rihanna' },
  { a: 'Drake', b: 'Kendrick' },
  { a: 'Taylor Swift', b: 'Olivia Rodrigo' },
  { a: 'The Beatles', b: 'The Rolling Stones' },
  { a: 'Stevie Wonder', b: 'Marvin Gaye' },
  { a: 'Prince', b: 'Bowie' },

  // ---------- Movies / TV ----------
  { a: 'Marvel', b: 'DC' },
  { a: 'Star Wars', b: 'Star Trek' },
  { a: 'Studio Ghibli', b: 'Pixar' },
  { a: 'Comedy', b: 'Drama' },
  { a: 'Horror', b: 'Thriller' },
  { a: 'Rom-com', b: 'Action' },
  { a: 'Mystery', b: 'Sci-fi' },
  { a: 'Anime', b: 'Animated film' },
  { a: 'Sitcom', b: 'Drama series' },
  { a: 'Reality TV', b: 'Documentary' },
  { a: 'Movie theater', b: 'Home theater' },
  { a: 'Netflix', b: 'HBO Max' },
  { a: 'Series finale', b: 'Movie franchise ending' },
  { a: 'Friends', b: 'Seinfeld' },
  { a: 'The Office', b: 'Parks & Rec' },
  { a: 'Stranger Things', b: 'Squid Game' },
  { a: 'Breaking Bad', b: 'Better Call Saul' },
  { a: 'Game of Thrones', b: 'House of the Dragon' },
  { a: 'Spider-Man', b: 'Batman' },
  { a: 'Disney movie', b: 'A24 movie' },

  // ---------- Style / aesthetic ----------
  { a: 'Streetwear', b: 'Minimalist' },
  { a: 'Vintage', b: 'Modern' },
  { a: 'Sneakers', b: 'Boots' },
  { a: 'Jeans', b: 'Sweatpants' },
  { a: 'Hoodie', b: 'Crewneck' },
  { a: 'Watch', b: 'Bracelet' },
  { a: 'Rings', b: 'Necklace' },
  { a: 'Sunglasses', b: 'Hat' },
  { a: 'Tattoo', b: 'Piercing' },
  { a: 'Dressed up', b: 'Dressed down' },
  { a: 'Bold colors', b: 'Neutral palette' },
  { a: 'Earth tones', b: 'Pastels' },
  { a: 'Gold', b: 'Silver' },
  { a: 'Black', b: 'White' },
  { a: 'Patterned', b: 'Solid' },

  // ---------- Tech / digital ----------
  { a: 'iPhone', b: 'Android' },
  { a: 'Mac', b: 'PC' },
  { a: 'AirPods', b: 'Over-ear headphones' },
  { a: 'Light mode', b: 'Dark mode' },
  { a: 'Instagram', b: 'TikTok' },
  { a: 'Twitter', b: 'Threads' },
  { a: 'YouTube', b: 'TikTok' },
  { a: 'Email', b: 'Text' },
  { a: 'Phone call', b: 'FaceTime' },
  { a: 'Discord', b: 'Slack' },
  { a: 'Google', b: 'ChatGPT' },
  { a: 'Console gaming', b: 'PC gaming' },
  { a: 'PlayStation', b: 'Xbox' },
  { a: 'Switch', b: 'Steam Deck' },
  { a: 'Online shopping', b: 'In-store shopping' },

  // ---------- Hobbies / activities ----------
  { a: 'Reading', b: 'Podcasts' },
  { a: 'Drawing', b: 'Painting' },
  { a: 'Writing', b: 'Photography' },
  { a: 'Singing', b: 'Dancing' },
  { a: 'Playing piano', b: 'Playing guitar' },
  { a: 'Board games', b: 'Video games' },
  { a: 'Puzzles', b: 'Crosswords' },
  { a: 'Sudoku', b: 'Wordle' },
  { a: 'Chess', b: 'Poker' },
  { a: 'Cooking', b: 'Baking' },
  { a: 'Gardening', b: 'Houseplants' },
  { a: 'Hiking', b: 'Biking' },
  { a: 'Swimming', b: 'Surfing' },
  { a: 'Skiing', b: 'Snowboarding' },
  { a: 'Tennis', b: 'Pickleball' },
  { a: 'Basketball', b: 'Soccer' },
  { a: 'Football', b: 'Baseball' },
  { a: 'F1', b: 'MotoGP' },
  { a: 'Crochet', b: 'Knitting' },
  { a: 'DIY home project', b: 'Hiring a pro' },

  // ---------- Pets / animals ----------
  { a: 'Cats', b: 'Dogs' },
  { a: 'Small dogs', b: 'Big dogs' },
  { a: 'Kittens', b: 'Puppies' },
  { a: 'Aquarium fish', b: 'Pet birds' },
  { a: 'Rabbits', b: 'Hamsters' },
  { a: 'Reptiles', b: 'Amphibians' },
  { a: 'Horses', b: 'Llamas' },
  { a: 'Owls', b: 'Hawks' },
  { a: 'Penguins', b: 'Polar bears' },
  { a: 'Dolphins', b: 'Whales' },

  // ---------- Travel ----------
  { a: 'Paris', b: 'Rome' },
  { a: 'Tokyo', b: 'Seoul' },
  { a: 'NYC', b: 'LA' },
  { a: 'Miami', b: 'Vegas' },
  { a: 'London', b: 'Berlin' },
  { a: 'Barcelona', b: 'Madrid' },
  { a: 'Bali', b: 'Maldives' },
  { a: 'Iceland', b: 'New Zealand' },
  { a: 'Greece', b: 'Croatia' },
  { a: 'Costa Rica', b: 'Mexico City' },
  { a: 'Caribbean', b: 'Hawaii' },
  { a: 'Train', b: 'Plane' },
  { a: 'Beach resort', b: 'Boutique hotel' },
  { a: 'Cabin in the woods', b: 'Loft downtown' },
  { a: 'Backpacking', b: 'Luxury travel' },

  // ---------- Personality / daily ----------
  { a: 'Introvert', b: 'Extrovert' },
  { a: 'Loud laugh', b: 'Quiet smile' },
  { a: 'Talker', b: 'Listener' },
  { a: 'Spontaneous', b: 'Planner' },
  { a: 'Adventurous', b: 'Cozy' },
  { a: 'Optimist', b: 'Realist' },
  { a: 'Thinker', b: 'Doer' },
  { a: 'Lead', b: 'Follow' },
  { a: 'Compete', b: 'Cooperate' },
  { a: 'Early', b: 'Fashionably late' },
  { a: 'Tidy', b: 'Cluttered' },
  { a: 'Open windows', b: 'AC' },
  { a: 'Coffee shop work', b: 'Quiet at home' },
  { a: 'Hot showers', b: 'Cold plunges' },
  { a: 'Bath', b: 'Shower' },
  { a: 'Bed by 10', b: 'Bed by 2' },

  // ---------- Weird / fun ----------
  { a: 'Cake at midnight', b: 'Pancakes at noon' },
  { a: 'Always cold', b: 'Always hot' },
  { a: 'No phone', b: 'No music' },
  { a: 'Aliens exist', b: 'Aliens don\'t' },
  { a: 'Time travel', b: 'Teleportation' },
  { a: 'Read minds', b: 'Be invisible' },
  { a: 'Fly', b: 'Breathe underwater' },
  { a: 'Talk to animals', b: 'Talk to plants' },
  { a: 'Be famous', b: 'Be rich' },
  { a: 'Lottery winner', b: 'Forever lucky' },
  { a: 'Endless brunch', b: 'Endless happy hour' },
  { a: 'Live in a treehouse', b: 'Live on a boat' },
  { a: 'Sleep 4 hours', b: 'Sleep 12 hours' },
  { a: 'Always know the time', b: 'Never need an alarm' },
  { a: 'See the future', b: 'Change the past' },
];

// Pick N unique random prompts, optionally excluding a list already in use.
export function pickRandomTot(n: number, exclude: TotPrompt[] = []): TotPrompt[] {
  const keys = new Set(exclude.map((p) => `${p.a}|${p.b}`));
  const pool = TOT_PROMPTS.filter((p) => !keys.has(`${p.a}|${p.b}`));
  const shuffled = pool.slice().sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
