// Would You Rather prompt library.
//
// 250+ curated prompts grouped loosely by theme. The shuffler in the
// game randomises within a session so a player won't see the same
// prompt twice across many games.

export interface WyrPrompt {
  a: string;
  b: string;
}

export const WYR_PROMPTS: WyrPrompt[] = [
  // ---------- Creative & craft ----------
  { a: 'Headline a sold-out world tour', b: 'Star in an Oscar-winning film' },
  { a: 'Have unlimited creative inspiration', b: 'Have unlimited budget for your projects' },
  { a: 'Collaborate with your childhood hero', b: 'Discover the next big thing and collaborate early' },
  { a: 'Be best known for one iconic piece', b: 'Have a huge body of respected work' },
  { a: 'Win an Oscar', b: 'Win a Grammy' },
  { a: 'Be Time magazine\'s Person of the Year', b: 'Win five Grammys in one night' },
  { a: 'Have your art in the Louvre', b: 'Have your song on every Spotify playlist' },
  { a: 'Always finish what you start', b: 'Never have writer\'s block' },
  { a: 'Master one craft perfectly', b: 'Be decent at ten different crafts' },
  { a: 'Get paid to make whatever you want', b: 'Get paid double to make what\'s trending' },
  { a: 'Be wildly successful but anonymous', b: 'Be famous but modestly successful' },
  { a: 'Only create at sunrise', b: 'Only create at midnight' },
  { a: 'Have perfect pitch', b: 'Have a photographic memory' },
  { a: 'Go viral once a year', b: 'Have 10 loyal superfans for life' },
  { a: 'Open for your favorite artist', b: 'Headline a small but devoted venue' },
  { a: 'Win a Pulitzer Prize', b: 'Have a hit Netflix series based on your work' },
  { a: 'Write the most-quoted line of the decade', b: 'Make the most-streamed song of the decade' },
  { a: 'Direct the highest-grossing film of the year', b: 'Direct the most critically acclaimed film of the year' },
  { a: 'Have a six-month creative retreat', b: 'Have $50K extra to spend on your craft' },
  { a: 'Be in the room with every artist you admire', b: 'Have one of them mentor you for a year' },
  { a: 'Get a glowing review in The New York Times', b: 'Get a glowing shout-out from Beyoncé' },
  { a: 'Only work in black-and-white', b: 'Only work in neon colors' },
  { a: 'Have an idea so good it scares you', b: 'Have ten ideas you could ship tomorrow' },
  { a: 'Be a one-hit wonder forever remembered', b: 'Be a steady mid-tier artist forever respected' },
  { a: 'Always know what people want to see', b: 'Always make what you want to make' },
  { a: 'Have a creative breakthrough every month', b: 'Have one massive breakthrough every five years' },
  { a: 'Be remembered for one project that defined a decade', b: 'Have a steady, life-long output that nobody remembers individually' },
  { a: 'Earn your fame slowly over 20 years', b: 'Earn it all at 25 and have to figure out what\'s next' },
  { a: 'Get rejected by every publisher then self-publish a hit', b: 'Get published by the first publisher who reads it' },
  { a: 'Be praised for your taste', b: 'Be praised for your originality' },
  { a: 'Win an award with a famous co-creator', b: 'Win it solo for a quiet project' },

  // ---------- Lifestyle ----------
  { a: 'Live by the beach', b: 'Live in a creative city downtown' },
  { a: 'Wake up at 5am every day', b: 'Stay up until 3am every day' },
  { a: 'Live in a tiny luxury apartment', b: 'Live in a huge house in the suburbs' },
  { a: 'Always have perfect Wi-Fi', b: 'Always have perfect coffee' },
  { a: 'Be 30 minutes early to everything', b: 'Always have a great excuse for being late' },
  { a: 'Live where it\'s always autumn', b: 'Live where it\'s always summer' },
  { a: 'Be able to control the weather where you are', b: 'Be able to skip ahead 24 hours whenever you want' },
  { a: 'Have a personal chef', b: 'Have a personal trainer' },
  { a: 'Live in one city for life', b: 'Live in a different country every year' },
  { a: 'Never need to sleep', b: 'Never need to eat' },
  { a: 'Always know the time without checking', b: 'Always know the temperature without checking' },
  { a: 'Have a pet that talks', b: 'Have a pet that lives forever' },
  { a: 'Have a personal assistant', b: 'Have a personal driver' },
  { a: 'Wear the same outfit every day', b: 'Wear a costume to every event' },
  { a: 'Lose your phone for a week', b: 'Lose your wallet for a week' },
  { a: 'Live in a tiny home you designed', b: 'Live in a mansion someone else designed' },
  { a: 'Move to a new city every five years', b: 'Stay in the same city your whole life' },
  { a: 'Have a beautiful garden', b: 'Have a beautiful library' },
  { a: 'Have a cozy small apartment forever', b: 'Have a mansion that always needs repairs' },
  { a: 'Live without TV', b: 'Live without music' },
  { a: 'Be invited everywhere', b: 'Be welcome anywhere' },
  { a: 'Always have the right thing to say', b: 'Always know when to be silent' },
  { a: 'Read every book on your shelf', b: 'Watch every movie on your watchlist' },
  { a: 'Cook a Michelin-star meal', b: 'Plate someone else\'s Michelin meal perfectly' },

  // ---------- Taste / preferences ----------
  { a: 'Pizza forever', b: 'Tacos forever' },
  { a: 'Coffee only', b: 'Tea only' },
  { a: 'Sweet breakfast', b: 'Savory breakfast' },
  { a: 'Beach vacation', b: 'Mountain vacation' },
  { a: 'Cats', b: 'Dogs' },
  { a: 'Spotify only', b: 'Apple Music only' },
  { a: 'Marvel forever', b: 'DC forever' },
  { a: 'The Beatles', b: 'The Rolling Stones' },
  { a: 'A perfect cup of coffee', b: 'A perfect glass of wine' },
  { a: 'Action movies forever', b: 'Rom-coms forever' },
  { a: 'Vinyl records', b: 'Streaming with perfect quality' },
  { a: 'Books only', b: 'Audiobooks only' },
  { a: 'Sneakers forever', b: 'Boots forever' },
  { a: 'Pasta as the only carb', b: 'Rice as the only carb' },
  { a: 'Sunrise person', b: 'Sunset person' },
  { a: 'iPhone forever', b: 'Android forever' },
  { a: 'Print magazines', b: 'Newsletters' },
  { a: 'Studio Ghibli', b: 'Pixar' },
  { a: 'Sushi forever', b: 'Pizza forever' },
  { a: 'Hot weather', b: 'Cold weather' },
  { a: 'Espresso shot', b: 'Iced latte' },
  { a: 'Drama series', b: 'Sitcom series' },
  { a: 'Indie film', b: 'Big-budget blockbuster' },
  { a: 'Comedy stand-up', b: 'Musical concert' },
  { a: 'Sneakers and jeans forever', b: 'Suits and dresses forever' },

  // ---------- Travel & adventure ----------
  { a: 'Travel the world for a year', b: 'Have one perfect month in Paris' },
  { a: 'See every country before you turn 40', b: 'Speak five languages fluently' },
  { a: 'Live in Tokyo for a year', b: 'Live in Buenos Aires for a year' },
  { a: 'Drive across America', b: 'Take a train across Europe' },
  { a: 'Backpack through Asia', b: 'Sail through the Mediterranean' },
  { a: 'Stay at the Ritz once', b: 'Stay at a stunning Airbnb every weekend' },
  { a: 'Always travel first class', b: 'Always travel for free' },
  { a: 'See the Northern Lights', b: 'Swim with whales' },
  { a: 'Climb a famous mountain', b: 'Scuba dive a famous reef' },
  { a: 'Spend a week in space', b: 'Spend a week at the bottom of the ocean' },
  { a: 'Live in NYC for a year', b: 'Live in LA for a year' },
  { a: 'Spend a month in a cabin', b: 'Spend a month on a yacht' },
  { a: 'Have your dream vacation alone', b: 'Have a fine vacation with your favorite people' },
  { a: 'Travel forever with no home base', b: 'Have one dream home and rarely leave' },
  { a: 'Take a 30-day silent retreat', b: 'Take a 30-day road trip with friends' },
  { a: 'Visit every continent', b: 'Master one city completely' },
  { a: 'Sleep under the stars', b: 'Sleep in a five-star hotel' },
  { a: 'Walk the Camino in Spain', b: 'Drive Route 66 across America' },
  { a: 'Eat your way through Tokyo', b: 'Eat your way through Rome' },
  { a: 'Go to Coachella', b: 'Go to Glastonbury' },

  // ---------- Hypotheticals / superpowers ----------
  { a: 'Be invisible for a week', b: 'Read minds for a week' },
  { a: 'Teleport to anywhere you\'ve been', b: 'Fly but only at 50 mph' },
  { a: 'Speak every language', b: 'Play every instrument' },
  { a: 'Live forever', b: 'Die at the perfect moment' },
  { a: 'Be incredibly attractive', b: 'Be incredibly intelligent' },
  { a: 'See the future once a year', b: 'Relive the past once a year' },
  { a: 'Never get sick', b: 'Never feel tired' },
  { a: 'Have a tail', b: 'Have wings (but you can\'t fly)' },
  { a: 'Have unlimited shoes', b: 'Have unlimited books' },
  { a: 'Be able to pause time once a day', b: 'Be able to rewind 10 seconds whenever you want' },
  { a: 'Have a photographic memory', b: 'Have unbelievable charisma' },
  { a: 'Always know when someone is lying', b: 'Always know what someone needs to hear' },
  { a: 'Have the talent of any artist you admire', b: 'Have the work ethic of any artist you admire' },
  { a: 'Be in two places at once', b: 'Be twice as productive' },
  { a: 'Heal any wound instantly', b: 'Forget any memory you want to' },
  { a: 'Have a personal soundtrack', b: 'Have a personal narrator' },
  { a: 'Always pick the winning lottery numbers', b: 'Always pick the winning sports bet' },
  { a: 'Win a Nobel Prize', b: 'Win an Oscar' },
  { a: 'Trade lives with anyone for a day', b: 'Live a day from your favorite movie' },
  { a: 'Talk to animals', b: 'Talk to plants' },
  { a: 'Always smell amazing', b: 'Always look photo-ready' },
  { a: 'Have one wish granted now', b: 'Have three wishes granted in five years' },
  { a: 'Be able to make anyone laugh', b: 'Be able to make anyone calm' },
  { a: 'Sleep for 30 minutes and feel fully rested', b: 'Get a full night\'s sleep in 4 hours' },

  // ---------- Money & career ----------
  { a: 'Make $100K doing something you love', b: 'Make $300K doing something you tolerate' },
  { a: 'Be your own boss with stress', b: 'Have a steady job with security' },
  { a: 'Inherit $500K but it must be invested', b: 'Get $200K cash right now' },
  { a: 'Be paid only in cryptocurrency', b: 'Be paid only in cash' },
  { a: 'Win the lottery', b: 'Have the perfect career' },
  { a: 'Work four hours a day for less money', b: 'Work ten hours a day for more money' },
  { a: 'Retire at 35 with average wealth', b: 'Retire at 65 with enormous wealth' },
  { a: 'Never work again but live modestly', b: 'Love your job forever but always grind' },
  { a: 'Switch careers every five years', b: 'Master one career for life' },
  { a: 'Be the boss', b: 'Be the second-in-command who gets it all done' },
  { a: 'Work from home forever', b: 'Have an office you love going to' },
  { a: 'Win Shark Tank', b: 'Get a personal mentor for life' },
  { a: 'Have a job everyone respects', b: 'Have a job nobody understands but you love' },
  { a: 'Always be paid in equity', b: 'Always be paid in cash' },
  { a: 'Live paycheck to paycheck doing what you love', b: 'Save aggressively doing what you tolerate' },
  { a: 'Be famous in your niche', b: 'Be wealthy outside your niche' },
  { a: 'Have $1M but it disappears in a year', b: 'Earn $100K every year for life' },
  { a: 'Be a household name', b: 'Be respected by your peers' },
  { a: 'Get a 10% raise every year forever', b: 'Get a 100% raise once and freeze' },
  { a: 'Have a job with no boss', b: 'Have a boss you love' },

  // ---------- Food & drink ----------
  { a: 'Only eat at five-star restaurants', b: 'Only eat home-cooked meals' },
  { a: 'Pizza every day', b: 'Sushi every day' },
  { a: 'Endless tacos', b: 'Endless burgers' },
  { a: 'Skip lunch', b: 'Skip breakfast' },
  { a: 'Never eat cheese again', b: 'Never eat chocolate again' },
  { a: 'Only eat hot food', b: 'Only eat cold food' },
  { a: 'Always have an empty stomach', b: 'Always be slightly full' },
  { a: 'Be the best home cook in your friend group', b: 'Have a personal chef twice a week' },
  { a: 'Lose your sense of taste', b: 'Lose your sense of smell' },
  { a: 'Only eat at your favorite restaurant', b: 'Always try new restaurants' },
  { a: 'Have unlimited dessert', b: 'Have unlimited starters' },
  { a: 'Eat dinner at 5pm forever', b: 'Eat dinner at 10pm forever' },
  { a: 'Always order the chef\'s special', b: 'Always order the same thing you love' },
  { a: 'Never eat at the same restaurant twice', b: 'Have one place you visit every week for life' },
  { a: 'Free coffee for life', b: 'Free wine for life' },
  { a: 'Be a great baker', b: 'Be a great BBQ pitmaster' },
  { a: 'Have a famous cookbook', b: 'Have a famous restaurant' },

  // ---------- Pop culture ----------
  { a: 'Be the lead in a Marvel film', b: 'Be the lead in an A24 film' },
  { a: 'Open at the Met Gala', b: 'Open at Coachella' },
  { a: 'Be on the cover of Rolling Stone', b: 'Be on the cover of Vogue' },
  { a: 'Be a guest on Hot Ones', b: 'Be a guest on Saturday Night Live' },
  { a: 'Walk a runway in Paris', b: 'Drop a sneaker collab with Nike' },
  { a: 'Be name-checked in a Drake song', b: 'Be name-checked in a Taylor Swift song' },
  { a: 'Open SNL', b: 'Close SNL' },
  { a: 'Be on Jimmy Fallon', b: 'Be on Joe Rogan' },
  { a: 'Have a million Instagram followers', b: 'Have ten thousand devoted Substack subscribers' },
  { a: 'Have your album debut at #1', b: 'Have a single that stays in the chart for two years' },
  { a: 'Trend on Twitter for something good', b: 'Trend on TikTok for something silly' },
  { a: 'Have a Spotify Wrapped you\'re proud of', b: 'Have a watch history you\'re proud of' },
  { a: 'Be on the cover of GQ', b: 'Be on the cover of Vanity Fair' },
  { a: 'Be the next Bowie', b: 'Be the next Beyoncé' },
  { a: 'Trade verses with Kendrick', b: 'Trade harmonies with SZA' },
  { a: 'Be played in every coffee shop', b: 'Be played in every car going to a party' },
  { a: 'Direct a Christopher Nolan-scale movie', b: 'Star in a Greta Gerwig-scale movie' },

  // ---------- Connection / friends / love ----------
  { a: 'Have a partner who reads minds', b: 'Have a partner who never reads yours' },
  { a: 'Always have the right thing to say to someone you love', b: 'Always know what they want before they do' },
  { a: 'Be in love forever with the wrong person', b: 'Be slightly happy forever with the right one' },
  { a: 'Date your best friend', b: 'Date your wildest crush' },
  { a: 'Have three best friends who never argue', b: 'Have ten close friends who sometimes do' },
  { a: 'Always know how your partner feels', b: 'Always know what to do about it' },
  { a: 'Have a partner who travels the world with you', b: 'Have a partner who builds a stable life with you' },
  { a: 'Always have the perfect dinner-party guest list', b: 'Always be the perfect dinner-party guest' },
  { a: 'Never argue with your partner', b: 'Always make up perfectly when you do' },
  { a: 'Have a soulmate you only see once a year', b: 'Have a great partner you see every day' },
  { a: 'Be the funniest person in the room', b: 'Be the kindest' },
  { a: 'Have a friend who tells you the truth', b: 'Have a friend who always makes you feel good' },
  { a: 'Live close to your family', b: 'Live across the world but see them in style' },
  { a: 'Meet five-years-ago you', b: 'Meet five-years-from-now you' },
  { a: 'Have a partner who loves your work', b: 'Have a partner who doesn\'t care about it at all' },
  { a: 'Marry someone hilarious', b: 'Marry someone wise' },
  { a: 'Have a great therapist for life', b: 'Have a great mentor for life' },
  { a: 'Always be invited to the party', b: 'Always be the one who plans it' },
  { a: 'Get really close to a few people', b: 'Be loved a little by many' },

  // ---------- Weird / funny ----------
  { a: 'Have a permanent cowlick', b: 'Have a permanent gravelly voice' },
  { a: 'Sneeze every time the sun comes out', b: 'Hiccup every time you laugh' },
  { a: 'Always have a song stuck in your head', b: 'Always have one random fact you can\'t share' },
  { a: 'Have to dance every time you hear music', b: 'Have to sing every time you hear a song' },
  { a: 'Have to talk to one stranger a day', b: 'Have to text one friend you haven\'t in a year' },
  { a: 'Never lose your keys again', b: 'Never lose your phone again' },
  { a: 'Be allergic to a fruit you love', b: 'Lose your love for a fruit forever' },
  { a: 'Wear socks with sandals forever', b: 'Wear flip-flops in winter forever' },
  { a: 'Have a third nipple', b: 'Have an extra finger' },
  { a: 'Get a tattoo of a meme', b: 'Get a tattoo of a stranger\'s name' },
  { a: 'Have your phone fall in a toilet', b: 'Have your phone fall off a building' },
  { a: 'Live next to a 24-hour Taco Bell', b: 'Live above a karaoke bar' },
  { a: 'Wake up to a rooster every day', b: 'Wake up to a leaf blower every day' },
  { a: 'Slip on a banana peel once a month', b: 'Stub your toe once a week' },
  { a: 'Mispronounce a common word forever', b: 'Misspell a common word forever' },
  { a: 'Get hiccups every time you eat', b: 'Sneeze every time you drink' },
  { a: 'Have toothpaste in your beard for an entire date', b: 'Have spinach in your teeth for an entire date' },

  // ---------- Personal growth ----------
  { a: 'Heal all your old wounds', b: 'Forget them entirely' },
  { a: 'Know your weaknesses perfectly', b: 'Know your strengths perfectly' },
  { a: 'Be told the unvarnished truth about yourself', b: 'Always be encouraged' },
  { a: 'Confront everyone you\'ve ever needed to', b: 'Forgive everyone you\'ve ever needed to' },
  { a: 'Have the courage to start something hard', b: 'Have the patience to finish something long' },
  { a: 'Be famous for one bold decision', b: 'Be respected for a hundred small ones' },
  { a: 'Live a slow life you remember', b: 'Live a fast life you forget' },
  { a: 'Know what you want', b: 'Be able to enjoy what you have' },
  { a: 'Always be working toward a goal', b: 'Always be present in the moment' },
  { a: 'Lose a year of memories', b: 'Gain a year of nightmares' },
  { a: 'Be told the truth about your past', b: 'Be told the truth about your future' },
  { a: 'Have one chance to redo a decade', b: 'Have one chance to skip a decade ahead' },
  { a: 'Always finish what you start', b: 'Always know which start is worth finishing' },

  // ---------- Tech & digital ----------
  { a: 'Lose all your photos', b: 'Lose all your contacts' },
  { a: 'Be unable to send a DM for a year', b: 'Be unable to read a DM for a year' },
  { a: 'Have your search history exposed', b: 'Have your group chat exposed' },
  { a: 'Lose Wi-Fi for a week', b: 'Lose cellular data for a week' },
  { a: 'Be in every Zoom call for a month', b: 'Get every email for a month' },
  { a: 'Have an inbox at zero forever', b: 'Have your camera roll perfectly curated forever' },
  { a: 'No Instagram for a year', b: 'No texting for a year' },
  { a: 'Live without a smartphone for a month', b: 'Live without your laptop for a month' },
  { a: 'Have an AI that books everything for you', b: 'Have an AI that writes anything for you' },
  { a: 'Be a meme for a day', b: 'Be a Wikipedia page for a day' },
  { a: 'Have a thousand notifications you can\'t open', b: 'Have one notification you can\'t ignore' },
  { a: 'Lose every saved password', b: 'Lose every saved card on file' },
];

// Take N random unique prompts.
export function pickRandomPrompts(n: number, exclude: WyrPrompt[] = []): WyrPrompt[] {
  const excludeKeys = new Set(exclude.map((p) => `${p.a}|${p.b}`));
  const pool = WYR_PROMPTS.filter((p) => !excludeKeys.has(`${p.a}|${p.b}`));
  const shuffled = pool.slice().sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
