import type { Module } from './types';

// Amazon Seller Masterclass, part B: modules 5 to 8.

export const AMAZON_MODULES_B: Module[] = [
  {
    id: 'research-profit',
    title: 'Module 5: Product Research and Profit Math',
    lessons: [
      {
        id: 'product-research',
        title: 'How to Research Products Worth Selling',
        minutes: 15,
        body: [
          `Choosing the product is the biggest decision you will make. A great listing cannot rescue a product nobody wants, and a mediocre listing can still sell a product people badly need. Research first, then buy.`,
          `## What you are looking for`,
          `* Steady demand: shoppers search for it all year, or in a predictable seasonal pattern.`,
          `* Manageable competition: not dominated by a handful of huge brands with thousands of reviews.`,
          `* Room for profit after every fee, with a healthy gap between your cost and the selling price.`,
          `* Small, light, durable items, which cost less to ship and break less often.`,
          `* No gating or heavy restrictions, so you can actually list it.`,
          `## Use Amazon itself first`,
          `Search the products you are considering. Look at the Best Sellers lists in the category, the autocomplete suggestions as you type, and the first page of results. Note prices, review counts, and how new the top listings are. If new listings with few reviews are on page one, the category is open to newcomers.`,
          `## Read the sales rank`,
          `Every product shows a Best Sellers Rank. A lower number means more sales in that category. Compare ranks across competing products to estimate demand. Many sellers also use paid research tools that estimate monthly sales, search volume, and trends. These are helpful but they are estimates, so cross check them against what you see on Amazon.`,
          `## Study the reviews`,
          `Read the three star and one star reviews of top products. Complaints tell you what customers wish was better, which is where you can compete or where you should avoid a product entirely if the problem cannot be fixed.`,
          `## Avoid these traps`,
          `* Branded or licensed goods you have no authorization to sell.`,
          `* Products that need certifications, such as electronics, children's items, or anything ingestible, until you understand the rules in Module 11.`,
          `* Fragile, oversized, or heavy items with high shipping cost.`,
          `* Fads that will be gone in a month.`,
          `* Products with many suppliers and a race to the lowest price.`,
        ],
      },
      {
        id: 'profit-math',
        title: 'Profit Math: Know Your Numbers Before You Buy',
        minutes: 16,
        body: [
          `A product that looks profitable can lose money once every cost is counted. The only way to know is to do the math before you buy a single unit.`,
          `## The costs to include`,
          `* Product cost, including any minimum order effect.`,
          `* Shipping from the supplier to you or to Amazon.`,
          `* Amazon referral fee, which is a percentage of the price. It is 15 percent in most categories and ranges from 8 percent to 45 percent depending on the category, usually with a small minimum per item.`,
          `* Fulfillment cost: either FBA fees, or your own packing and shipping if you fulfill yourself.`,
          `* Storage and inbound fees if you use FBA, and the low inventory fee if you run too lean.`,
          `* Advertising cost.`,
          `* Returns, damages, and a small buffer for unexpected costs.`,
          `## Worked example one: merchant fulfilled or dropshipped`,
          `This example uses round numbers for illustration, not actual current prices.`,
          `* Selling price: $30.00`,
          `* Supplier cost, including their shipping to the customer: $15.00`,
          `* Referral fee at 15 percent: $4.50`,
          `* Advertising allowance at 10 percent: $3.00`,
          `* Profit before taxes: $30.00 minus $22.50 equals $7.50, a margin of 25 percent.`,
          `## Worked example two: FBA`,
          `Again an illustration. Look up the real fees for your exact product with Amazon's revenue calculator.`,
          `* Selling price: $30.00`,
          `* Product landed cost at your warehouse or prep center: $8.00`,
          `* Referral fee at 15 percent: $4.50`,
          `* FBA fulfillment fee for a small standard item, example: $4.00`,
          `* Storage, inbound, and prep allowance: $1.00`,
          `* Advertising allowance at 10 percent: $3.00`,
          `* Profit before taxes: $30.00 minus $20.50 equals $9.50, a margin of about 32 percent.`,
          `## Break even and advertising`,
          `Your break even advertising cost of sale, ACoS, equals your profit margin before ads. If your margin before ads is 35 percent, any ad campaign with an ACoS above 35 percent loses money on each sale. Knowing this number prevents the most common way new sellers burn through cash.`,
          `## Check the numbers with Amazon's own calculator`,
          `Amazon provides a free revenue calculator that estimates referral and fulfillment fees for an exact product. Use it on every product before you decide. Rule of thumb for beginners: aim for at least 25 to 30 percent margin before ads, so there is room to advertise and absorb surprises.`,
        ],
        links: [
          { label: 'Amazon Seller Central (revenue calculator inside)', url: 'https://sellercentral.amazon.com' },
        ],
      },
      {
        id: 'first-product',
        title: 'Validating and Choosing Your First Product',
        minutes: 12,
        body: [
          `Now combine the research and the math into one decision. Do not fall in love with a product. Make it earn its place.`,
          `## A simple scorecard`,
          `Rate each candidate from one to five on these points and pick the best total.`,
          `* Demand: steady searches and healthy sales rank.`,
          `* Competition: room for a newcomer.`,
          `* Margin: at least 25 to 30 percent before ads.`,
          `* Simplicity: small, light, durable, easy to describe.`,
          `* Access: no gating, no brand restriction, no certification hurdle.`,
          `* Supplier reliability: stock, speed, and quality you have checked.`,
          `## Validate before you commit`,
          `Order a sample and check quality. Search for a supplier alternative so you are not stuck with one source. Test the price against competitors by calculating what you would earn at a price that wins the Featured Offer, not your wishful price.`,
          `## Start small`,
          `For your first product, buy or list the smallest quantity that lets you learn. Your goal in the first 30 to 60 days is data: how people find the listing, how often they buy, how you handle orders, and what the true profit is.`,
          `## Decide what success looks like`,
          `Write down a target before you launch, such as a minimum number of sales and a minimum margin after fees. If the product meets it, scale. If it does not, change the price, listing, or ads. If it still fails, move on without regret. Testing products quickly and cheaply is the real skill.`,
        ],
      },
    ],
  },
  {
    id: 'dropshipping',
    title: 'Module 6: Dropshipping the Compliant Way',
    lessons: [
      {
        id: 'dropship-policy',
        title: 'Amazon Dropshipping Policy in Plain Language',
        minutes: 14,
        body: [
          `Amazon allows dropshipping, but only under strict conditions. Breaking them is one of the fastest ways to lose a seller account. This lesson explains the rules in plain language. Always read the current policy in Seller Central, because it is the final authority.`,
          `## The core rules`,
          `* You must be the seller of record. Your business must appear as the seller to the customer.`,
          `* You must remove any supplier, retailer, or third party names, logos, and prices from packing slips, invoices, and outer packaging. The package must show you as the seller.`,
          `* You are responsible for returns and customer service, even when a supplier ships the order.`,
          `* You must comply with the rest of Amazon's seller policies and terms.`,
          `## What is not allowed`,
          `You may not buy a product from another retailer, such as a large department store or an online marketplace, and have that retailer ship it straight to your Amazon customer. The retailer's packing slip and branding would identify the wrong seller, and you would not control the customer experience. Sellers who do this commonly face suspension, and the penalty for repeated violations can be permanent.`,
          `## What is allowed`,
          `Working with a manufacturer, wholesaler, or distributor that ships to your customers in blank or custom packaging that carries your business as the seller. That is why choosing the right supplier is the heart of compliant dropshipping.`,
          `## Why Amazon cares`,
          `Amazon wants the customer to know exactly who sold the item and who is accountable if something goes wrong. A package from an unfamiliar company with a different name creates confusion, and confusion creates complaints.`,
          `## The speed problem`,
          `Even a compliant supplier can sink you if shipping is slow. Amazon expects late shipments under 4 percent and cancellations before shipping under 2.5 percent. Suppliers that ship from overseas in 7 to 20 days make it hard to meet delivery promises, which is why many sellers prefer suppliers with warehouses in the United States.`,
          `## Protect yourself`,
          `Keep written agreements with suppliers that confirm blank packaging and your seller name, keep invoices, test order the full process yourself, and watch your account health daily.`,
        ],
        links: [
          { label: 'Amazon Seller Central (search: drop shipping policy)', url: 'https://sellercentral.amazon.com' },
        ],
      },
      {
        id: 'dropship-suppliers',
        title: 'Dropshipping Supplier Platforms and How to Choose',
        minutes: 15,
        body: [
          `Dropshipping platforms connect sellers with suppliers and often automate inventory updates and order forwarding. None of them is the single best choice. The right one depends on your budget, your products, and how fast the items must reach the customer. This lesson describes three widely used options. Details and prices change, so confirm everything on each company's own site before you commit. Mitype is not affiliated with these companies and does not guarantee their service.`,
          `## Spocket`,
          `Spocket curates suppliers, many based in the United States and Europe, and focuses on faster delivery, commonly two to five days. Plans are paid, with entry level pricing around $39.99 per month at the time of research. It suits sellers who care about delivery speed and branded invoicing. Fewer products are available than on larger catalog platforms.`,
          `## CJDropshipping`,
          `CJDropshipping offers a very large catalog of 400,000 or more products, a free subscription, and warehouses in the United States and other regions. Many products ship from China, with delivery often 7 to 20 days, and faster when stock is held in a local warehouse. It also offers custom packaging and product sourcing. It is popular for testing and for private label, but you must check shipping time per product against Amazon's expectations.`,
          `## Doba`,
          `Doba connects sellers to more than 160 supplier integrations, mainly in the United States and China, and automates inventory and price updates across channels including Amazon. It uses a paid subscription and suits sellers building a larger catalog who want one dashboard.`,
          `## How to choose`,
          `* Delivery time from the supplier location to your customers.`,
          `* Whether packaging and invoices can carry your business name.`,
          `* Product quality, which you confirm by ordering samples.`,
          `* Stock accuracy and how quickly the platform syncs inventory.`,
          `* Total cost, including subscription, product price, and shipping.`,
          `* Return handling and support responsiveness.`,
          `## Test before you trust`,
          `Place a real order with each candidate, shipped to yourself, and inspect the box, the packing slip, the speed, and the tracking. If the box shows another company's name, it is not compliant for Amazon.`,
        ],
        links: [
          { label: 'Spocket', url: 'https://www.spocket.co' },
          { label: 'CJDropshipping', url: 'https://cjdropshipping.com' },
          { label: 'Doba', url: 'https://www.doba.com' },
        ],
      },
      {
        id: 'dropship-workflow',
        title: 'Your Dropshipping Order Workflow From Sale to Delivery',
        minutes: 14,
        body: [
          `A written workflow keeps you compliant when you are busy. Here is a reliable routine you can adapt.`,
          `## Before the sale`,
          `* List only products your supplier has in stock, and keep your inventory quantities updated or automated.`,
          `* Set your handling time honestly, based on how long your supplier needs to ship.`,
          `* Price with your full costs included, including supplier shipping.`,
          `## When an order arrives`,
          `* Check the order in Seller Central and confirm the shipping address.`,
          `* Place the order with your supplier right away, using the customer's address, and confirm that the packing slip and packaging will show your business as the seller.`,
          `* Record the supplier order number.`,
          `## Tracking and confirmation`,
          `* As soon as the supplier ships, get the tracking number and confirm shipment in Seller Central with the correct carrier. Every shipment needs verifiable tracking regardless of carrier.`,
          `* Watch for delays. If tracking stalls, contact the supplier at once and contact the customer before they contact you.`,
          `## Problems and returns`,
          `* Respond to every customer message within 24 hours.`,
          `* Decide in advance who pays for return shipping and how returned goods are handled with each supplier.`,
          `* Never tell a customer to contact the supplier. As seller of record, the customer service is yours.`,
          `## Cancellations`,
          `If your supplier runs out of stock, cancel before shipping only when necessary, because pre fulfillment cancellations count against you. This is why accurate stock levels matter.`,
          `## Review weekly`,
          `Each week check your late shipment rate, cancellation rate, defect rate, and customer messages. Fix small problems before they become account health problems.`,
        ],
      },
    ],
  },
  {
    id: 'fba',
    title: 'Module 7: FBA Step by Step',
    lessons: [
      {
        id: 'fba-basics',
        title: 'How FBA Works and What It Costs',
        minutes: 14,
        body: [
          `FBA means you send inventory to Amazon and Amazon fulfills your orders. It is the engine behind the fast delivery shoppers expect, and this is the model that matches shipping products to Amazon facilities.`,
          `## The flow`,
          `* You source inventory from a supplier or manufacturer.`,
          `* You prepare and label each unit to Amazon's standards.`,
          `* You create a shipment in Seller Central and send it to the fulfillment center Amazon assigns.`,
          `* Amazon stores your units and, when customers order, picks, packs, ships, and handles customer service and returns for those orders.`,
          `* Amazon deposits your earnings after subtracting fees.`,
          `## The fees to expect`,
          `* Referral fee, a percentage of the sale price by category.`,
          `* FBA fulfillment fee, based on size and weight. Amazon raised average fulfillment fees by about $0.08 per unit on January 15, 2026.`,
          `* Monthly storage fees, which are higher in the fourth quarter holiday season.`,
          `* Inbound placement fees, which apply when you send inventory to a single location instead of splitting it. Amazon restructured these in January 2026.`,
          `* A low inventory level fee, which applies when you hold too little stock compared to demand. The threshold reported for 2026 is about 35 days of supply.`,
          `* Aged inventory and removal charges for units that sit too long or that you ask Amazon to return.`,
          `## Is FBA right for your product?`,
          `FBA works best for products that sell steadily, are small and light, and have margins that can absorb the fees. It works poorly for slow sellers, bulky items, or low priced items where fees consume the profit. Always run the profit math before sending inventory.`,
          `## Know the 2026 changes`,
          `Amazon ended its own prep and labeling services in the United States on January 1, 2026, and reported plans to end commingled inventory in 2026. Always confirm current rules in Seller Central before you ship.`,
        ],
      },
      {
        id: 'inbound',
        title: 'Preparing and Sending Inventory to Amazon',
        minutes: 16,
        body: [
          `This lesson walks through getting inventory into a fulfillment center. Because Amazon no longer prepares or labels units for you, accuracy matters. Units that arrive wrong can be refused or charged defect fees.`,
          `## Step one: list the product`,
          `Create or match the listing in Seller Central and choose FBA as the fulfillment method.`,
          `## Step two: use Send to Amazon`,
          `Amazon's Send to Amazon workflow guides every inbound shipment. The main steps are choosing the products and quantities, preparing the products, labeling the inventory, reviewing the shipment, choosing a shipping method, and confirming delivery.`,
          `## Step three: prepare each unit`,
          `* Make sure each unit is sealed and protected. Fragile items need real cushioning.`,
          `* Liquids and items that can leak must be properly sealed.`,
          `* Units sold as a set must be packaged and labeled as one item.`,
          `* Follow category specific prep rules shown in Seller Central.`,
          `## Step four: label correctly`,
          `Every unit must be scannable. You can apply Amazon's FNSKU barcode label to each unit, or in limited cases rely on a manufacturer barcode where Amazon allows it. Labels must scan the first time, sit on a flat spot, and not cover other barcodes. Many sellers hire a prep center to receive supplier goods, label, inspect, and forward them to Amazon for a per unit fee.`,
          `## Step five: ship`,
          `You can use Amazon's partnered carrier program, which usually offers discounted rates, or arrange your own carrier. Small shipments go by parcel, and larger ones go by pallet or freight. Print the shipment labels and box content details, and attach them as instructed.`,
          `## Step six: track check in`,
          `Amazon scans your shipment when it arrives. This can take days or weeks in busy seasons. Watch the shipment status for receiving problems and respond quickly.`,
          `## Costs of mistakes`,
          `Non compliant units can incur defect fees per unit. For standard size items, reported ranges are from about $0.32 to $5.72 per unit, and up to about $8.25 for bulky items. The cure is careful preparation and a pilot shipment of a few units before sending a large batch.`,
        ],
      },
      {
        id: 'inventory-planning',
        title: 'Inventory Planning, Restocking, and Storage Limits',
        minutes: 12,
        body: [
          `Running out of stock loses sales and ranking. Holding too much stock ties up cash and costs storage fees. Good planning keeps you between the two.`,
          `## Know your sales velocity`,
          `Track how many units you sell per day over the last 30 days. Divide your stock on hand by that daily number to see how many days of supply you have.`,
          `## Plan for lead time`,
          `Add up the time to order from your supplier, produce, ship to you or a prep center, prepare, ship to Amazon, and get checked in. If that total is 45 days, you must reorder before your stock drops below roughly 45 days plus a safety buffer.`,
          `## Avoid the low inventory fee and stockouts`,
          `Keep enough supply so you do not trigger the low inventory fee, and so you do not lose the Featured Offer when you go out of stock.`,
          `## Avoid overstock`,
          `Excess units pay monthly storage and may incur aged inventory charges. Run promotions, lower the price, or remove units before they become expensive to hold.`,
          `## Know your storage limits`,
          `Amazon sets storage limits based on your performance and sales history. New sellers often have lower limits, so build up gradually and keep your account in good standing.`,
          `## Seasonal planning`,
          `Order early for peak times such as Prime Day events and the holiday season, because Amazon checks in inventory slower when it is busy, and fees can rise. Amazon announced holiday fees would stay flat in 2026, but check current schedules.`,
          `## Keep a simple tracker`,
          `Record each product's stock, daily sales, lead time, and reorder date in one sheet and review it weekly.`,
        ],
      },
    ],
  },
  {
    id: 'listings',
    title: 'Module 8: Listings, Brand Registry, and Reviews',
    lessons: [
      {
        id: 'create-listing',
        title: 'Creating a Listing That Ranks and Converts',
        minutes: 16,
        body: [
          `Your listing has two jobs. It must help Amazon match your product to what shoppers search for, and it must persuade a shopper to buy once they land on it.`,
          `## Product identifiers`,
          `Most products need a GTIN, usually a UPC. Barcodes bought from the official standards organization are accepted and protect you from problems later. If a product legitimately has no barcode, such as some handmade or private label goods, Amazon offers a GTIN exemption, which requires the brand to exist in Amazon's system. Never use random or cheap resold barcodes, because they can cause listing removals.`,
          `## The title`,
          `Include the brand, the product type, the key feature, and important details such as size, color, or quantity. Follow Amazon's category style rules, avoid promotional words, and keep it readable.`,
          `## Bullet points`,
          `Lead each bullet with a benefit and then the feature. Answer the questions a buyer would ask, such as size, material, compatibility, and what is included.`,
          `## Images`,
          `Images drive conversion more than almost anything. Use a clean main image on a white background, then add lifestyle images, size comparisons, infographics, and close ups. Use high resolution so zoom works.`,
          `## Description and backend terms`,
          `Write a clear description and fill the backend search terms with relevant words you did not use elsewhere. Do not repeat words unnecessarily and never include competitor brand names.`,
          `## Price and offer`,
          `Set a price that can win the Featured Offer and still protect your margin. Make sure your shipping settings and handling time are honest.`,
          `## Optimize with data`,
          `After launch, watch your sessions and unit session percentage, the share of visitors who buy. If traffic is fine but conversion is weak, improve images, price, or reviews. If traffic is low, improve keywords and advertising.`,
        ],
      },
      {
        id: 'brand-registry',
        title: 'Brand Registry, A+ Content, and Vine',
        minutes: 13,
        body: [
          `If you sell your own brand, Brand Registry gives you tools that make your listings stronger and protect them from copycats.`,
          `## What you need`,
          `You need an active registered trademark for your brand in the country where you enroll, or a pending application that Amazon now accepts in many cases. In the United States this is through the government trademark office. Your brand name must match the trademark exactly, and your brand name or logo must appear on the product or packaging.`,
          `## What Brand Registry unlocks`,
          `* A+ Content, richer product descriptions with extra images and comparison charts. Reported conversion lifts range from about 3 to 10 percent.`,
          `* Sponsored Brands advertising.`,
          `* Brand protection tools to report counterfeits and listing hijackers.`,
          `* Brand Analytics, with data on what shoppers search for.`,
          `* Manage Your Experiments, for testing images and content.`,
          `* Amazon Vine, where Amazon invites trusted reviewers to review your new product, covered below.`,
          `## Is it worth it?`,
          `For private label sellers, yes. It protects your listing and improves conversion. For sellers of other brands' products, it does not apply, and the brand owner controls it.`,
          `## Start the trademark early`,
          `Trademark applications take time. If you plan a private label product, apply early so you are ready when your product launches.`,
          `## Watch for lookalikes`,
          `Choose a distinctive brand name that is not already taken, and search the trademark database first to avoid rejections or conflicts.`,
        ],
        links: [
          { label: 'Amazon Brand Registry', url: 'https://brandregistry.amazon.com' },
          { label: 'U.S. Patent and Trademark Office', url: 'https://www.uspto.gov' },
          { label: 'GS1 US barcodes', url: 'https://www.gs1us.org' },
        ],
      },
      {
        id: 'reviews-service',
        title: 'Reviews, Customer Service, and Returns',
        minutes: 13,
        body: [
          `Reviews and service decide whether shoppers buy and whether Amazon keeps showing your products.`,
          `## Rules on reviews`,
          `Reviews must come from genuine customers. You may not offer money, free products, discounts, or gifts in exchange for reviews, you may not ask only happy customers to review, and you may not pay for or trade reviews. Violations can lead to account removal. Do not ask family and friends to post reviews on your own products.`,
          `## Legitimate ways to earn reviews`,
          `* Deliver a good product that arrives as described.`,
          `* Use Amazon's built in Request a Review button, which sends a compliant request after delivery.`,
          `* Use Amazon Vine if your brand is eligible.`,
          `* Include a helpful insert that thanks the buyer and offers support, without asking for a positive review.`,
          `## Customer messages`,
          `Respond within 24 hours, be polite, and be specific. Amazon measures your response time. Do not try to move customers off Amazon, and do not include outside links or promotions.`,
          `## Returns`,
          `Amazon allows customers to return most items. With FBA, Amazon handles returns. With merchant fulfillment, you set a return policy that must meet Amazon's standards, and you handle returned items. Review why items come back, because a pattern points to a product or listing problem you can fix.`,
          `## Negative feedback and claims`,
          `Resolve problems quickly with refunds or replacements when appropriate. Unresolved issues can become A to z claims, which count against your defect rate. You can request removal of feedback that violates Amazon's guidelines, but not simply because it is negative.`,
        ],
      },
    ],
  },
];
