import type { Module } from './types';

// Amazon Seller Masterclass, part C: modules 9 to 13.

export const AMAZON_MODULES_C: Module[] = [
  {
    id: 'buy-box',
    title: 'Module 9: Winning the Buy Box',
    lessons: [
      {
        id: 'buy-box-how',
        title: 'How the Buy Box and Featured Offer Work',
        minutes: 14,
        body: [
          `The Buy Box is the Add to Cart and Buy Now area on a product page. Amazon now also calls the winning position the Featured Offer. More than 80 percent of purchases happen through it, so on a page shared by many sellers, winning it is the difference between steady sales and almost none.`,
          `## It rotates`,
          `When several qualified sellers offer the same product, Amazon does not pick one winner forever. The Buy Box rotates among eligible offers, giving each a share of the time. Your goal is to qualify and then earn the largest share. Share can change by the hour as prices, stock, and performance change.`,
          `## Who is eligible`,
          `* You need a Professional selling account.`,
          `* Your account must be in good standing with healthy performance metrics.`,
          `* The product must be in a category and condition that qualifies, usually new.`,
          `* Your offer must be in stock and priced competitively.`,
          `* For new sellers, Amazon may require some sales history before you win much share. Sellers new to a listing often get a limited chance first.`,
          `## What Amazon weighs`,
          `Amazon does not publish an exact formula. The commonly reported factors include fulfillment method, the total landed price including shipping, seller performance metrics, shipping speed, stock level, and whether your listing is healthy and not suppressed. Price is only one factor. A cheaper offer from a seller with poor metrics usually loses to a slightly higher priced offer from a seller with strong metrics.`,
          `## Fulfillment matters`,
          `FBA offers carry a structural advantage because of fast, reliable delivery. FBA sellers are commonly reported to win the Buy Box three to five times more often than merchant fulfilled sellers on the same listing. Merchant fulfilled sellers can still win with fast, tracked, reliable shipping.`,
          `## Delivery speed is rising in importance`,
          `Local delivery speed carries more weight than in the past. A seller who can deliver in one day can beat a cheaper competitor who needs two.`,
          `## A reality check`,
          `You cannot buy the Buy Box or force it. You earn it by combining a competitive price, fast fulfillment, and excellent metrics.`,
        ],
      },
      {
        id: 'buy-box-win',
        title: 'Winning and Keeping the Buy Box',
        minutes: 14,
        body: [
          `Use this action list, in this order. Fix the foundation before you adjust price.`,
          `## 1. Protect your metrics`,
          `* Order defect rate under 1 percent.`,
          `* Late shipment rate under 4 percent.`,
          `* Pre fulfillment cancellation rate under 2.5 percent.`,
          `* High valid tracking, meaning every shipment has real, working tracking.`,
          `If one of these slips, Amazon can reduce your share across your whole catalog, not just one listing.`,
          `## 2. Use fast, reliable fulfillment`,
          `Choose FBA for products where you want the strongest position. If you ship yourself, set honest handling times, ship the same day when possible, and use trackable services.`,
          `## 3. Price to the landed total`,
          `Compare your item price plus shipping to the competition. You do not have to be the cheapest, but you should be close to the lowest comparable offers from sellers with similar delivery.`,
          `## 4. Keep stock available`,
          `If you go out of stock, you lose your position and may take time to regain it. Reorder in time.`,
          `## 5. Respond fast to buyers`,
          `Answer messages within 24 hours.`,
          `## 6. Use repricing carefully`,
          `Repricing tools adjust your price automatically based on rules. Set a minimum price that protects your margin, so the tool never pushes you into a loss. Avoid races to the bottom, where two sellers keep undercutting each other until neither makes money.`,
          `## 7. Build your own brand when you can`,
          `If you are the only seller of your product, as with private label under Brand Registry, you own the Buy Box on your listing. This is one of the strongest reasons sellers move toward private label.`,
          `## 8. Watch your listing health`,
          `A suppressed listing cannot win. Check for suppression alerts in Seller Central and fix them promptly.`,
          `## Monitor and adjust`,
          `Check your Buy Box percentage on the Business Reports page by product. If the percentage drops, look first at stock, metrics, shipping, and price changes by competitors.`,
        ],
      },
    ],
  },
  {
    id: 'ads',
    title: 'Module 10: Amazon Advertising',
    lessons: [
      {
        id: 'sponsored-products',
        title: 'Setting Up Sponsored Products',
        minutes: 15,
        body: [
          `Most new listings need advertising to get seen. Sponsored Products is the most beginner friendly and the most important ad type. These are the ads that appear in search results and on product pages, labeled Sponsored.`,
          `## How it works`,
          `Amazon advertising is a pay per click auction. You pay only when a shopper clicks, not when they see the ad. You bid on keywords, or on specific products, and Amazon shows your ad when it fits.`,
          `## Key terms`,
          `* ACoS, advertising cost of sale: ad spend divided by ad sales. A 20 percent ACoS means you spent $20 to make $100 in ad sales.`,
          `* ROAS, return on ad spend: ad sales divided by ad spend. It is the same idea turned upside down.`,
          `* Click through rate and conversion rate, which show how well your ad and listing work.`,
          `* Break even ACoS: your profit margin before ads. You lose money above it.`,
          `## Your first campaign`,
          `* Make sure your listing is complete and competitive before you advertise.`,
          `* Start with one automatic campaign. Amazon chooses the keywords and targets for you, which teaches you what shoppers use.`,
          `* Set a small daily budget you can afford to lose while learning.`,
          `* Use dynamic bidding settings suited to your goal, and start with moderate bids.`,
          `* Let the campaign collect data for one to two weeks before making large changes.`,
          `## Then move to manual campaigns`,
          `Read the search term report from your automatic campaign. Take the search terms that produce sales and place them in a manual campaign with controlled bids. Add terms that cost money without producing sales as negative keywords so you stop paying for them.`,
          `## Add other ad types later`,
          `Sponsored Brands, which need Brand Registry, and Sponsored Display come after your Sponsored Products campaigns are consistently profitable.`,
        ],
        links: [
          { label: 'Amazon Ads', url: 'https://advertising.amazon.com' },
        ],
      },
      {
        id: 'ads-optimize',
        title: 'The Weekly Optimization Loop and New Creative Tools',
        minutes: 12,
        body: [
          `Advertising rewards a steady routine, not constant tinkering. Use this weekly loop.`,
          `## The weekly loop`,
          `* Review the search term report. Promote winning terms to manual campaigns.`,
          `* Add negative keywords for terms that spent money without sales.`,
          `* Adjust bids. Lower bids on terms with ACoS above your break even, and raise bids on profitable terms that get few impressions.`,
          `* Check budgets so your best campaigns do not run out of budget early in the day.`,
          `* Look at the overall result in your profit, not just ACoS. Sales driven by ads also lift your organic ranking, so a campaign near break even can still help your listing grow.`,
          `## Launch, stabilize, scale`,
          `At launch you spend more to gather data and reviews, accepting low or break even returns. When the listing is stable, you tune for profit. When profit is steady, you scale budgets and add campaigns.`,
          `## Common beginner mistakes`,
          `* Advertising a listing with weak images, price, or reviews.`,
          `* Using a huge budget before learning what works.`,
          `* Never adding negative keywords.`,
          `* Changing settings every day so no data can build.`,
          `* Ignoring margin and chasing sales volume at a loss.`,
          `## New creative tools`,
          `Amazon announced at its 2026 seller conference that Creative Studio is available to sellers at no charge. It can generate lifestyle images from a product photo, create short video ads from still images, and produce audio ads. Amazon reported an average sales lift of about 12 percent for users, though your results will vary. Try it on a few products and compare results against your existing creative.`,
        ],
      },
    ],
  },
  {
    id: 'compliance',
    title: 'Module 11: Compliance, Account Health, and Suspensions',
    lessons: [
      {
        id: 'policies',
        title: 'Policies, Restricted Products, and Intellectual Property',
        minutes: 15,
        body: [
          `You can lose an account in a day for something you did not know was against the rules. Learn them before you list.`,
          `## Restricted and gated categories`,
          `Some categories require approval before you can sell. Commonly gated areas include certain automotive items, supplements and nutritional products, beauty and personal care, fine jewelry and watches, luxury goods, shoes and handbags, and wine and spirits. Approval often requires supplier invoices, brand authorization letters, or lab testing. Amazon has been tightening documentation, so start collecting invoices early.`,
          `## Brand gating`,
          `Even if a category is open, individual brands can be gated at the request of the brand owner. You may need written authorization from the brand to sell it.`,
          `## Restricted and hazardous products`,
          `Some products cannot be sold at all, and others, such as batteries, aerosols, and flammables, need special handling and safety documents. Check the restricted products list for any item before you buy it.`,
          `## Safety and certification`,
          `Children's products, electronics, and many other items require safety testing and certification. Selling an uncertified product can lead to listing removal and legal exposure.`,
          `## Intellectual property`,
          `* Never sell counterfeit or unauthorized copies.`,
          `* Do not use another company's trademarked brand name, logos, or images without permission.`,
          `* Do not copy another seller's photos or text.`,
          `* Respect patents and copyrights. A single complaint from a rights owner can suspend a listing, and repeated complaints can suspend an account.`,
          `## Product condition and authenticity`,
          `Sell only genuine, correctly described products. Keep invoices that prove where your inventory came from.`,
          `## Stay current`,
          `Read policy updates in Seller Central, which Amazon sends as notices. Many suspensions happen because a seller never read a policy change.`,
        ],
      },
      {
        id: 'account-health',
        title: 'Account Health, Suspensions, and Plans of Action',
        minutes: 15,
        body: [
          `Account health is Amazon's report card for you. Check it every day.`,
          `## The main performance metrics`,
          `* Order defect rate: under 1 percent.`,
          `* Late shipment rate: under 4 percent.`,
          `* Pre fulfillment cancellation rate: under 2.5 percent.`,
          `* Valid tracking rate: high, because every merchant fulfilled shipment needs verifiable tracking from any carrier.`,
          `## The Account Health Rating`,
          `Amazon also uses a score. As of 2026 guidance, 200 to 1,000 is healthy, 100 to 199 is at risk, and 99 or lower is in the danger zone. Every seller starts at the baseline, and points are deducted when policies are violated or metrics slip, and restored when problems are resolved. Lower scores in the healthy range can draw more automatic review.`,
          `## Common causes of suspension`,
          `* Poor metrics.`,
          `* Intellectual property or authenticity complaints.`,
          `* Review manipulation.`,
          `* Dropshipping from retailers or hiding the true seller.`,
          `* Selling restricted products.`,
          `* Related accounts, such as opening a second account without permission.`,
          `## If you are suspended`,
          `Stay calm and read the notice carefully. Amazon will tell you the reason and often how to appeal. Do not open a new account.`,
          `## Writing a plan of action`,
          `An appeal usually requires a plan of action with three parts.`,
          `* Root cause: what went wrong, in your own honest words.`,
          `* Corrective actions: what you have already fixed.`,
          `* Preventive measures: what you will do so it does not happen again.`,
          `Attach documents such as invoices and proof of changes. Be specific, concise, and respectful. Take responsibility rather than blaming Amazon or buyers. If the first appeal is rejected, read the feedback and revise it.`,
          `## Prevention is cheaper`,
          `Keep your metrics healthy, keep invoices, follow policies, and check Seller Central daily. If you face a serious suspension, consider professional help from a reputable consultant, and be careful about anyone who guarantees reinstatement.`,
        ],
      },
    ],
  },
  {
    id: 'features-fees-taxes',
    title: 'Module 12: 2026 Features, Fees, and Taxes',
    lessons: [
      {
        id: 'new-features',
        title: 'New Features Sellers Should Know About in 2026',
        minutes: 14,
        body: [
          `Amazon announced a wave of seller tools at its seller conference in September 2026. Features roll out in stages, so check which are available to your account.`,
          `## Seller Assistant`,
          `Amazon's AI companion for sellers evolved from a chat tool into an always on assistant. It now keeps persistent memory of your pricing patterns, inventory cycles, and goals. It can run standing workflows when you are not logged in, monitor your account for issues, and, with your permission, act on your behalf. It is free for all sellers. Amazon also announced a plugin that connects Seller Central data to outside AI tools, launching with Amazon Quick and in beta with Anthropic's Claude. Treat AI suggestions as help, not as final decisions, and review any action before you approve it.`,
          `## Creative Studio`,
          `Free for all sellers. It generates lifestyle images, video ads from still product images, and audio ads. Covered in Module 10.`,
          `## Multichannel selling from Seller Central`,
          `Amazon introduced tools that let United States sellers manage selling on other platforms, including eBay, Shopify, TikTok Shop, and Walmart, from within Seller Central.`,
          `## Prime delivery beyond Amazon`,
          `Merchants using Multi Channel Fulfillment can offer Prime badging and delivery on orders from their own websites, with no cost beyond standard Multi Channel Fulfillment fees.`,
          `## Amazon Warehousing and Distribution`,
          `The bulk storage service continued expanding internationally.`,
          `## Amazon Quick Plus offer`,
          `Amazon offered 12 months of Amazon Quick Plus at no charge to primary account holders until December 31, 2026. Check Seller Central for eligibility.`,
          `## Fee and policy changes earlier in 2026`,
          `* FBA fulfillment fees rose by an average of about $0.08 per unit on January 15, 2026.`,
          `* Inbound placement fees were restructured in January 2026.`,
          `* Amazon ended its own FBA prep and labeling services in the United States on January 1, 2026.`,
          `* Defect fees for non compliant inbound shipments increased.`,
          `* Referral fees held steady.`,
          `* Multi Channel Fulfillment and Buy with Prime fees rose, and Amazon introduced a preferred pricing program for Multi Channel Fulfillment with discounts reported at 15 to 25 percent for the first six months.`,
          `Always confirm details in Seller Central, because Amazon adjusts programs frequently.`,
        ],
        links: [
          { label: 'Amazon Selling Partners news', url: 'https://sellingpartners.aboutamazon.com' },
        ],
      },
      {
        id: 'fee-overview',
        title: 'Fee Overview: Where Every Dollar Goes',
        minutes: 12,
        body: [
          `Here is a one page map of what Amazon can charge. Use it as a checklist whenever you calculate profit.`,
          `## Account level`,
          `* Individual plan: $0.99 per item sold.`,
          `* Professional plan: $39.99 per month.`,
          `## Per sale`,
          `* Referral fee: a percentage of the sale price. In most categories it is 15 percent, with a range from 8 percent for items such as consumer electronics to higher percentages in some categories. Most categories have a minimum per item. Some categories use tiers, with one percentage up to a price and a lower percentage above it.`,
          `* Closing fees on certain media items.`,
          `## FBA charges`,
          `* Fulfillment fee based on size and weight.`,
          `* Monthly storage, higher in the holiday season.`,
          `* Inbound placement fee when you send to a single location.`,
          `* Low inventory level fee when stock is too thin for demand.`,
          `* Aged inventory surcharges.`,
          `* Removal and disposal fees.`,
          `* Inbound defect fees when units arrive non compliant.`,
          `* Optional label service where available.`,
          `## Other costs`,
          `* Advertising spend.`,
          `* Returns processing and unsellable units.`,
          `* Your own prep, supplies, supplier, and shipping costs.`,
          `* Software and tools you choose to use.`,
          `## How to use this list`,
          `Open the revenue calculator, enter your product, and note every fee it shows. Add advertising and returns as percentages. If the product still clears your target margin, it passes. If not, change the price, find a cheaper supplier, or pick a different product.`,
        ],
      },
      {
        id: 'taxes',
        title: 'Taxes for Amazon Sellers',
        minutes: 13,
        body: [
          `This lesson is general education, not tax advice. Speak with a licensed accountant who understands online selling. Rules differ by state and situation.`,
          `## Income tax`,
          `Your Amazon profit is taxable income, whether or not you receive a tax form. Profit equals your sales minus your costs of goods and business expenses. Sole proprietors and single member LLCs usually report this on a Schedule C with their personal return, and may owe self employment tax. Many sellers also make quarterly estimated payments.`,
          `## Form 1099-K`,
          `Payment platforms report certain income to the IRS. For the 2026 tax year, the federal reporting threshold is reported as more than $20,000 in gross sales and more than 200 transactions. The form shows gross sales, not profit. You must report all business income even if you receive no form.`,
          `## Sales tax`,
          `Amazon collects and remits sales tax for most orders in nearly every state with a sales tax, under marketplace facilitator laws. That does not remove every obligation. Depending on your state and where you hold inventory or reach sales thresholds, you may need to register for a sales tax permit or file returns. Holding FBA inventory in several states can create tax presence in those states, so ask your accountant.`,
          `## Resale certificates`,
          `Wholesalers may ask for a resale certificate so you do not pay sales tax on inventory you resell.`,
          `## Deductible expenses`,
          `Common business expenses include inventory cost, shipping, Amazon fees, advertising, software, supplies, and a portion of certain home office costs. Only deduct real, documented expenses.`,
          `## Bookkeeping habits`,
          `* Keep a separate business bank account and card.`,
          `* Download Amazon reports monthly.`,
          `* Save every invoice and receipt.`,
          `* Track inventory on hand at year end.`,
          `* Consider bookkeeping software or an accountant from the start. The cost is far less than the cost of a tax problem.`,
        ],
        links: [
          { label: 'IRS small business and self employed', url: 'https://www.irs.gov/businesses/small-businesses-self-employed' },
        ],
      },
    ],
  },
  {
    id: 'launch-plan',
    title: 'Module 13: Your 90 Day Launch Plan',
    lessons: [
      {
        id: 'ninety-days',
        title: 'Your 90 Day Plan From Zero to First Profit',
        minutes: 18,
        body: [
          `This plan ties every module together. It is built to be followed week by week. Adjust it to your budget and pace.`,
          `## Days 1 to 14: Foundation`,
          `* Decide your structure, get an EIN, and open a business bank account.`,
          `* Gather your documents and register your Professional account.`,
          `* Complete verification and tour Seller Central.`,
          `* Set your startup budget and your testing budget.`,
          `## Days 15 to 30: Research`,
          `* Research at least 20 product ideas using the scorecard from Module 5.`,
          `* Run the profit math on your top five.`,
          `* Contact suppliers, request invoices and samples, and vet them.`,
          `* Choose one or two products to test.`,
          `## Days 31 to 45: List and launch`,
          `* Create strong listings with proper identifiers and good images.`,
          `* Choose your fulfillment method for each product, either compliant dropshipping, merchant fulfillment, or FBA.`,
          `* Place your first small inventory order or set up the supplier workflow, and test an order yourself.`,
          `* Start a small automatic Sponsored Products campaign.`,
          `## Days 46 to 60: Operate and learn`,
          `* Fulfill orders on time and respond to messages in 24 hours.`,
          `* Check account health daily.`,
          `* Run the weekly ad loop.`,
          `* Track your true profit after every fee on each product.`,
          `## Days 61 to 75: Improve`,
          `* Improve the listing from the data: images, price, and keywords.`,
          `* Move winning search terms to manual campaigns and add negative keywords.`,
          `* Work on earning genuine reviews through great service and Amazon's compliant tools.`,
          `* Review your Buy Box percentage and fix whatever is hurting it.`,
          `## Days 76 to 90: Decide and scale`,
          `* Compare each product to the targets you set at the start.`,
          `* Reorder or scale winners. Cut or change losers.`,
          `* Consider moving a winning product into wholesale or private label, and start the trademark.`,
          `* Plan inventory and timing for the next busy season.`,
          `* Write down what you learned, and plan the next 90 days.`,
          `## The honest truth`,
          `Most sellers do not reach large profits in 90 days, and that is normal. By day 90, you should understand your numbers, your suppliers, and your customers far better than you did, and you should know which products deserve more of your money. That knowledge is what lasting Amazon businesses are built on.`,
        ],
      },
      {
        id: 'scaling',
        title: 'Seasonal Planning and Scaling Safely',
        minutes: 13,
        body: [
          `Once you have a product that works, growth comes from doing the basics at a larger scale, without breaking what made it work.`,
          `## Plan around the calendar`,
          `Amazon sales surge during Prime Day events and the fourth quarter holiday season. Plan inventory, advertising, and listing updates weeks ahead. Be careful about overbuying, because storage fees and aged inventory charges follow the season.`,
          `## Expand your catalog carefully`,
          `Add related products to a proven niche so your brand knowledge and customers carry over. Keep each new product through the same research and profit checks.`,
          `## Strengthen your supply`,
          `Develop a second supplier for your best products. Negotiate better terms as your volumes rise. Keep communicating about quality.`,
          `## Build a brand`,
          `Register a trademark, enroll in Brand Registry, build A+ Content, and consider a simple website for repeat customers and email. A brand reduces competition on the page and helps you win the Featured Offer.`,
          `## Sell beyond Amazon`,
          `With Multi Channel Fulfillment and the 2026 multichannel tools, you can sell on other platforms using the inventory you already hold at Amazon. Add channels one at a time.`,
          `## Get help when it pays for itself`,
          `As volume grows, consider a virtual assistant for customer messages and listing work, an accountant, and a prep center. Give help written procedures, and keep control of your account login and finances.`,
          `## Protect the foundation`,
          `Growth stresses metrics. Keep watching late shipments, defects, and stock. Scaling a problem only makes it bigger.`,
          `## Keep learning`,
          `Read Seller Central announcements, join seller forums, and revisit this masterclass as rules change. Amazon changes fast, and sellers who keep learning stay ahead.`,
        ],
      },
      {
        id: 'glossary',
        title: 'Glossary of Amazon Seller Terms',
        minutes: 8,
        body: [
          `Keep this glossary open while you work.`,
          `* ACoS: advertising cost of sale. Ad spend divided by ad sales.`,
          `* AWD: Amazon Warehousing and Distribution, a bulk storage service.`,
          `* ASIN: Amazon Standard Identification Number, the ID for a product page.`,
          `* A+ Content: enhanced product descriptions available through Brand Registry.`,
          `* BSR: Best Sellers Rank, a ranking that reflects sales in a category.`,
          `* Buy Box or Featured Offer: the purchase box where one offer is shown to the shopper.`,
          `* FBA: Fulfillment by Amazon.`,
          `* FBM: Fulfillment by Merchant, meaning you ship orders yourself.`,
          `* FNSKU: Fulfillment Network Stock Keeping Unit, the barcode Amazon uses to track your units in FBA.`,
          `* GTIN: Global Trade Item Number, such as a UPC, a barcode number for a product.`,
          `* MCF: Multi Channel Fulfillment, using FBA inventory for orders from other places.`,
          `* ODR: order defect rate, the share of orders with negative feedback, A to z claims, or chargebacks.`,
          `* PPC: pay per click advertising.`,
          `* Plan of action: your written response to an Amazon suspension.`,
          `* Private label: products made for you and sold under your own brand.`,
          `* ROAS: return on ad spend.`,
          `* Seller Central: the dashboard where third party sellers manage their business.`,
          `* Seller of record: the business shown as the seller of an order and responsible for it.`,
          `* SFP: Seller Fulfilled Prime.`,
          `* SKU: Stock Keeping Unit, your own code for a product.`,
          `* Vendor Central: the system for first party suppliers who sell wholesale to Amazon by invitation.`,
          `* Vine: Amazon's program that invites trusted reviewers to review new products.`,
        ],
      },
    ],
  },
];
