import type { Module } from './types';

// Amazon Seller Masterclass, part A: modules 1 to 4.
// Figures and policies reflect what was published as of October 2026.
// Amazon changes rules often, so lessons point learners to Seller
// Central for the final word.

export const AMAZON_MODULES_A: Module[] = [
  {
    id: 'how-amazon-works',
    title: 'Module 1: How Amazon Works for Sellers',
    lessons: [
      {
        id: 'marketplace',
        title: 'The Amazon Marketplace and Where Sellers Fit',
        minutes: 14,
        body: [
          `Before you spend a dollar, you need a clear picture of how Amazon is built. Amazon is two businesses in one storefront. In the first, Amazon buys products wholesale from brands and sells them itself. This is called first party, and brands manage it through a separate system called Vendor Central by invitation. In the second, independent businesses list their own products and Amazon provides the customers, the website, the payments, and optionally the warehouses and delivery. This is called third party, and it is what this course is about. You manage it in a tool called Seller Central.`,
          `A majority of the units sold on Amazon now come from independent sellers like the people taking this course. That matters for you, because it means Amazon is actively built to support sellers, and it also means you are competing with thousands of them.`,
          `## The catalog and the ASIN`,
          `Amazon keeps one catalog. Every product gets one product page, identified by a number called an ASIN. If you want to sell a product that already exists, you do not create a new page. You attach your offer to the existing page. That means many sellers can be selling the exact same item on the exact same page at the same time.`,
          `## Why that matters: the Featured Offer`,
          `When several sellers offer the same product, Amazon shows one offer in the main purchase box on the page, the Add to Cart and Buy Now buttons. This was long called the Buy Box, and Amazon now also calls it the Featured Offer. Over 80 percent of purchases happen through it. Everything else on the page, including other sellers listed under See All Buying Options, gets a small share of sales. Winning that position is one of the central skills in this course, and Module 9 is dedicated to it.`,
          `## The three things Amazon gives you`,
          `* Traffic: shoppers already searching to buy, which is the hardest thing for any new business to create.`,
          `* Trust: customers buy from Amazon, so they trust the checkout, the returns, and the delivery promise.`,
          `* Infrastructure: payments, customer service tools, and, if you choose, warehousing and shipping.`,
          `## What Amazon expects in return`,
          `Amazon expects you to protect the customer experience. You ship on time, you describe products accurately, you handle problems quickly, and you follow its policies. Sellers who do this are rewarded with visibility and the Featured Offer. Sellers who do not are limited or suspended. Think of Amazon as a partner with strict standards, not as a place where you can do whatever you want.`,
        ],
        links: [
          { label: 'Amazon Seller Central', url: 'https://sellercentral.amazon.com' },
          { label: 'Sell on Amazon overview', url: 'https://sell.amazon.com' },
        ],
      },
      {
        id: 'fulfillment-options',
        title: 'Selling Models and Fulfillment Options Explained',
        minutes: 15,
        body: [
          `There are two separate decisions every Amazon seller makes, and beginners often mix them up. The first is where your products come from, which is called your sourcing model. The second is who packs and ships the order to the customer, which is your fulfillment method. This lesson covers fulfillment. Module 4 covers sourcing.`,
          `## Fulfillment by Amazon, or FBA`,
          `You send your inventory to Amazon warehouses, which are called fulfillment centers. When a customer orders, Amazon picks, packs, and ships it, handles customer service and returns for that order, and your offer carries the Prime badge. You pay fees for fulfillment and storage. FBA offers shoppers the fast delivery they expect and is commonly reported to win the Featured Offer three to five times more often than merchant fulfilled offers on the same listing.`,
          `## Fulfillment by Merchant, or FBM`,
          `You keep the inventory, or arrange for a supplier to hold it, and you ship every order yourself. You pay no Amazon storage or fulfillment fees, but you carry the responsibility for speed, packaging, tracking, and returns. Late shipments and missing tracking hurt your account health directly.`,
          `## Seller Fulfilled Prime`,
          `If your own shipping is consistently fast, Amazon can qualify you to show the Prime badge on offers you ship yourself. It is demanding, but it lets strong operators keep control of their inventory and still get the Prime advantage.`,
          `## Multi Channel Fulfillment and Warehousing and Distribution`,
          `Multi Channel Fulfillment lets Amazon ship orders that come from other places, such as your own website or other marketplaces, out of your FBA inventory. Amazon Warehousing and Distribution is a lower cost storage service for bulk inventory that replenishes your FBA stock as needed. Both are growth tools, not starting tools.`,
          `## Where dropshipping fits`,
          `Dropshipping is a sourcing and shipping arrangement where a supplier ships the order directly to your customer. On Amazon it is a form of merchant fulfillment, so it is judged on the same speed and tracking standards, and it has special rules covered in Module 6.`,
          `## Choosing for now`,
          `A simple rule for beginners: use FBM or dropshipping to test products with little cash at risk, and use FBA for products that prove they sell and that you want to scale. Many successful sellers do both at once, depending on the product.`,
        ],
      },
    ],
  },
  {
    id: 'business-foundations',
    title: 'Module 2: Business Foundations',
    lessons: [
      {
        id: 'legal-setup',
        title: 'Legal and Financial Setup Before You Sell',
        minutes: 13,
        body: [
          `This lesson is general education, not legal or tax advice. Rules differ by state and by situation, so confirm your choices with a licensed accountant or attorney. The goal here is to help you ask the right questions.`,
          `## Choose how your business is structured`,
          `You can start as a sole proprietor, which is simple and uses your Social Security number, or form a limited liability company, an LLC, which separates your business from your personal assets and is the choice many sellers make once real money is involved. Amazon accepts both. If you form an LLC, register it in your state and keep it in good standing.`,
          `## Get an EIN`,
          `An Employer Identification Number is a free tax ID from the IRS. Even sole proprietors can get one, and using it instead of your Social Security number in business paperwork is a sensible privacy step. Apply only through the official IRS site, because paid third party sites charge for something that is free.`,
          `## Open a separate business bank account`,
          `Keep every business dollar in one account. This makes taxes easier, protects your LLC status, and gives Amazon one clean place to deposit your earnings. Amazon will ask for bank details during registration.`,
          `## Resale certificate and sales tax basics`,
          `If you buy inventory from wholesalers, they may ask for a resale certificate so you do not pay sales tax on goods you will resell. Amazon collects and remits sales tax for you in most states under marketplace facilitator laws, but you may still have your own obligations in some situations. Module 12 covers this in more detail.`,
          `## Insurance`,
          `Amazon requires many sellers to carry commercial general liability insurance once their sales reach certain monthly levels, and it can require proof. Even before that requirement, product liability coverage protects you if a product you sold causes harm. Ask an insurance agent who works with online sellers, and check Seller Central for the current requirement.`,
          `## Keep records from day one`,
          `Save every supplier invoice, receipt, and bank statement. You will need them for taxes, for Amazon category approvals, and for proving where your inventory came from if Amazon asks.`,
        ],
        links: [
          { label: 'IRS: Apply for an EIN (free)', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online' },
        ],
      },
      {
        id: 'budget',
        title: 'Startup Budget and Realistic Expectations',
        minutes: 12,
        body: [
          `Most people who quit Amazon quit because they ran out of money before they learned the system. A realistic budget protects you from that.`,
          `## Typical startup ranges`,
          `* Dropshipping or merchant fulfilled testing: roughly $500 to $1,500 to start.`,
          `* Wholesale buying from brands or distributors: often $5,000 to $25,000 or more, because you buy inventory up front.`,
          `* Private label, where you create your own branded product: often $3,000 to $10,000 or more, covering samples, production, branding, shipping, and launch advertising.`,
          `These are common ranges, not promises. Your number depends on the category and product cost.`,
          `## Costs people forget`,
          `* The Professional selling plan, $39.99 per month.`,
          `* Supplier or dropshipping platform subscriptions.`,
          `* Amazon fees on every sale, which can be 8 to 15 percent in most categories for referral fees alone, plus fulfillment and storage if you use FBA.`,
          `* Advertising, because new listings usually need paid traffic to get started.`,
          `* Returns, damaged units, and unsold inventory.`,
          `* Taxes, which are due on profit, not on cash in your account.`,
          `## Cash flow and timing`,
          `Amazon pays out on a regular schedule, and funds from new sellers can be held for a period. Plan for money to be tied up in inventory and in transit. A common beginner mistake is spending the entire budget on the first order of inventory.`,
          `## Set honest expectations`,
          `Amazon selling is a real business, not a shortcut. Many sellers see slow first months while they learn, gather reviews, and tune their ads. This course gives you the knowledge, but results depend on your product choices, your execution, your budget, and the market. No one can guarantee income, and you should be wary of anyone who does. Set a testing budget you can afford to lose, treat early sales as learning, and measure everything.`,
        ],
      },
    ],
  },
  {
    id: 'account-setup',
    title: 'Module 3: Setting Up Your Seller Account',
    lessons: [
      {
        id: 'plans',
        title: 'Choosing Your Selling Plan and Preparing Your Documents',
        minutes: 11,
        body: [
          `Amazon offers two plans. Choosing correctly saves money and avoids a limitation you would have to fix later.`,
          `## Individual plan`,
          `No monthly fee, but Amazon charges $0.99 for every item you sell, on top of the usual selling fees. It is designed for people selling very small quantities. It has limited tools and does not give you access to advertising, and Individual sellers are not eligible to win the Featured Offer.`,
          `## Professional plan`,
          `$39.99 per month with no per item fee. It unlocks bulk listing tools, reports, advertising, Brand Registry eligibility, and the ability to win the Featured Offer. If you plan to sell more than about 40 items a month, or you want to grow at all, Professional is the better value. You can switch from Individual to Professional later.`,
          `## What to prepare before you start`,
          `Gather these first so registration takes minutes instead of days.`,
          `* A government issued photo ID, such as a passport or driver license, that matches your legal name.`,
          `* Your business bank account details, where Amazon will deposit your earnings.`,
          `* A credit card that can be charged internationally, for your subscription and any account charges.`,
          `* Your Social Security number or EIN, and your tax information.`,
          `* A phone number you can answer for two step verification, and an email address you control.`,
          `* Proof of address, such as a recent utility bill or bank statement, in case Amazon requests it.`,
          `## Keep details consistent`,
          `The name on your ID, your bank account, your card, and your tax record should match what you enter. Inconsistencies are the number one reason verification stalls. Use your own legal information only, and never open an account using someone else's identity.`,
        ],
        links: [
          { label: 'Amazon seller registration', url: 'https://sell.amazon.com' },
        ],
      },
      {
        id: 'registration',
        title: 'Step by Step Registration and Your First Look at Seller Central',
        minutes: 15,
        body: [
          `Registration usually takes 15 to 30 minutes of typing. Verification afterward can take 24 hours to several days, and Amazon may ask for extra documents. Follow these steps in order.`,
          `## Registration steps`,
          `* Go to the official Amazon seller site and choose to sign up. Create an account with a business email you control.`,
          `* Enter your business type and legal business information exactly as it appears on your documents.`,
          `* Add your primary contact and your phone number, and complete the two step verification.`,
          `* Enter the bank account where earnings will be deposited and the credit card for fees.`,
          `* Enter your tax information.`,
          `* Complete identity verification by uploading your ID, and often by joining a short live video call with an Amazon verifier. Have your ID in hand and sit in a quiet, well lit room.`,
          `* Choose your store name. It can be your business name, and it appears on your seller profile.`,
          `* Review and submit, then wait for Amazon to confirm your account is open.`,
          `## If verification is slow or fails`,
          `Check your email, including spam, for requests from Amazon. Reply with clear, readable documents that match your registration details. Do not create a second account to get around a problem, because duplicate accounts can be banned.`,
          `## Your first tour of Seller Central`,
          `Once approved, spend an hour exploring before you list anything.`,
          `* Inventory: where you create listings and track stock.`,
          `* Orders: where you manage and confirm shipments.`,
          `* Advertising: where campaigns are built.`,
          `* Reports and Payments: where you track sales, fees, and deposits.`,
          `* Performance and Account Health: where Amazon scores you. Learn this early, because it decides whether your account survives.`,
          `* Settings: where you set shipping options, returns, and notifications.`,
          `## Turn on the safety basics`,
          `Enable two step verification, set up a dedicated email for Amazon, set your return address, and review your notification settings so you never miss a policy message.`,
        ],
      },
    ],
  },
  {
    id: 'sourcing-models',
    title: 'Module 4: Sourcing Models',
    lessons: [
      {
        id: 'compare-models',
        title: 'Dropshipping, Wholesale, Arbitrage, and Private Label Compared',
        minutes: 16,
        body: [
          `Your sourcing model is how you get products to sell. Each model has different cost, risk, speed, and profit potential. Understanding all four helps you pick a starting point and plan where to go next.`,
          `## Dropshipping`,
          `A supplier holds the inventory and ships orders directly to your customers. You carry almost no inventory cost, so startup can be roughly $500 to $1,500 and you can launch within weeks. The tradeoffs are thin margins, often 15 to 30 percent before advertising, little control over shipping speed and quality, and strict Amazon rules, which Module 6 covers in full.`,
          `## Wholesale`,
          `You buy goods in bulk from brands or authorized distributors and resell them. Because you buy genuine, branded product, quality is predictable. Upfront cost is higher. Many brands also restrict who can sell them, so you may need approvals, and you often compete with other sellers on the same listing for the Featured Offer.`,
          `## Online and retail arbitrage`,
          `You buy discounted products from stores and resell them on Amazon at a higher price. It can work with a small budget, but it needs constant sourcing work, risks brand and category restrictions, and depends on promotions that disappear.`,
          `## Private label`,
          `You have a manufacturer make a product that you brand as your own. You own the listing, so you avoid price wars with other sellers on the same page, and margins can reach 30 to 50 percent or more. It takes the longest, about 90 days to launch, costs the most, roughly $3,000 to $10,000 or more, and means you carry inventory and product risk.`,
          `## A practical path`,
          `Many new sellers test demand with merchant fulfilled or dropshipped products, learn how listings, ads, and customer service work with little risk, and then move proven products into wholesale or private label. Choose the model that matches your budget and your appetite for risk, and be willing to change models as you learn.`,
        ],
      },
      {
        id: 'finding-suppliers',
        title: 'Finding and Vetting Legitimate Suppliers',
        minutes: 13,
        body: [
          `Your supplier is a business partner whose mistakes become your problems. A late or damaged shipment hurts your metrics, not theirs. Vet suppliers carefully.`,
          `## Where legitimate suppliers come from`,
          `* Manufacturers and brands that sell wholesale through their own websites.`,
          `* Authorized distributors that carry multiple brands.`,
          `* Established dropshipping platforms that screen suppliers, covered in Module 6.`,
          `* Trade shows and industry directories for larger buyers.`,
          `## Vetting checklist`,
          `* Ask for a business license or registration and verify the company exists.`,
          `* Confirm they are the manufacturer or an authorized distributor, not another reseller.`,
          `* Order samples yourself and inspect quality, packaging, and delivery time.`,
          `* Ask about return and damage policies, minimum orders, and who pays for defects.`,
          `* Confirm they can ship with your business name and without their own branding when needed.`,
          `* Check stock reliability, because running out of stock after you take an order is a cancellation against you.`,
          `* Start with a small test order before committing.`,
          `## Keep proof of purchase`,
          `Amazon can ask for invoices showing you sourced genuine, authorized product. Always receive and save an invoice with the supplier name, address, product, quantity, and date. Invoices must be from a real supplier and must not be altered.`,
          `## Red flags`,
          `Be cautious of suppliers who refuse invoices, price far below market with no explanation, ask for payment by gift card or unusual methods, or promise guaranteed profits. If a deal sounds too good to be true on genuine branded goods, it is often counterfeit or gray market inventory, and selling counterfeit goods can end your account.`,
        ],
      },
    ],
  },
];
