import type { Module } from './types';

// Cottage Bakery Masterclass, part A: modules 1 to 4.
// Rules and figures reflect what was published as of October 2026.
// Cottage food law changes often, so lessons keep sending learners back to
// their own state agency and local health department for the final word.

export const COTTAGE_MODULES_A: Module[] = [
  {
    id: 'welcome',
    title: 'Module 1: Welcome to Cottage Baking',
    lessons: [
      {
        id: 'what-is-cottage-bakery',
        title: 'What a Cottage Bakery Really Is',
        minutes: 12,
        body: [
          `A cottage bakery is a small food business that makes baked goods in a home kitchen and sells them directly to customers. It is built on cottage food laws, which are state rules that let people sell certain low risk foods from home without a commercial kitchen. Every state now has some version of these laws, and in many states you can start with very little paperwork and very little money.`,
          `The reason this is possible is simple. Regulators treat foods that stay safe at room temperature, like bread, cookies, and most cakes, as low risk. Foods that need a refrigerator to stay safe, like cheesecake, cream pies, and anything with meat or dairy as the main ingredient, are treated as higher risk and usually need a licensed kitchen.`,
          `## What you are actually building`,
          `* A real business with real customers, real taxes, and real responsibility for food safety.`,
          `* A product people trust enough to eat and to give to their families and friends.`,
          `* A brand. People rarely buy a cookie. They buy the baker they know.`,
          `## What cottage baking is not`,
          `It is not a loophole. It is a legal category with rules, and the rules differ by state, by county, and sometimes by city. Selling without understanding them can get a baker shut down, fined, or sued. This course teaches you to do it correctly from day one so you can build something that lasts.`,
          `## Why this model is growing`,
          `Many states have raised sales caps, removed permits, and allowed online ordering in the last few years. Several now allow some refrigerated foods under extra conditions. That means the opportunity is real and getting wider, but it also means rules are moving. A habit you will build in this course is checking your state agency regularly, not relying on what a friend heard two years ago.`,
          `## How this masterclass is organized`,
          `You will start with the legal ground rules and your own state's details, then set up your business, then learn food safety from the first ingredient to the final delivery, then build your menu, packaging, labels, pricing, and sales channels. The final module gives you a 90 day launch plan and checklists you can use every week.`,
        ],
      },
      {
        id: 'is-this-for-you',
        title: 'Is This Business Right for You? An Honest Look',
        minutes: 12,
        body: [
          `Baking from home can be rewarding, but it helps to go in with open eyes. Successful cottage bakers usually treat it as a business from the start, and they are honest about the time and the work.`,
          `## The real work`,
          `Baking itself is often the smaller part of the week. You also shop for ingredients, clean and sanitize, package, label, photograph, answer messages, deliver or hand off orders, and keep records. A good rule of thumb is that every hour in the oven comes with at least an hour of other work.`,
          `## What the money can look like`,
          `Your sales cap and your selling channels set your ceiling. Some states cap yearly sales as low as $30,000 and a few allow $250,000. Many have no cap on baked goods. Whatever your state allows, remember that sales are not income. Ingredients, packaging, labels, fees, insurance, and your time all come out first. Later in this course you will learn to price so that you are paid for your time and not just your ingredients.`,
          `## Questions to ask yourself`,
          `* Can I bake consistently, with the same quality every time, and in larger batches than a family recipe?`,
          `* Do I have the space to keep my business food separate from my household food and supplies?`,
          `* Am I comfortable following written procedures and keeping records?`,
          `* Can I handle customer messages, deadlines, and the occasional complaint calmly?`,
          `* Does my household, my lease, and my homeowner association allow a food business at my address?`,
          `## Start small on purpose`,
          `You do not need a large launch. Many strong bakeries begin with two or three products, a small weekly order window, and a handful of regular customers. Starting small lets you learn the rules, perfect the recipes, and build good habits before volume makes mistakes expensive.`,
          `## A word on mindset`,
          `The bakers who last are the ones who respect the food safety side as much as the creative side. A beautiful cake that makes someone sick ends a business overnight. A plain loaf made carefully, labeled correctly, and delivered on time builds one.`,
        ],
      },
    ],
  },
  {
    id: 'know-your-rules',
    title: 'Module 2: Know Your Rules',
    lessons: [
      {
        id: 'three-layers',
        title: 'The Three Layers of Rules',
        minutes: 12,
        body: [
          `Cottage baking is governed by three layers of rules, and you have to satisfy all of them. Many beginners only find out about the second or third layer after they have already started selling.`,
          `## Layer 1: Federal rules`,
          `The federal government sets food labeling and allergen requirements that apply everywhere, and it has authority over food crossing state lines. Most cottage food laws are written around staying inside your state, which is why many states limit or ban shipping. If you ever sell to a buyer in another state, federal law and that buyer's state law can both apply.`,
          `## Layer 2: State rules`,
          `This is where most of the action is. Your state decides which foods qualify, how much you can sell in a year, whether you need a registration, permit, license, or training, what your label must say, and where and how you can sell, including online and shipping. This layer differs more from state to state than anything else, which is why this course includes a state rules finder in the next lesson.`,
          `## Layer 3: Local rules`,
          `Your city, county, and neighborhood can add rules that your state does not mention. Common examples include zoning and home occupation permits, a city business license, county health department registration, restrictions in a homeowner association, and the terms of your lease if you rent. In some states the law prevents local governments from adding rules, and in others it does not. Never assume.`,
          `## The mistake to avoid`,
          `The classic mistake is reading a blog post about your state, seeing that no permit is required, and assuming you are done. That can be true at the state level and still leave a city business license, a zoning question, or a sales tax certificate unsolved.`,
          `## Your standing rule`,
          `Treat every rule you read online, including in this course, as a starting point. Confirm it with the official agency, get the answer in writing when you can, and write down the date. That habit protects you when rules change.`,
        ],
        links: [
          { label: 'National Agricultural Law Center cottage food compilation', url: 'https://nationalaglawcenter.org/state-compilations/cottagefood/' },
          { label: 'Institute for Justice cottage food and food freedom reforms', url: 'https://ij.org/legislative-advocacy/state-reforms-for-cottage-food-and-food-freedom-laws/' },
        ],
      },
      {
        id: 'state-rules',
        title: 'Your State Rules Finder',
        minutes: 15,
        body: [
          `Use the finder below to see the headline rules for your state. It covers three things every baker needs to know before the first sale: your yearly sales cap, whether you need a license, permit, registration, or training, and what the state says about online orders and shipping.`,
          `The finder covers the 50 states. If you live in Washington, D.C. or a U.S. territory, go straight to the local health department and ask for its cottage food or home food business rules.`,
          `## How to read the results`,
          `* Sales cap: usually your gross sales, meaning the money customers pay you before costs, not your profit. Plan to track it from your very first sale.`,
          `* No cap: the state's own source says there is no limit. Some states show Not listed, which usually means there is no cap on the state page, but you should ask the agency before you count on it.`,
          `* Permit or registration: some states ask for nothing, some ask for a course or a food handler card, and some require a registration, a permit, or even an inspection of your kitchen.`,
          `* Online orders: allowed does not always mean shipping is allowed. Many states want the food handed over in person inside the state.`,
          `## Changes coming soon`,
          `Several states have scheduled changes. For example, some caps rise soon, and some states are opening online sales or in state shipping in 2027. When a change is coming, the finder shows it in a highlighted box. Mark the date on your calendar.`,
          `## What the finder does not cover`,
          `The finder gives you the headline rules. It does not replace the full list of allowed foods, the exact label wording your state requires, your county health department, your city's zoning, or your sales tax obligations. The next lessons walk you through those. Use the agency link under your state as your starting point for the official wording.`,
          `## Food freedom states`,
          `A small group of states, including Wyoming, North Dakota, Montana, Tennessee, Oklahoma, and Idaho, have gone beyond traditional cottage food laws and allow a much wider range of homemade foods sold directly to informed customers. Even there, the rules about where and how you can sell still matter, so read your state's details carefully.`,
        ],
        links: [
          { label: 'Forrager cottage food law map', url: 'https://forrager.com/laws/' },
          { label: 'National Agricultural Law Center state compilation', url: 'https://nationalaglawcenter.org/state-compilations/cottagefood/' },
        ],
      },
      {
        id: 'local-rules',
        title: 'Local Rules: Zoning, HOA, Lease, and County',
        minutes: 14,
        body: [
          `State law may say yes while your local situation says no. Checking local rules is a one hour project that can save you from a forced shutdown, so do it before you spend money on supplies.`,
          `## Who to contact`,
          `* County or city health department: ask whether they require registration, inspection, or a label review for home bakers in your area.`,
          `* City or county zoning office: ask whether a home based food business is allowed at your address and whether you need a home occupation permit.`,
          `* City or county business license office: ask whether you need a general business license even if the state needs no food permit.`,
          `* State department of revenue: ask about sales tax registration for the foods you sell.`,
          `* Your homeowner association, if you have one: read the covenants and ask whether business activity is restricted, including customer visits and signs.`,
          `* Your landlord, if you rent: read the lease and get written permission for food production and customer pickups.`,
          `## Questions worth asking`,
          `* Is a food business allowed in a home in my zoning district?`,
          `* Can customers come to my home for pickup, and are there parking or traffic limits?`,
          `* Do I need a business license or a home occupation permit, and what does it cost?`,
          `* Does the health department want to see my labels or my food safety certificate?`,
          `* Does the county impose any rule beyond the state law?`,
          `## A short phone script`,
          `"Hello, I am a home baker planning to sell baked goods under my state's cottage food law. I live at [address]. Can you tell me whether my address allows a home food business, whether I need a business license or a home occupation permit, and whether the county or city adds any rules beyond the state law? Could you also email me the answer so I can keep it with my records?"`,
          `Stay friendly and specific. Ask for the name of the person you spoke to and the date, and write both in your log.`,
          `## Write it all down`,
          `Keep a simple log with the date, the office, the person you spoke to, and what they told you. If the answer was by email, save it. If it was by phone, send a short confirming email afterward.`,
          `## If the answer is no`,
          `Do not give up and do not ignore it. Ask what is allowed. Some places allow pickup at a neutral location instead of your home. Some allow farmers market sales. And a shared commercial kitchen can be a fully legal alternative that removes most home based restrictions.`,
        ],
      },
      {
        id: 'written-answers',
        title: 'Getting Answers in Writing and Reading the Law Yourself',
        minutes: 10,
        body: [
          `When you are unsure about a rule, the best move is to ask the agency and keep the reply. Agencies are used to these questions, and a written answer protects you if someone later challenges your product.`,
          `## How to write a good question`,
          `Be specific and keep it short. Name the product, your state, and exactly what you want to know. For example, say that you plan to sell vanilla buttercream cupcakes made in a home kitchen and ask whether that product qualifies and what the label must include.`,
          `## A simple template`,
          `Say who you are, that you are planning a cottage food business in your county, list your three or four products, and ask whether those products qualify, whether you need any registration or training, and what your label must include. Ask for a reply in writing and thank them for their time.`,
          `## Reading the statute`,
          `Your state's cottage food law is usually short and written in plain language. Read it once. Look for definitions, the list of allowed or banned foods, the label requirements, the sales limit, and where sales are allowed. Use the National Agricultural Law Center compilation to find your state's statute quickly.`,
          `## Keep your proof`,
          `Create a folder, digital or paper, called Compliance. Put in it your emails with agencies, your registration or certificate, your food handler card, your insurance, your label approvals, and your recipes with test dates. If you are ever asked how you know you are allowed to sell something, the folder is your answer.`,
          `## Check again every January`,
          `Laws change, and many changes take effect on January 1 or on another fixed date. Put a yearly reminder on your calendar to recheck your state page, your local requirements, and your sales cap.`,
        ],
        links: [
          { label: 'National Agricultural Law Center state compilation', url: 'https://nationalaglawcenter.org/state-compilations/cottagefood/' },
        ],
      },
      {
        id: 'foods-that-qualify',
        title: 'Which Foods Qualify and Why',
        minutes: 15,
        body: [
          `Cottage food laws are built around one idea: foods that stay safe at room temperature are low risk. Understanding the reasons will help you judge a new recipe even when your state's list does not name it.`,
          `## Two numbers that matter`,
          `* Acidity, measured as pH. Foods at a pH of 4.6 or below are acidic enough that most harmful bacteria cannot grow. That is why jams and properly made pickles can qualify.`,
          `* Water activity, a measure of how much moisture is available for bacteria. Foods at 0.85 or below do not have enough for most bacteria to grow, which is why most breads, cookies, and dry baked goods qualify.`,
          `A food with a low pH, a low water activity, or both can sit on a shelf safely. Foods that fail both tests need time and temperature control, and food safety professionals call them TCS foods. Traditional cottage food laws exclude them.`,
          `## Usually allowed`,
          `* Bread, rolls, and sourdough.`,
          `* Cookies, brownies, and bars.`,
          `* Cakes and cupcakes without cream, custard, or cream cheese frosting.`,
          `* Muffins, scones, and quick breads.`,
          `* Fruit pies with fruit fillings.`,
          `* Biscotti, shortbread, and other dry baked goods.`,
          `## Usually not allowed under a traditional cottage food law`,
          `* Cheesecake, custard, cream pies, and cakes with cream cheese or whipped cream fillings.`,
          `* Anything with meat or seafood.`,
          `* Fresh cut fruit and anything that must be kept cold to stay safe.`,
          `* Low acid canned foods.`,
          `## The buttercream gray area`,
          `Buttercream made with butter, powdered sugar, and flavoring is allowed in many states because it is shelf stable. It is not allowed everywhere. Some states ban buttercream that contains dairy or eggs, and some do not allow butter based buttercream at all. Ask your state agency before you build a menu around frosting.`,
          `## Some states are expanding`,
          `A growing number of states allow certain refrigerated foods from home, but usually with training, registration, or in person delivery. If you want to sell cheesecake or cream pies, check whether your state has a path, and read every requirement.`,
          `## The safe test for a new recipe`,
          `Ask whether the finished product needs refrigeration to stay safe. If yes, treat it as off limits until your state agency tells you in writing that it qualifies.`,
        ],
        links: [
          { label: 'FDA Food Code', url: 'https://www.fda.gov/food/retail-food-protection/fda-food-code' },
        ],
      },
      {
        id: 'outgrowing',
        title: 'When You Outgrow Cottage Food',
        minutes: 12,
        body: [
          `If your bakery works, you may eventually hit a ceiling. Planning for that ceiling now makes growth smooth instead of stressful.`,
          `## The common ceilings`,
          `* Your yearly sales cap, if your state has one.`,
          `* A product you want to sell that is not allowed, such as a refrigerated dessert.`,
          `* A sales channel you want to use, such as wholesale to stores or shipping across state lines.`,
          `## Your options when you hit a ceiling`,
          `* Change the recipe. A small change, such as swapping a cream filling for a fruit filling, can move a product into the allowed category.`,
          `* Move to a higher tier license where your state offers one. Some states have a middle level between cottage food and a full commercial license, such as a home bakery or homestead license.`,
          `* Rent a shared commercial kitchen. Many rent by the hour, which is far cheaper than building your own space, and they remove most home based limits.`,
          `* Use a commercial kitchen license for the products that need it while keeping simple items under your cottage food registration.`,
          `* Wait for the law to change. Laws keep expanding, and a food that is not allowed today may be added later.`,
          `## Home restaurant style programs`,
          `A few places, notably California, have home kitchen operation programs that allow permitted home cooks to sell full meals. These are separate from traditional cottage food laws and have their own permits, so research them separately if they interest you.`,
          `## Track your cap from day one`,
          `Divide your yearly cap by 12 to see your monthly pace. If your cap is $50,000, that is about $4,167 a month on average. Many bakers earn more in November and December, so a strong holiday season can use up a large share of the year quickly. Check your total on the first of every month.`,
          `## Plan before you hit the limit`,
          `Start researching shared kitchens and your state's next license tier when you reach about 60 percent of your cap. If you pass your cap without a plan, you may have to stop selling for the rest of the year.`,
        ],
      },
    ],
  },
  {
    id: 'business-foundations',
    title: 'Module 3: Business Foundations',
    lessons: [
      {
        id: 'structure',
        title: 'Business Name, Structure, and EIN',
        minutes: 12,
        body: [
          `Setting up your business correctly is simple, inexpensive, and protects you. You can do most of it in a weekend.`,
          `## Pick a name`,
          `Choose a name that is easy to say, easy to spell, and not already used by another bakery in your area. Search your state's business name records, search social media for the handle, and search the federal trademark database to avoid conflicts. If the .com domain and the handle are available, grab them right away.`,
          `## Choose a structure`,
          `* Sole proprietorship: the default. You and the business are the same legal person. It is the simplest and the cheapest, but your personal assets are not separated from the business.`,
          `* Limited liability company, or LLC: a separate legal entity that can protect your personal assets from many business debts and claims. It costs a state filing fee and sometimes a yearly fee. It does not replace insurance.`,
          `Many new bakers start as sole proprietors, buy liability insurance, and form an LLC once sales grow. Talk to an accountant or an attorney in your state to decide what fits you.`,
          `## Get an EIN`,
          `An Employer Identification Number is a free number from the IRS. Even if you have no employees, it lets you open a business bank account and keep your Social Security number off documents. Apply only through the official IRS site. You never have to pay a fee for an EIN, and sites that charge for it are not the IRS.`,
          `## Register your name`,
          `If you operate under a name that is not your own legal name, many states and counties require a registration often called a DBA or assumed name. Ask your county clerk or your state business office.`,
          `## Keep your personal and business lives separate`,
          `Separate bank accounts, separate records, and separate receipts protect you in taxes and in any legal question. Do this from the first day.`,
        ],
        links: [
          { label: 'IRS: Get an EIN for free', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/get-an-employer-identification-number' },
          { label: 'USPTO trademark search and information', url: 'https://www.uspto.gov/trademarks' },
          { label: 'U.S. Small Business Administration', url: 'https://www.sba.gov' },
        ],
      },
      {
        id: 'money-taxes',
        title: 'Money, Sales Tax, and Income Taxes',
        minutes: 15,
        body: [
          `Cottage food income is real income and it is taxable. Setting up simple money habits early is the difference between a calm tax season and a painful one.`,
          `## Open a business bank account`,
          `Use it for every sale and every business expense. Even a basic checking account works. This gives you a clean record and protects you if you are ever asked to prove your numbers.`,
          `## Track every sale and every expense`,
          `Use a simple spreadsheet or a bookkeeping app. Record the date, the customer or channel, the amount, and the payment type. For expenses, save receipts for ingredients, packaging, labels, equipment, fees, insurance, mileage, and supplies. Your sales total also tells you how close you are to your state cap.`,
          `## Sales tax`,
          `Whether baked goods are taxable depends on your state and sometimes your city. Some states require you to register for a sales tax permit or certificate even when no food permit is needed, and a few require one as part of the cottage food rules. Contact your state department of revenue and ask what applies to your products and your channels.`,
          `## Income taxes in plain language`,
          `* In the United States, a sole proprietor reports business income and expenses on Schedule C with a personal tax return.`,
          `* Net profit is generally also subject to self employment tax, which covers Social Security and Medicare.`,
          `* If you expect to owe a meaningful amount, the IRS expects estimated tax payments during the year rather than one payment at tax time.`,
          `* Payment apps and marketplaces may send you or the IRS income reports. Keep your own complete records no matter what any app reports.`,
          `## Pay yourself on purpose`,
          `Set aside a percentage of every sale for taxes in a separate savings account, so the money is there when payments are due. An accountant can help you pick the percentage for your situation.`,
          `## A caution`,
          `This course gives general education, not tax advice. A local accountant who works with small food businesses is worth the cost, especially in your first year.`,
        ],
        links: [
          { label: 'IRS: Schedule C (Profit or Loss From Business)', url: 'https://www.irs.gov/forms-pubs/about-schedule-c-form-1040' },
          { label: 'IRS: Estimated taxes', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes' },
        ],
      },
      {
        id: 'insurance',
        title: 'Insurance and Liability',
        minutes: 12,
        body: [
          `Insurance is not required in every state, but it is one of the smartest purchases a new baker can make. Food businesses carry real risk, and one claim can end a small business.`,
          `## Why your homeowner or renter policy probably is not enough`,
          `Standard homeowner and renter policies often limit or exclude business activity and product claims. Do not assume you are covered. Call your agent, describe your business, and ask in plain words whether a customer's illness or allergic reaction from your food would be covered. Get the answer in writing.`,
          `## The kinds of coverage to know`,
          `* General liability: covers injuries and property damage related to your business, such as a customer who is hurt at your market booth.`,
          `* Product liability: covers claims that your food made someone sick or caused an allergic reaction. This is the most important one for bakers.`,
          `* Property coverage: covers your equipment and inventory.`,
          `* Event or market coverage: many markets and festivals require vendors to carry liability insurance and name the market as an additional insured.`,
          `## Where bakers often find coverage`,
          `Some insurance programs are built for home food businesses and offer affordable policies. Compare quotes from several providers and read what is excluded.`,
          `## Reduce your risk beyond insurance`,
          `* Follow the food safety practices in Module 4 every time.`,
          `* Label every product with ingredients and allergens exactly as required.`,
          `* Keep batch records so you can trace a problem.`,
          `* Use clear written policies for orders, allergies, and refunds, which you will build in the next lesson.`,
        ],
        links: [
          { label: 'FLIP: Food Liability Insurance Program', url: 'https://www.fliprogram.com' },
          { label: 'Next Insurance', url: 'https://www.nextinsurance.com' },
          { label: 'Thimble', url: 'https://www.thimble.com' },
        ],
      },
      {
        id: 'policies',
        title: 'Policies Customers Can Count On',
        minutes: 10,
        body: [
          `Clear written policies prevent most disputes. They make you look professional and they give you something to point to when a customer is unhappy.`,
          `## Policies to write before you sell`,
          `* Ordering: how customers order, your order window, your cutoff time, and your minimum order.`,
          `* Deposits and payment: whether you take deposits for custom orders, how much, and when the balance is due.`,
          `* Cancellations and changes: how many days notice you need and what happens to deposits.`,
          `* Refunds: because food cannot be returned, decide how you handle a product that arrives damaged or a mistake on your part.`,
          `* Pickup and delivery: where, when, and what happens if a customer is late or misses a pickup.`,
          `## Allergy statement`,
          `Say plainly that your products are made in a home kitchen where common allergens are present, that cross contact is possible, and that customers with severe allergies should read the label and decide for themselves. This does not replace accurate labeling. It supports it.`,
          `## Keep the tone friendly`,
          `Policies can be warm and short. A customer who feels respected is more likely to follow them. Put the key points on your order page, your menu, and in your confirmation messages.`,
          `## Make them easy to find`,
          `A short page or pinned post that holds your policies saves you from retyping answers a hundred times. Link it wherever you take orders.`,
        ],
      },
    ],
  },
  {
    id: 'food-safety',
    title: 'Module 4: Food Safety from Start to Finish',
    lessons: [
      {
        id: 'fs-foundation',
        title: 'Why Food Safety Comes First',
        minutes: 12,
        body: [
          `Food safety is not paperwork. It is how you keep customers safe and how you keep your business alive. Even in a state where no inspector will ever visit your kitchen, you are still responsible for what you sell.`,
          `## The three kinds of hazards`,
          `* Biological: harmful bacteria, viruses, and molds. These cause most foodborne illness.`,
          `* Chemical: cleaning products, pesticides, and unlabeled allergens.`,
          `* Physical: anything that should not be in food, such as glass, metal, hair, or a bandage.`,
          `## Where the risk hides in baking`,
          `Baked goods are lower risk than many foods, but they are not risk free. Raw flour and raw eggs can carry harmful bacteria, which is why cooking and cleaning steps matter. Fillings, frostings, and toppings can add risk. Hands, surfaces, and tools can move germs from raw ingredients to finished products. Allergens can move too.`,
          `## The idea behind everything in this module`,
          `Follow the food from the first ingredient to the final delivery and ask at every step what could go wrong and what stops it. That habit is the heart of professional food safety.`,
          `## The journey`,
          `* The people: your health and your hands.`,
          `* The kitchen: clean, sanitized, and pest free.`,
          `* The ingredients: bought, stored, and used safely.`,
          `* The temperatures: safe holding, cooking, and cooling.`,
          `* The allergens: controlled and labeled.`,
          `* The production day: a repeatable routine.`,
          `* The transport and sale: safe from your kitchen to the customer.`,
          `* The records: proof of what you did and a plan if something goes wrong.`,
          `## Get trained even if no one requires it`,
          `Many states require a food handler card or a food safety course. Even if yours does not, take one. A basic course takes a few hours, costs little, and gives you a professional foundation and proof of training that markets and insurers like to see.`,
        ],
        links: [
          { label: 'ServSafe food handler training', url: 'https://www.servsafe.com' },
          { label: 'StateFoodSafety food handler training', url: 'https://www.statefoodsafety.com' },
          { label: 'CDC food safety', url: 'https://www.cdc.gov/food-safety/index.html' },
        ],
      },
      {
        id: 'fs-people',
        title: 'People: Health, Hands, and Habits',
        minutes: 12,
        body: [
          `Most contamination in small kitchens starts with the people. These habits cost nothing and prevent a great deal of trouble.`,
          `## Do not bake when you are sick`,
          `If you have vomiting, diarrhea, fever, a sore throat with fever, or jaundice, do not handle food for others. Wait at least 24 hours after symptoms end, or longer if your doctor or your health department advises. The same applies to anyone helping you. Open cuts or sores on hands must be covered with a waterproof bandage and a clean glove.`,
          `## Wash your hands the right way`,
          `* Use warm running water and soap.`,
          `* Scrub all surfaces of your hands, including between fingers and under nails, for at least 20 seconds.`,
          `* Rinse well and dry with a clean single use towel or a clean cloth that you change often.`,
          `## When to wash`,
          `* Before you start and every time you return to the kitchen.`,
          `* After using the restroom, handling trash, or touching your face, hair, phone, or pet.`,
          `* After handling raw eggs, raw flour, or any raw ingredient.`,
          `* After cleaning, taking out the trash, or touching money.`,
          `* Between tasks, especially between allergen foods and non allergen foods.`,
          `## Dress for the kitchen`,
          `Tie back or cover your hair, wear a clean apron, keep nails short and clean, remove rings and bracelets that can trap germs or fall into food, and avoid heavy perfume that can taint flavors. Use gloves for ready to eat foods if your state or market requires them, and remember gloves must be changed often. They do not replace handwashing.`,
          `## Keep non workers out`,
          `Children, visitors, and pets should stay out of the kitchen during production. Many states explicitly require that pets be kept out of the cooking area. Plan your baking schedule around family life so the kitchen is yours while you work.`,
          `## Phones and distractions`,
          `Phones carry germs. Keep yours out of the production area or wash your hands every time you touch it.`,
        ],
      },
      {
        id: 'fs-kitchen',
        title: 'The Kitchen: Cleaning, Sanitizing, and Pest Control',
        minutes: 14,
        body: [
          `A home kitchen can be a safe production space if you set it up and clean it with intention.`,
          `## Clean first, then sanitize`,
          `These are two different steps and both matter. Cleaning removes dirt and food residue with soap and water. Sanitizing reduces germs on a clean surface to a safe level. A sanitizer does not work well on a dirty surface, so always clean first.`,
          `## A simple routine for surfaces and tools`,
          `* Scrape and rinse off food residue.`,
          `* Wash with hot soapy water.`,
          `* Rinse with clean water.`,
          `* Sanitize with a food safe sanitizer, following the product label or your health department's instructions for strength and contact time. A common home guideline is a solution of unscented household bleach in water, but follow the label for the exact mix.`,
          `* Air dry. Do not wipe with a dirty towel.`,
          `## Surfaces and items that need special attention`,
          `* Countertops, cutting boards, mixing bowls, and baking sheets.`,
          `* Sinks and faucet handles.`,
          `* Refrigerator and freezer handles.`,
          `* Mixer attachments and scrapers.`,
          `* Dish towels and sponges. Sponges hold bacteria, so replace them often or use clean disposable towels for production.`,
          `## Dishwashing`,
          `If you have a dishwasher with a sanitizing cycle, it can handle many tools. If you wash by hand, use the three step method of wash, rinse, and sanitize, and let items air dry.`,
          `## Set your kitchen up for production`,
          `Clear counters of household items, personal items, and clutter. Use a dedicated area for finished and packaged goods. Keep business ingredients and supplies in clearly marked containers, separate from household food, and store chemicals away from food.`,
          `## Pest control`,
          `Store dry ingredients in sealed, labeled containers. Take out trash regularly, wipe crumbs promptly, and fix leaks. If you see signs of pests, stop production and deal with it before you resume.`,
          `## Water and waste`,
          `Use safe drinking water. If you use a private well, ask your health department whether testing is required or recommended. Keep a covered trash can and empty it often.`,
        ],
      },
      {
        id: 'fs-ingredients',
        title: 'Ingredients: Buying, Storing, and Using Safely',
        minutes: 14,
        body: [
          `Safe food starts with safe ingredients. Careful buying and storage protect your products and your budget.`,
          `## Buy from reliable sources`,
          `Purchase from licensed grocery stores, restaurant supply stores, and reputable distributors. Avoid unlabeled bulk items from unknown sources. Keep receipts for your records and for traceability if there is ever a recall.`,
          `## Check on arrival`,
          `* Inspect packaging for damage, leaks, swelling, or tampering.`,
          `* Check dates on eggs, dairy, and other perishables.`,
          `* Get refrigerated and frozen items home and into cold storage quickly. Use an insulated bag in warm weather.`,
          `## Storage rules`,
          `* Keep your refrigerator at 41 degrees Fahrenheit or colder and your freezer at 0 degrees Fahrenheit or colder, and check with an appliance thermometer.`,
          `* Store dry ingredients in sealed, labeled containers off the floor.`,
          `* Use first in, first out. Put newer items behind older ones and date everything you open or transfer.`,
          `* Store raw eggs below ready to eat foods and in their original cartons on a shelf, not in the door.`,
          `## Special notes for bakers`,
          `* Raw flour is a raw agricultural product and can carry harmful bacteria. Baking kills them, but raw dough and raw batter are not safe to taste. Keep raw flour away from finished goods and wash your hands after handling it.`,
          `* Raw eggs can carry bacteria. Cook fully, and use pasteurized eggs in any recipe that will not be fully cooked.`,
          `* Nuts and seeds are major allergens. Store them separately and label containers clearly.`,
          `* Check that spices, extracts, and colorings are food grade.`,
          `## Use clean tools and containers`,
          `Only use containers and tools that are made for food. Do not reuse containers that held chemicals, and do not use household items that are not food safe.`,
          `## Know when to throw it out`,
          `If you are not sure whether an ingredient is safe, throw it out. The cost of the ingredient is always lower than the cost of one sick customer.`,
        ],
        links: [
          { label: 'CDC food safety', url: 'https://www.cdc.gov/food-safety/index.html' },
        ],
      },
      {
        id: 'fs-temperatures',
        title: 'Temperatures: Cook, Cool, Hold, and Measure',
        minutes: 12,
        body: [
          `Temperature control is one of the most powerful food safety tools you have. Bacteria multiply fastest in what is called the danger zone.`,
          `## The danger zone`,
          `Food safety rules treat the range between 41 degrees Fahrenheit and 135 degrees Fahrenheit as the danger zone. Cold foods should be kept at 41 degrees or below, and hot foods at 135 degrees or above. Do not leave foods that need temperature control in the danger zone longer than your state's guidance allows, and do not leave them out for more than a short time.`,
          `## Why most baked goods are lower risk`,
          `Fully baked bread, cookies, and many cakes are low in moisture and stable at room temperature. That is why they qualify as cottage foods. When you add fillings, creams, custards, fresh fruit toppings, or dairy based frostings, you may add risk and may leave the cottage food category.`,
          `## Use a thermometer`,
          `A digital food thermometer is cheap and essential. Use it to check oven accuracy, bake doneness where relevant, and fridge and freezer temperatures. Calibrate it regularly by placing the probe in a glass of ice water, which should read 32 degrees Fahrenheit, and adjust if needed.`,
          `## Cooling`,
          `Food that you cook and then cool for later use, such as a cooked filling, should be cooled quickly. A common guideline is to cool from 135 degrees to 70 degrees within 2 hours, then to 41 degrees within 4 more hours. Use shallow pans, ice baths, and small portions to speed cooling. Check with your agency whether any cooked fillings are allowed in your category.`,
          `## Cooling baked goods before packaging`,
          `Always let baked goods cool fully before packaging. Warm product in a sealed bag creates condensation, which can encourage mold and spoil texture.`,
          `## Keep a temperature log`,
          `A simple log with the date, the item, and the temperature shows professionalism and helps you catch problems early. Record fridge and freezer temperatures daily if you use cold storage for ingredients.`,
        ],
      },
      {
        id: 'fs-allergens',
        title: 'Allergens and Cross Contact',
        minutes: 14,
        body: [
          `Allergens are one of the biggest safety and legal issues for bakers. A reaction can be life threatening, and an unlabeled allergen is one of the most common reasons for recalls.`,
          `## The major allergens`,
          `In the United States there are nine major food allergens: milk, eggs, fish, shellfish, tree nuts, peanuts, wheat, soybeans, and sesame. Sesame was added to the list in recent years. Baked goods commonly contain several of these, often hidden in ingredients like flavorings and mixes.`,
          `## What cross contact means`,
          `Cross contact happens when an allergen is accidentally transferred to a food that should not contain it, through shared tools, surfaces, hands, or equipment. Washing and sanitizing between products reduces it, but in a home kitchen it is hard to eliminate completely.`,
          `## How to manage it`,
          `* Read every ingredient label every time. Manufacturers change recipes.`,
          `* Plan your production order so that products without a given allergen are made before products with it, then clean thoroughly.`,
          `* Wash, rinse, and sanitize tools and surfaces between products.`,
          `* Store allergen ingredients in sealed containers and separate them from others.`,
          `* Use dedicated tools, such as separate scoops, for major allergens like nuts when possible.`,
          `* Never promise that a product is free of an allergen unless you can truly guarantee it. Use accurate wording on labels and policies.`,
          `## Labeling is not optional`,
          `Your label must list ingredients and identify major allergens in the way your state and federal rules require. You will build this in Module 7.`,
          `## Talking with customers`,
          `When a customer says they have an allergy, slow down. Share the exact ingredients, tell them honestly that your kitchen handles other allergens, and let them decide. Never guess. If you are unsure whether an ingredient contains an allergen, say so and check.`,
          `## If someone has a reaction`,
          `Know what to do. Encourage the person to follow their own emergency plan and call emergency services for severe symptoms. Keep the product, the label, and your batch record, and tell your insurer promptly.`,
        ],
        links: [
          { label: 'FDA: Food allergies', url: 'https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies' },
        ],
      },
      {
        id: 'fs-production',
        title: 'The Production Day Routine',
        minutes: 12,
        body: [
          `A repeatable routine turns safe habits into automatic ones. Here is a simple flow you can adapt.`,
          `## Before you start`,
          `* Check that you are healthy and your hands, hair, and clothing are ready.`,
          `* Clear the space of household items and keep family and pets out.`,
          `* Clean and sanitize counters, tools, and sinks.`,
          `* Review your order list, recipes, and allergen plan for the day.`,
          `## During production`,
          `* Wash your hands at the start and whenever you switch tasks.`,
          `* Weigh ingredients carefully for consistency.`,
          `* Bake in the planned order, with allergen free items before items with major allergens.`,
          `* Clean and sanitize tools between products.`,
          `* Keep raw ingredients and finished goods separate.`,
          `## After baking`,
          `* Cool products fully on clean racks.`,
          `* Package with clean hands in clean food grade packaging.`,
          `* Apply labels with the correct ingredients, allergens, and required statements.`,
          `* Store finished goods in a clean, dry area away from chemicals, pets, and household traffic.`,
          `## Clean down`,
          `Finish by cleaning, sanitizing, and putting everything away. Take out trash. Record the batch details in your log. A kitchen that is closed down properly is ready to go next time.`,
          `## Quality check`,
          `Look at each product before it goes out. Check appearance, weight, packaging, and label. Do not sell anything you would not be comfortable giving to a family member.`,
        ],
      },
      {
        id: 'fs-transport',
        title: 'Packaging, Transport, Delivery, and Market Day',
        minutes: 12,
        body: [
          `Many food safety problems start after the oven, in the car, on the delivery route, or on the market table. Protect the food all the way to the customer.`,
          `## Packaging for safety`,
          `* Use clean, food grade packaging made for direct food contact.`,
          `* Seal products so they are protected from dust, pests, and handling.`,
          `* Use tamper evident closures, such as stickers over a bag closure, where it makes sense.`,
          `* Put the label on every package before it leaves your kitchen.`,
          `## Transport`,
          `* Keep the vehicle clean and free of pets, chemicals, and strong odors.`,
          `* Pack products in clean, covered bins or boxes, and keep them off the floor of the vehicle.`,
          `* In hot weather, protect products from heat. Heat can melt frostings and speed spoilage.`,
          `* Keep products out of direct sunlight.`,
          `## Local delivery and pickup`,
          `Follow your state's rules on how you deliver. Some require in person handoff, some allow mail, and some allow neither. A porch drop, a locker, or a hand off at an agreed spot can all be fine where allowed, but think about heat, pests, theft, and allergies. Always confirm the order and the pickup details.`,
          `## Market day`,
          `* Bring a handwashing setup, sanitizer, and wipes.`,
          `* Cover products and keep them off the ground. Use clean tablecloths, display stands, and clean tongs or wax paper for handling.`,
          `* Keep a clean cash handling system, and avoid handling money and food with the same hands. Use a separate person, gloves, or a card reader.`,
          `* Check whether your market and your state restrict free samples, and follow the rules exactly.`,
          `* Keep your registration, insurance, and labels with you in case a market manager or inspector asks.`,
        ],
      },
      {
        id: 'fs-records',
        title: 'Records, Complaints, and What to Do If Something Goes Wrong',
        minutes: 12,
        body: [
          `Good records protect your customers and your business. They show that you take safety seriously, and they let you act fast if a problem appears.`,
          `## Keep a simple batch log`,
          `For each production day, record the date, the product, the quantity, key ingredient lot numbers or purchase dates for eggs, flour, nuts, and mixes, and who made it. If a customer reports a problem, the log helps you find the cause.`,
          `## Keep ingredient records`,
          `Save receipts and label photos for key ingredients. If a supplier announces a recall, you can check quickly whether you used the product.`,
          `## Handle complaints well`,
          `* Listen without arguing. Thank the customer for telling you.`,
          `* Collect details: what they ate, when, and what happened.`,
          `* Ask for the package and label if possible.`,
          `* Make a note of the batch, and review your records for the same batch.`,
          `* Respond respectfully and promptly. Offer a refund or replacement where appropriate.`,
          `## If someone says they became sick`,
          `Take it seriously. Express concern, stop selling the suspected product until you understand what happened, review your records, and contact your health department and insurer as required. Cooperate fully with any investigation. Do not blame the customer or hide information.`,
          `## Recalls`,
          `If you find a safety problem, such as an undeclared allergen or contamination, stop selling the product immediately, contact affected customers, remove products from sale, and notify your health department. Document what you did.`,
          `## Learn from problems`,
          `After any incident, write down what happened and what you will change. A bakery that learns from mistakes quickly earns long term trust.`,
        ],
      },
    ],
  },
];
