import type { Module } from './types';

// Cottage Bakery Masterclass, part D: modules 12 to 15.
// Business planning, orders and online presence, extra income, and the
// templates, scripts, and troubleshooting guides.

export const COTTAGE_MODULES_D: Module[] = [
  {
    id: 'planning',
    title: 'Module 11: Business Plan and Goals',
    lessons: [
      {
        id: 'business-plan',
        title: 'Your One Page Business Plan and Goals',
        minutes: 12,
        body: [
          `A business plan for a home bakery does not need to be long. One clear page that you actually use beats a thick document that sits in a drawer. Writing it forces you to make decisions before you spend money.`,
          `## The one page plan`,
          `* Who I serve: describe your ideal customer in a sentence, such as busy families within ten miles who want fresh bread each week.`,
          `* What I sell: your signature item, your core items, and your seasonal items.`,
          `* Where I sell: your first two channels, such as a weekly pickup and one market.`,
          `* How I am different: the flavor, the story, the quality, or the service that makes you worth choosing.`,
          `* What I charge: your price list and your target profit.`,
          `* How I stay legal: your state rules, your registration or training, your insurance, and your labels.`,
          `* How I get customers: your three main marketing actions each week.`,
          `## Set goals with numbers`,
          `Write goals for 30, 90, and 365 days. A useful goal has a number and a date. For example, by day 90 I will sell 150 items a week from two channels, and by month 12 I will earn a set monthly profit after paying myself. Use the calculators in this course to turn income goals into units, orders, and hours.`,
          `## Work backward`,
          `If you want a monthly profit of a certain amount and your average profit per item is known, divide to find how many items you must sell. Then divide by the number of selling days to see what each week requires. If the number needs more hours than you have, raise prices, add a higher value product, or lower the goal.`,
          `## Decide what success means to you`,
          `Some bakers want a little extra income and a flexible schedule. Others want to grow into a full time business or a storefront. Neither is wrong, but they require different plans. Decide early, and revisit it every quarter.`,
          `## Review monthly`,
          `Once a month, compare real results to your plan. What sold, what did not, what took too long, and what should change? Adjust the plan instead of abandoning it.`,
        ],
        links: [
          { label: 'SCORE free business plan templates and mentoring', url: 'https://www.score.org' },
        ],
      },
      {
        id: 'startup-budget',
        title: 'Your Startup Budget Worksheet',
        minutes: 12,
        body: [
          `Startup costs vary widely, because it depends on the equipment you already own, your state's requirements, and how professional you want your packaging to look. Build your own budget before you buy.`,
          `## Costs to list`,
          `* Registration, permit, license, or required training fees.`,
          `* Business license, name registration, and any sales tax setup.`,
          `* Insurance, first year.`,
          `* Equipment you must buy: scale, thermometers, pans, racks, storage containers, and a mixer if you need one.`,
          `* Cleaning and sanitizing supplies.`,
          `* First ingredient purchase for your test batches and first week of orders.`,
          `* Packaging, labels, and a label printer or printing service.`,
          `* Branding: logo, signs, business cards, and table cover.`,
          `* Market costs: canopy, tables, display pieces, weights, and card reader.`,
          `* A starter marketing budget, such as photo props or a small amount for local promotion.`,
          `* A cushion for mistakes and failed test batches.`,
          `## Sort items into three groups`,
          `* Must have before the first sale: anything the law or food safety requires, plus the basics you cannot bake without.`,
          `* Should have within the first 90 days: items that improve efficiency or presentation.`,
          `* Can wait: upgrades you buy only once sales pay for them.`,
          `## Ways to start lean`,
          `Use equipment you already own where it is food safe and reliable, buy used from restaurant supply or retiring bakers, order packaging samples before bulk, and rent market gear for your first event before you buy. Test demand with a small batch before investing in more inventory.`,
          `## Know your payback`,
          `Divide your total startup cost by your profit per item to learn how many items you must sell to get your money back. Seeing that number makes decisions easier.`,
          `## Keep receipts for every purchase`,
          `Startup costs may be deductible business expenses. Keep every receipt and ask your tax professional how to record them.`,
        ],
      },
    ],
  },
  {
    id: 'orders-online',
    title: 'Module 12: Orders, Website, and Customers',
    lessons: [
      {
        id: 'preorders',
        title: 'Pre Orders, Order Windows, and Pickup Systems',
        minutes: 14,
        body: [
          `Pre orders are one of the most useful systems a home baker can build. They tell you how much to bake, reduce waste, protect your time, and make cash flow predictable.`,
          `## How a pre order cycle works`,
          `* You announce a menu and an order window, such as Sunday through Wednesday.`,
          `* Customers choose items, a pickup time, and pay or place a deposit where your state allows online or advance payment.`,
          `* You close the window, total your orders, buy ingredients, and bake.`,
          `* Customers pick up at the time you scheduled.`,
          `## Why it works`,
          `You only bake what is already sold. Customers know exactly when the next window opens, which builds anticipation. A limited window creates urgency, and sold out items increase demand.`,
          `## What your order form should collect`,
          `* Name, phone, and email.`,
          `* Items and quantities.`,
          `* Pickup date and time slot.`,
          `* Allergy information the customer wants you to know.`,
          `* A line confirming they have read your policies.`,
          `## Check the rules first`,
          `Some states ban online sales or online payment for cottage food, some require in person handoff, and some require that the buyer be able to speak with you. Design your system around what your state allows. In some places you can take requests and confirm by phone or in person, then collect payment at pickup.`,
          `## Porch pickup and farmstand style sales`,
          `Many bakers use a porch cooler or a stand. Check zoning, HOA rules, and your state's rules about unattended sales. Protect products from heat, rain, pests, and theft, put each customer's name clearly on their order, and send a message when it is ready.`,
          `## Reduce no shows`,
          `Use clear pickup windows, send a reminder, and write a simple policy for orders that are not picked up. Many bakers require payment or a deposit in advance where allowed.`,
          `## Keep it simple`,
          `You can run a pre order system with a form, a spreadsheet, and a messaging app. Add tools only when volume makes the simple version hard.`,
        ],
      },
      {
        id: 'website-email',
        title: 'A Simple Website and Email List',
        minutes: 14,
        body: [
          `Social media rents you an audience. A website and an email list give you something you own. Both can be very simple.`,
          `## What a baker's website needs`,
          `* Your name, logo, and a clear one sentence description of what you bake and where you serve.`,
          `* Your menu and prices, or your current order window.`,
          `* How to order and how pickup works.`,
          `* Your policies, your allergen statement, and any statement your state requires you to show before an online sale. Some states require label information to appear on a website before a sale.`,
          `* Your story and a few clear photos.`,
          `* Contact information that does not expose more than you want to share. Many bakers use a form or a business email instead of a home address.`,
          `## Check your state's rules for websites`,
          `Some states allow a site to show products but require that the sale itself happen in person. Some require your registration number or a disclaimer on the page. Review the rules in your state before you add a buy button.`,
          `## Why an email list matters`,
          `An email list lets you reach customers directly when an order window opens. It does not depend on an algorithm. Even a list of a hundred local customers can fill an order window.`,
          `## How to build a list the right way`,
          `* Ask permission. Add people only when they sign up or clearly agree.`,
          `* Offer a reason to join, such as first access to a limited menu.`,
          `* Put a sign up link in your bio, on your market sign, and on your order confirmation.`,
          `## Follow email rules`,
          `United States law requires commercial emails to have honest subject lines, a real way to opt out, and a valid physical postal address. Use an email service that handles unsubscribe links for you.`,
          `## What to send`,
          `Send a short message when an order window opens, a reminder before it closes, a thank you after pickup, and an occasional story or seasonal preview. Once or twice a week is plenty.`,
        ],
        links: [
          { label: 'FTC: CAN-SPAM Act compliance guide', url: 'https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business' },
        ],
      },
      {
        id: 'photography',
        title: 'Photography That Sells Your Baking',
        minutes: 14,
        body: [
          `Your photos are your storefront. Strong photos let customers taste with their eyes, and you only need a phone and good habits.`,
          `## Light is everything`,
          `* Shoot near a window with soft daylight, away from direct harsh sun.`,
          `* Turn off overhead lights so colors do not look yellow or green.`,
          `* Place the product so the light comes from the side or slightly behind, which shows texture and shape.`,
          `* Use a white board or a piece of foam board opposite the window to bounce light into shadows.`,
          `## Keep backgrounds simple`,
          `Use a wood board, a neutral cloth, parchment, or a plain tabletop. Keep props small, such as a napkin, a cup, or a sprig of an ingredient, and make sure everything near food is clean and food safe.`,
          `## Know your core shots`,
          `* A hero shot: one product, close, with the best detail.`,
          `* A group shot: the full menu or a box set up.`,
          `* A packaged shot: your product in its package with the label visible.`,
          `* A cut or bite shot: the inside texture, such as the crumb of bread or the center of a cookie.`,
          `* A process shot: hands, dough, or decorating, with clean hands and covered hair.`,
          `## Phone tips`,
          `Clean the lens, tap to focus on the product, adjust exposure slightly down so highlights do not wash out, hold steady, and take many shots. Shoot from above for flat items and from a low angle for tall items like cakes and loaves.`,
          `## Edit lightly`,
          `Adjust brightness, contrast, and warmth a little so food looks true. Do not over filter. Customers should get what they see.`,
          `## Be honest`,
          `Photograph what you actually sell. Misleading photos cause disappointed customers and bad reviews.`,
          `## Build a consistent look`,
          `Use the same style, background, and editing so your page looks like a brand. Keep a folder of your best photos, organized by product and season.`,
        ],
      },
      {
        id: 'customer-service',
        title: 'Customer Service, Boundaries, and Difficult Moments',
        minutes: 12,
        body: [
          `Good service turns buyers into regulars, and firm boundaries keep a home bakery from taking over your life.`,
          `## Be fast, friendly, and clear`,
          `Reply to messages within a set window, such as within 24 hours, and say so on your profile. Confirm every order in writing with the items, the price, the pickup time, and any allergy notes.`,
          `## Common situations and calm responses`,
          `* Last minute order requests: thank them, explain your order cutoff, and offer the next available date.`,
          `* Requests for discounts: explain that your prices reflect your ingredients and time, and offer a smaller size or a different item if you can.`,
          `* Late or missed pickup: follow your policy kindly and consistently.`,
          `* Complaints: listen first, thank them, gather details, and offer a fair remedy. Never argue in public.`,
          `* Requests for products you cannot sell legally: explain simply that your state rules do not allow it, and offer a compliant alternative.`,
          `## Boundaries that protect your time`,
          `* Set message hours and an order window and share them clearly.`,
          `* Say no to requests that do not fit your capacity or your rules.`,
          `* Take real days off.`,
          `## Home safety and privacy`,
          `Consider using a pickup location other than your front door when possible, such as a porch box with a code, a nearby public spot, or a market. Do not publish your home address more than you must. Some states let you use a registration number on labels instead of your address.`,
          `## Collect reviews`,
          `Ask happy customers for a short review and permission to share it. Reviews are the strongest marketing a home bakery can have.`,
        ],
      },
    ],
  },
  {
    id: 'more-income',
    title: 'Module 13: More Ways to Earn',
    lessons: [
      {
        id: 'wholesale-retail',
        title: 'Wholesale Versus Retail, and When Each Makes Sense',
        minutes: 12,
        body: [
          `Selling directly to customers earns the most per item. Selling to stores, cafes, and restaurants earns less per item but can bring steady volume. Whether wholesale is even allowed depends on your state.`,
          `## Check the rules first`,
          `Many cottage food laws allow only direct sales to the end consumer. Some states allow sales to stores or restaurants, and some require extra steps, such as a review or a higher license. A few states ban it for baked goods. Use the state finder and ask your agency.`,
          `## Retail pricing versus wholesale pricing`,
          `Wholesale prices are often around half of retail, so your costs, labor, and packaging must still leave a profit at that price. If they do not, wholesale will cost you money even if it feels busy.`,
          `## When wholesale makes sense`,
          `* Your recipes are consistent, and you can batch efficiently.`,
          `* You have spare capacity.`,
          `* The buyer reorders regularly and pays on time.`,
          `* The volume does not push you toward your sales cap too quickly.`,
          `## Terms to write down`,
          `* Products, sizes, and prices.`,
          `* Order days, delivery days, and minimums.`,
          `* Payment terms and what happens with late payment.`,
          `* Labeling and any required allergen information.`,
          `* Who is responsible for storage and shelf life.`,
          `## Consignment`,
          `Some stores sell on consignment, paying you only after your product sells. This adds risk because you pay for products that may not sell. Many states restrict resale of cottage food, so confirm it is allowed.`,
          `## Watch your cap`,
          `Wholesale counts toward your yearly sales cap. Large orders can use a big share of it quickly.`,
        ],
      },
      {
        id: 'other-income',
        title: 'Other Income Streams That Fit a Home Bakery',
        minutes: 12,
        body: [
          `Once your bakery runs smoothly, you can add ideas that earn more without simply adding hours at the oven. Always check that each idea fits your state's rules before you launch.`,
          `## Ideas to consider`,
          `* Gift boxes and sampler sets with higher price points for holidays, corporate gifts, and thank you gifts.`,
          `* Standing weekly or monthly orders for regular customers, which gives you predictable income.`,
          `* Baking kits and dry mixes, where your state allows dry mixes as a cottage food. Check the labeling rules for mixes, which can differ from baked goods.`,
          `* Classes and workshops. Teaching a class is usually different from selling food, and rules about serving food at a class can differ. Check with your health department and your insurer before you host one at home.`,
          `* Digital products such as printed recipe cards or ebooks that you create yourself. These are not food products, but do not copy other people's recipes or photos.`,
          `* Events and collaborations, such as pop ups with a coffee shop, a florist, or another vendor where your state and venue allow it.`,
          `* Custom orders for weddings, showers, and corporate events at premium prices, when your allowed product list covers them.`,
          `## Choose carefully`,
          `Each new stream takes time to build. Add one at a time and judge it by profit per hour, not by how busy it feels.`,
          `## Protect your cap`,
          `Many of these ideas still count toward your sales cap if they involve food. Track total gross sales across everything you sell.`,
          `## Think long term`,
          `The strongest path for many bakers is to raise prices, serve fewer customers better, and reserve their time for the products and channels that earn the most.`,
        ],
      },
    ],
  },
  {
    id: 'tools-templates',
    title: 'Module 14: Templates, Scripts, and Troubleshooting',
    lessons: [
      {
        id: 'template-agency-email',
        title: 'Template: Email to Your State or County Agency',
        minutes: 6,
        body: [
          `Use this template when you want written answers about your products. Replace the items in brackets. Keep the reply for your Compliance folder.`,
          `## Subject line`,
          `Question about cottage food rules for a home bakery in [your county], [your state]`,
          `## Message`,
          `Hello, my name is [your name]. I am planning a small home based bakery in [your city and county]. I would like to confirm the rules that apply to me before I begin selling. I plan to make the following products in my home kitchen: [list each product, such as chocolate chip cookies, sourdough bread, vanilla cupcakes with buttercream frosting].`,
          `## Questions to include`,
          `* Do these products qualify under the state's cottage food law?`,
          `* Do I need any registration, permit, license, or training before I sell? What are the fees?`,
          `* What exact wording must appear on my label, and is there a required type size?`,
          `* Is there a yearly sales limit, and how is it measured?`,
          `* May I take orders online, deliver, ship, or sell to stores?`,
          `* Does my county or city add any requirements beyond the state law?`,
          `* Is there an inspection, and what does it involve?`,
          `## Closing`,
          `Please reply in writing if possible so I can keep the answer for my records. Thank you for your time. [Your name, phone number, and email]`,
          `## After you send it`,
          `Save the email, note the date, and if you do not hear back within a week, follow up politely or call and send a confirming email afterward.`,
        ],
      },
      {
        id: 'template-policies-forms',
        title: 'Template: Order Form Fields and Customer Policies',
        minutes: 8,
        body: [
          `Copy these into your order page or form and edit them to fit your rules. Keep the wording short and friendly.`,
          `## Order form fields`,
          `* Full name, phone number, email.`,
          `* Order window or event date.`,
          `* Items and quantities, with prices shown.`,
          `* Pickup day and time slot.`,
          `* Allergies or dietary notes the customer wants you to know.`,
          `* Check box: I have read the order policies.`,
          `## Sample policies`,
          `Orders. Orders open on [day] and close on [day] at [time] or when sold out. Orders placed after the cutoff go to the next window.`,
          `Payment. [Describe what your state allows, such as payment at pickup, or a deposit for custom orders.] The balance is due before pickup.`,
          `Pickup. Please pick up during your chosen time. I am not able to hold orders longer than [time]. Orders left unclaimed are not refundable.`,
          `Changes and cancellations. Please contact me at least [number] days before your pickup to change or cancel. Deposits are [refundable or non refundable] as stated on your quote.`,
          `Allergies. My products are made in a home kitchen where wheat, milk, eggs, soy, tree nuts, peanuts, and other allergens are handled. Cross contact is possible. Please read each label before you eat.`,
          `Quality. If anything is wrong with your order, please message me within [time] and include a photo. I will make it right.`,
          `## Custom order quote note`,
          `Your quote includes [items], [design details], and [packaging]. A deposit of [amount] confirms your date. Final allergen details must be confirmed in writing before baking begins.`,
        ],
      },
      {
        id: 'template-label-signs',
        title: 'Template: Label Layout, Price List, and Market Signs',
        minutes: 8,
        body: [
          `Use these layouts as a starting point. Always replace the required wording with your own state's exact text.`,
          `## Label layout`,
          `Product name, large, at the top.`,
          `Your business name and your address or state ID number, as your state requires.`,
          `Ingredients: list every ingredient in order from the most by weight to the least. Add sub ingredients in parentheses where needed.`,
          `Contains: list the major allergens present, for example wheat, milk, eggs, and soy.`,
          `Net weight: [weight].`,
          `Required home kitchen statement: [paste your state's exact wording].`,
          `Optional: baked on or best by date, storage instructions, and your handle or ordering link.`,
          `## Price list layout`,
          `Group items by category. Show the name, a short description, the size, and the price. Mark seasonal items and sold out items clearly. Add a short line with your ordering window and pickup details.`,
          `## Market sign wording`,
          `Business name and a one line description of what makes you special, such as small batch sourdough baked fresh this morning. Add a line that points to your order list, such as scan to join the next order window. Add your handle and, where your state requires it, your registration number or a statement about your home kitchen.`,
          `## Allergen sign for your table`,
          `Our products are made in a home kitchen that handles wheat, milk, eggs, soy, tree nuts, peanuts, and other allergens. Please read each label or ask me before you buy.`,
          `## Keep a master copy`,
          `Store every layout in a folder with the product name and date. When a rule or recipe changes, update the master copy first.`,
        ],
      },
      {
        id: 'template-captions-messages',
        title: 'Template: Captions, Messages, and Announcements',
        minutes: 8,
        body: [
          `Short, warm, clear messages save time and sell more. Edit these so they sound like you.`,
          `## Order window open`,
          `Orders are open for this week's bake. I am baking [items] for pickup on [day]. Spots are limited and orders close on [day] at [time] or when sold out. Order here: [link or instructions].`,
          `## Last call`,
          `Last call. I have [number] spots left for this week's bake. Orders close tonight at [time].`,
          `## New flavor`,
          `New this week: [flavor]. It has [short description]. I tested it [number] times to get it right and I cannot wait for you to try it. Available while it lasts.`,
          `## Behind the scenes`,
          `Baking day at my kitchen. [Short true detail about what you are making, why you love it, or what went wrong and how you fixed it.] Order window opens [day].`,
          `## Thank you after pickup`,
          `Thank you for your order. I hope you love it. If you enjoy it, a short review or a photo means the world to a small bakery like mine.`,
          `## Replying to a late request`,
          `Thank you so much for thinking of me. My order window for this week has closed, but I would love to bake for you next time. The next window opens [date].`,
          `## Replying to a request you cannot fill legally`,
          `Thank you for asking. My products are made under my state's home bakery rules, which do not allow me to make [item]. I can offer [allowed alternative], if you would like that instead.`,
          `## Replying to an allergy question`,
          `Thank you for asking. Here is the full ingredient list for [product]: [list]. Please know that my kitchen also handles [allergens], so cross contact is possible. I want you to feel safe, so please decide based on that information.`,
        ],
      },
      {
        id: 'troubleshooting',
        title: 'Troubleshooting Guide: Baking and Business Problems',
        minutes: 12,
        body: [
          `Every baker hits problems. Here are common ones and where to look first.`,
          `## Baking problems`,
          `* Cookies spread too much: dough too warm, too little flour, too much sugar or butter, or a hot or greasy pan. Chill the dough, weigh your flour, and use parchment.`,
          `* Cookies are hard or dry: overbaked, too much flour, or stored uncovered. Shorten bake time and store sealed.`,
          `* Bread is dense: weak starter or yeast, too little proofing, too much flour, or underdeveloped dough. Check your yeast, proof longer, and weigh ingredients.`,
          `* Bread is gummy inside: sliced before cooling, underbaked, or too much water. Cool fully and check the internal temperature.`,
          `* Cakes dome or crack: oven too hot or batter overmixed. Check your oven with a thermometer and mix only until combined.`,
          `* Cupcakes stick to liners: underbaked or cooled in the pan too long. Cool on a rack soon after baking.`,
          `* Frosting melts or sweats: warm room, too soft butter, or moisture in the box. Cool products fully and control transport temperature.`,
          `* Mold appears early: too much moisture, packaged while warm, or too long on the shelf. Cool fully, shorten shelf life, and test packaging.`,
          `## Business problems`,
          `* Not enough orders: simplify your menu, post consistently, ask for reviews, offer a limited seasonal item, and build your email list.`,
          `* Too many orders: close the window earlier, set a cap per window, and raise prices.`,
          `* Low profit: recalculate costs, raise prices, reduce waste, and drop low profit items.`,
          `* Burnout: reduce your order limit, set rest days, batch your work, and ask for help where your state allows.`,
          `* Customer complaint: follow the steps in the food safety module, and keep records.`,
          `* Close to your sales cap: use the Sales Cap Tracker and plan your next step early.`,
          `## Keep a problem log`,
          `Record what went wrong, what you changed, and what happened. In a few months it becomes your own troubleshooting book.`,
        ],
      },
      {
        id: 'glossary-faq',
        title: 'Glossary and Frequently Asked Questions',
        minutes: 10,
        body: [
          `Use this as a quick reference when a term comes up.`,
          `## Glossary`,
          `* Cottage food: shelf stable foods made in a home kitchen under a state cottage food law.`,
          `* TCS food: food that needs time and temperature control for safety, such as cream pies and cheesecake.`,
          `* Water activity: a measure of the free moisture in a food that bacteria can use. Lower values mean lower risk.`,
          `* pH: a measure of acidity. A pH of 4.6 or below is acidic enough that most harmful bacteria cannot grow.`,
          `* Cross contact: the accidental transfer of an allergen to a food that should not contain it.`,
          `* Danger zone: the temperature range between 41 and 135 degrees Fahrenheit where bacteria grow fastest.`,
          `* EIN: a free federal tax number for your business.`,
          `* DBA: a registered business name that is different from your legal name.`,
          `* Gross sales: total money from sales before costs. Most caps count this.`,
          `* Food freedom law: a state law that allows a broader range of homemade foods, usually sold directly to informed customers.`,
          `* Commissary or shared kitchen: a licensed commercial kitchen that bakers can rent.`,
          `## Frequently asked questions`,
          `Do I need a license? It depends on your state. Use the state finder, then confirm with your agency and local health department.`,
          `Can I sell online? It depends on your state and sometimes on how the food is delivered. Check the finder and ask in writing.`,
          `Can I ship? Many states do not allow it, and interstate shipping brings federal rules. Confirm before you ship anything.`,
          `Can I sell cake with cream cheese frosting? In many states, no. Ask your agency in writing.`,
          `Can my kids or a friend help? Some states limit who can work in a cottage kitchen. Check your rules and make sure everyone follows the same food safety practices.`,
          `Do I need insurance even if my state does not require it? It is strongly recommended. A single claim could be larger than your savings.`,
          `Do I have to pay taxes? Yes. Income from selling food is taxable, and you may owe sales tax. Talk to a local tax professional.`,
          `What if the law changes? Update your products, labels, and practices right away, and keep the new rule in your records.`,
        ],
      },
    ],
  },
];
