import type { Module } from './types';

// Cottage Bakery Masterclass, part C: modules 9 to 11.
// Selling, operations and growth, and the 90 day launch plan.

export const COTTAGE_MODULES_C: Module[] = [
  {
    id: 'selling',
    title: 'Module 9: Selling and Marketing',
    lessons: [
      {
        id: 'channels',
        title: 'Where and How You Can Sell',
        minutes: 14,
        body: [
          `Where you sell is as important as what you sell. Your state decides which channels are open to you, so start with the rules, then choose the channels that fit your products and your life.`,
          `## Common channels`,
          `* Direct from home: customers order and pick up from you. Check zoning and neighborhood rules first.`,
          `* Farmers markets and craft fairs: a strong way to meet customers and test products. Markets often have their own application, fees, and insurance rules.`,
          `* Pop ups and community events: seasonal markets, school fairs, church events, and local festivals.`,
          `* Online orders with local pickup or delivery: taking orders through your own page, a form, or a messaging app, with a set pickup time.`,
          `* Custom orders: birthdays, weddings, showers, and holidays. These are higher value and take more planning.`,
          `* Corporate and gift orders: offices, realtors, and small businesses buying gifts in bulk.`,
          `* Wholesale to stores, cafes, or restaurants: only where your state allows it, and often with extra requirements.`,
          `## Match the channel to the rules`,
          `Some states require in person delivery, ban online sales, ban shipping, or ban sales to stores. Use the state finder and your agency to check each channel before you use it.`,
          `## Start with two channels`,
          `Pick one high touch channel, like a weekly market, and one convenient channel, like a weekly online order window. Doing two well beats trying to do five poorly.`,
          `## Think about repeat customers`,
          `The best channel is the one that gets customers to come back. A weekly pickup, a standing order, or a loyalty card turns first time buyers into regulars.`,
        ],
        links: [
          { label: 'USDA farmers market directory', url: 'https://www.ams.usda.gov/local-food-directories/farmersmarkets' },
        ],
      },
      {
        id: 'booth-selling',
        title: 'Selling at Markets and Events',
        minutes: 14,
        body: [
          `A good market day takes preparation. Here is how successful vendors approach it.`,
          `## Before you apply`,
          `* Visit the market as a shopper first. Look at the crowd, the other vendors, and the prices.`,
          `* Ask about application deadlines, booth fees, insurance requirements, and whether baked goods are already well represented.`,
          `* Confirm that your cottage food registration, training, and labels meet the market's requirements, and ask what documents to bring.`,
          `## Prepare your products`,
          `Bring enough to avoid running out in the first hour, but not so much that you are left with a lot. Track what sells so your numbers improve every week. Pack products in clean, covered containers.`,
          `## Create a welcoming booth`,
          `* Clear signs that say what you sell and your prices.`,
          `* A neat display with height and color variety.`,
          `* Your best sellers at eye level.`,
          `* A friendly greeting, eye contact, and a short description of each product.`,
          `## Samples`,
          `Samples can increase sales, but many states and markets restrict them. If allowed, use individually wrapped samples or follow the rules for safe handling. If not allowed, show products and describe flavors.`,
          `## Build your list`,
          `Offer a sign up sheet or QR code for your order list or social page. A market sale is good. A repeat customer is better.`,
          `## Keep records after every event`,
          `Write down the date, weather, location, fees, units sold, revenue, and what you would change. After a few events, the numbers will tell you which markets deserve your time.`,
          `## Be professional`,
          `Arrive early, set up safely, follow market rules, and clean up completely. Market managers remember reliable vendors and often reserve the best spots for them.`,
        ],
      },
      {
        id: 'custom-orders',
        title: 'Custom Orders: Process, Deposits, and Boundaries',
        minutes: 12,
        body: [
          `Custom orders can be your most profitable work and your biggest source of stress. A clear process keeps them profitable and enjoyable.`,
          `## Create an intake process`,
          `Use a simple form that collects the date, the number of servings or units, flavors, dietary needs and allergens, design ideas, pickup or delivery details, and the contact information. Ask for photos of inspiration.`,
          `## Quote clearly`,
          `Give a price that includes ingredients, packaging, labor, design time, and any rush fee. Put it in writing and tell the customer what is included.`,
          `## Require a deposit`,
          `A non refundable deposit secures the date and protects you from last minute cancellations. Many bakers ask for a portion up front and the balance before pickup.`,
          `## Set a calendar limit`,
          `Decide how many custom orders you can handle each week and each holiday. Accept only what you can deliver at your standard of quality and safety. Saying no or offering another date is part of running a business.`,
          `## Confirm allergens and ingredients in writing`,
          `Before you bake, confirm every allergen and ingredient with the customer, and confirm your labeling. Never make last minute substitutions without telling them.`,
          `## Know what your state allows`,
          `Some states limit custom decorated items, refrigerated fillings, or the use of certain ingredients. Make sure every custom product fits your allowed list.`,
          `## Boundaries that protect you`,
          `* Set limits on how many design changes you will make.`,
          `* Decline requests that need ingredients or processes your state does not allow.`,
          `* Be polite and firm.`,
        ],
      },
      {
        id: 'online-presence',
        title: 'Building Your Online Presence and Photos',
        minutes: 14,
        body: [
          `Most customers will find you online before they ever taste your product. A clear, appealing online presence is part of your bakery.`,
          `## The basics`,
          `* One consistent name and handle across your platforms.`,
          `* A short bio that says what you bake, where you are, how to order, and your pickup details.`,
          `* A link to your ordering page or your profile in your bio.`,
          `## Make good photos`,
          `* Use natural light near a window.`,
          `* Keep the background simple and clean.`,
          `* Take close up shots that show texture, and wider shots that show the package.`,
          `* Show your packaging and your label, which builds trust.`,
          `* Show the process occasionally, with clean hands, hair covered, and a tidy kitchen.`,
          `## Content ideas that work`,
          `* Short videos of a bake, a decoration, or a package being closed.`,
          `* Weekly menus and order window reminders.`,
          `* Customer reviews and photos, with their permission.`,
          `* Behind the scenes stories about you and your recipes.`,
          `## Use it for orders, not just attention`,
          `Every post should make it easy to do something, such as order, join the list, or visit your market booth. Include the next step.`,
          `## Be careful about online sales rules`,
          `Some states ban online sales or ban online payments for cottage food, or allow online ads only. Advertising is usually fine, but selling and payment may not be. Check your state's rules before you take payment online.`,
          `## Reviews and local search`,
          `Ask happy customers to leave a review. Claim a free business listing in local search, with your service area, hours, and ordering details, if your zoning and state rules allow you to list a home based business.`,
        ],
      },
      {
        id: 'mitype',
        title: 'Using Mitype to Grow Your Bakery',
        minutes: 12,
        body: [
          `Mitype gives you a home base for your creative business and a community of local creators and customers. Here is how to use it well, within your state's cottage food rules.`,
          `## Build a complete profile`,
          `Add a clear photo, a short description of what you bake, your city, and your craft. People choose to connect with creators who look real and considered.`,
          `## Share your Mitype profile link`,
          `Your profile link works in an Instagram bio, a TikTok comment, a business card, or a market sign. Anyone who taps it lands on your profile.`,
          `## Show your work on the Wave Feed`,
          `Post short videos of your baking, your packaging, or your market table. Videos help people learn who you are and what makes your bakery different.`,
          `## Join the conversation on The Current`,
          `The Current is for text posts and replies. Share a new flavor, an order window, or a local market date, and talk with other creators.`,
          `## Small Business profile`,
          `If your bakery runs as a small business, you can set up a business page with a logo, services, hours, and contact options so local members can find you.`,
          `## Connect with other local creators`,
          `Photographers, designers, and other makers can become partners. A photographer can help with product photos, a designer can create your labels, and fellow vendors can share market tips and referrals.`,
          `## Follow the rules`,
          `Mitype is a place to meet and connect. Your state and local rules about how you sell food still apply, including what you can sell, how you take payment, and how you deliver. Use Mitype to build awareness and relationships, and take orders only in ways your state allows.`,
        ],
      },
      {
        id: 'seasonal',
        title: 'Seasons, Holidays, and Repeat Customers',
        minutes: 10,
        body: [
          `Baking has a natural calendar. Planning ahead for the busy seasons turns them into your best months instead of your most stressful.`,
          `## Map your year`,
          `* Winter holidays: usually the biggest season for cookies, gift boxes, and bread.`,
          `* Valentine's Day, Easter, Mother's Day, and graduation season: popular for gift and celebration orders.`,
          `* Summer: farmers market season for many regions, and wedding season.`,
          `* Fall: harvest flavors, pumpkin and apple items, and the beginning of the holiday rush.`,
          `## Plan early`,
          `Open holiday ordering earlier than you think and set a hard cutoff. Set order limits so you do not overbook yourself. Pre orders also help you buy ingredients and packaging in the right amounts.`,
          `## Create seasonal items`,
          `A limited seasonal item gives people a reason to buy now and a reason to follow you.`,
          `## Keep customers coming back`,
          `* Save contact details with permission, and send a short message when a favorite item returns.`,
          `* Offer a simple loyalty card or a repeat customer perk.`,
          `* Thank customers and follow up after custom orders.`,
          `* Share customer stories, with permission.`,
          `## Watch your cap in busy months`,
          `If your state caps yearly sales, a strong holiday season can use a large share of your cap. Check your total before you accept extra orders in November and December.`,
        ],
      },
    ],
  },
  {
    id: 'operations-growth',
    title: 'Module 10: Operations and Growth',
    lessons: [
      {
        id: 'weekly-rhythm',
        title: 'A Weekly Rhythm That Prevents Burnout',
        minutes: 12,
        body: [
          `A sustainable bakery depends on a predictable schedule. Without one, orders pile up and quality drops.`,
          `## Build a weekly cycle`,
          `* Order window: for example, Sunday to Wednesday.`,
          `* Shopping and prep: Wednesday.`,
          `* Baking and packaging: Thursday and Friday.`,
          `* Pickup, delivery, or market: Friday and Saturday.`,
          `* Admin and rest: Sunday and Monday.`,
          `## Batch your work`,
          `Group similar tasks. Mix all doughs, then bake all items, then package all items. It saves time and helps you control cleaning and allergen steps.`,
          `## Know your capacity`,
          `Track how long each product takes, including cleaning. Then set order limits that fit your real time and your kitchen. Overbooking is how quality and safety slip.`,
          `## Protect your time`,
          `Set clear hours for messages and orders. Customers respect clear boundaries when they are communicated kindly and consistently.`,
          `## Care for your body`,
          `Baking is physical. Use proper lifting, comfortable shoes, breaks, and water. A bakery owner who cannot work cannot sell.`,
          `## Protect your household`,
          `Talk with the people you live with about schedules, kitchen use, noise, deliveries, and customer pickups.`,
          `## Review monthly`,
          `Once a month, review your sales, hours, and stress level. Adjust the schedule before problems build.`,
        ],
      },
      {
        id: 'scaling',
        title: 'Growing Without Losing Quality or Compliance',
        minutes: 12,
        body: [
          `Growth is good when it is planned. Growth that outruns your systems creates safety and quality problems.`,
          `## Raise prices before you add hours`,
          `If demand is higher than your capacity, raise prices rather than working longer. Higher prices reduce volume while increasing profit per hour.`,
          `## Improve efficiency`,
          `* Standardize recipes and batch sizes.`,
          `* Buy better equipment when it saves meaningful time.`,
          `* Use ordering systems that gather order details in one place.`,
          `* Make packaging and labeling a simple routine.`,
          `## Helpers and employees`,
          `Many cottage food laws limit who can work in your kitchen, and many limit hiring beyond household members. Check your state rules before you bring in help. Anyone who handles food must follow the same food safety practices and should be trained.`,
          `## Add products slowly`,
          `Add one new product at a time, test it, and make sure it fits your allowed list and your capacity before adding another.`,
          `## Keep your standards`,
          `As volume grows, keep checking labels, temperatures, cleaning, and records. Review your food safety routine every quarter.`,
          `## Plan your next step`,
          `Decide in advance what comes next if the bakery keeps growing: a higher tier license, a shared commercial kitchen, a part time helper where allowed, or wholesale. Planning ahead keeps you in control.`,
        ],
      },
      {
        id: 'brand',
        title: 'Brand, Story, and Trademark Basics',
        minutes: 10,
        body: [
          `People buy from bakers they know and like. A clear brand turns a product into a business that is remembered and recommended.`,
          `## Define your brand`,
          `* Who you serve: families, offices, wedding clients, health conscious buyers, or neighbors.`,
          `* What makes you different: a flavor style, a family recipe, sourdough craft, or beautiful design.`,
          `* How you want customers to feel: cozy, elegant, playful, or nostalgic.`,
          `## Tell your story`,
          `Share why you bake, how you learned, and what you care about. Keep it honest and personal. Customers love real stories.`,
          `## Create a consistent look`,
          `Choose a small set of colors, fonts, and a simple logo. Use them on labels, packaging, signs, and social posts so customers recognize you quickly.`,
          `## Protect your name`,
          `Before you invest in packaging and signs, search for similar names in your area and in the federal trademark database. Using a name that another business already owns can force you to rebrand later. If your brand grows, speak with an attorney about trademark registration.`,
          `## Be consistent`,
          `A consistent product, a consistent look, and consistent service are the real brand. Everything else supports them.`,
        ],
        links: [
          { label: 'USPTO trademark information', url: 'https://www.uspto.gov/trademarks' },
          { label: 'SCORE free small business mentoring', url: 'https://www.score.org' },
        ],
      },
      {
        id: 'moving-up',
        title: 'Shared Kitchens, Licenses, and Moving Up',
        minutes: 12,
        body: [
          `If your bakery outgrows cottage food, you have good options. Learn them now so you are not surprised later.`,
          `## Shared commercial kitchens`,
          `Many communities have commissary or shared kitchens that rent space by the hour or by the month. They are inspected, licensed, and equipped, and renting one can legally remove many home based limits. Search for shared commercial kitchens near you, and ask your health department and your local small business office for recommendations.`,
          `## What to ask a shared kitchen`,
          `* What are the hourly or monthly rates, and what is included?`,
          `* Which equipment is provided, and what storage is available?`,
          `* Which licenses do they require, and what insurance?`,
          `* Can I sell to stores and ship products from there?`,
          `## Higher license tiers`,
          `Some states offer a home bakery, homestead, or home processor license that allows more than basic cottage food. Others offer separate licenses for wholesale. Ask your state agency about the next tier.`,
          `## A commercial space of your own`,
          `A storefront or your own commissary is a major step. Do the math first. Talk to your local small business development center or a mentor, build a financial plan, and test demand before you sign a lease.`,
          `## Get free help`,
          `Local small business development centers, SCORE mentors, and the Small Business Administration offer free or low cost guidance for new owners.`,
          `## Keep the habit of checking`,
          `Every new license or step comes with new rules. Apply the same habits you learned in this course: ask the agency, get answers in writing, and keep records.`,
        ],
        links: [
          { label: 'U.S. Small Business Administration', url: 'https://www.sba.gov' },
          { label: 'SCORE free mentoring', url: 'https://www.score.org' },
        ],
      },
    ],
  },
  {
    id: 'launch-plan',
    title: 'Module 15: Your 90 Day Launch Plan',
    lessons: [
      {
        id: 'plan-90',
        title: 'The 90 Day Launch Plan',
        minutes: 14,
        body: [
          `You now have the knowledge. This lesson turns it into a plan. Work through it in order and check items off as you go.`,
          `## Days 1 to 14: Rules and foundation`,
          `* Look up your state's rules with the finder and read your state agency page.`,
          `* Contact your county health department, zoning office, and business license office.`,
          `* Check your HOA and your lease.`,
          `* Write down every answer and save every email.`,
          `* Choose your business name and check availability.`,
          `## Days 15 to 30: Business setup and training`,
          `* Complete any required food safety training or registration, and take a food handler course even if it is optional.`,
          `* Get an EIN and open a business bank account.`,
          `* Register for sales tax if required.`,
          `* Get quotes for liability insurance and choose one.`,
          `* Set up a simple bookkeeping system.`,
          `## Days 31 to 45: Menu and recipes`,
          `* Choose your signature item and two to four core items.`,
          `* Standardize recipes by weight and test shelf life.`,
          `* Check each product against your state's allowed list.`,
          `* Cost each product and set prices.`,
          `## Days 46 to 60: Packaging and labels`,
          `* Order packaging samples and test them.`,
          `* Draft labels with the exact required wording, ingredients, and allergens.`,
          `* Have someone review your labels, and ask your agency whether they review labels.`,
          `* Order supplies in small amounts.`,
          `## Days 61 to 75: Soft launch`,
          `* Make small batches and sell to friends, family, and neighbors, within your rules.`,
          `* Take photos, collect feedback, and refine your recipes and packaging.`,
          `* Set your order window, pickup process, and policies.`,
          `## Days 76 to 90: Public launch`,
          `* Apply for a local market or set up your first online order window within your state's rules.`,
          `* Share your launch on your profiles and with your network.`,
          `* Track sales, hours, costs, and your progress against your cap.`,
          `* Review everything at day 90 and plan the next 90 days.`,
        ],
      },
      {
        id: 'checklists',
        title: 'Master Checklists You Can Reuse',
        minutes: 10,
        body: [
          `Use these checklists often. Copy them into your notes and print them for your kitchen.`,
          `## Before your first sale`,
          `* My products qualify under my state's list, confirmed in writing where possible.`,
          `* I have done any required training, registration, or permit.`,
          `* I have checked zoning, HOA, lease, county health, and business license rules.`,
          `* I have insurance, an EIN, a business bank account, and a way to track sales.`,
          `* My labels are correct and complete.`,
          `* My food safety routine and records are ready.`,
          `## Every baking day`,
          `* I am healthy, my hands are washed, and my hair is covered.`,
          `* The kitchen is clear of pets, kids, and household clutter.`,
          `* Surfaces and tools are cleaned and sanitized.`,
          `* I have checked ingredient labels for allergens.`,
          `* Allergen products are planned and cleaned between.`,
          `* Products are cooled, packaged, and labeled correctly.`,
          `* I have logged the batch.`,
          `## Every week`,
          `* I record sales, costs, hours, and units.`,
          `* I check my fridge and freezer temperatures.`,
          `* I review upcoming orders against my capacity.`,
          `* I check my year to date total against my cap.`,
          `## Every quarter and every January`,
          `* I recheck my state agency page and local requirements.`,
          `* I recalculate costs and adjust prices.`,
          `* I review insurance, registration renewals, and training dates.`,
          `* I review recipes, labels, and suppliers for changes.`,
        ],
      },
      {
        id: 'stay-current',
        title: 'Staying Legal and Staying Current',
        minutes: 10,
        body: [
          `Cottage food law is one of the fastest changing areas of small business regulation. The bakers who last are the ones who stay informed.`,
          `## Make checking a habit`,
          `* Bookmark your state agency's cottage food page and check it every quarter.`,
          `* Recheck every January, when many changes take effect.`,
          `* Note any scheduled change dates in your calendar.`,
          `## Reliable sources`,
          `* Your state's department of agriculture or department of health.`,
          `* Your county health department.`,
          `* The National Agricultural Law Center's cottage food compilation.`,
          `* The Institute for Justice's tracking of home food reforms.`,
          `* A university cooperative extension office in your state, which often publishes cottage food guides.`,
          `## Join a community`,
          `Local baker groups, market vendor groups, and small business networks are valuable for learning what is working in your area. Share what you learn, and verify it before you rely on it.`,
          `## When rules change`,
          `Update your recipes, labels, and processes right away. Notify affected customers when needed. Save the new rule and the date.`,
          `## A final word`,
          `The cottage bakery model works because it balances opportunity with safety. Follow the rules, protect your customers, bake with care, and treat your bakery as the real business it is. That is how a kitchen table business becomes a brand people trust.`,
          `This course is education, not legal advice. Laws vary by state and change often, so always confirm current rules with your state agency and your local health department before you sell.`,
        ],
        links: [
          { label: 'National Agricultural Law Center cottage food compilation', url: 'https://nationalaglawcenter.org/state-compilations/cottagefood/' },
          { label: 'Institute for Justice home food reforms', url: 'https://ij.org/legislative-advocacy/state-reforms-for-cottage-food-and-food-freedom-laws/' },
          { label: 'Forrager cottage food law map', url: 'https://forrager.com/laws/' },
        ],
      },
    ],
  },
];
