import type { Module } from './types';

// Cottage Bakery Masterclass, part B: modules 5 to 8.
// Menu and recipes, equipment and packaging, labels, and pricing.

export const COTTAGE_MODULES_B: Module[] = [
  {
    id: 'menu-recipes',
    title: 'Module 5: Your Menu and Recipes',
    lessons: [
      {
        id: 'choose-products',
        title: 'Choosing Products That Sell and Qualify',
        minutes: 12,
        body: [
          `Your menu is your business. The best menus are small, focused, profitable, and legal in your state. Choose with your head first and your heart second.`,
          `## Four filters for every product`,
          `* Does it qualify under my state's cottage food law?`,
          `* Can I make it consistently, in batches, with the same quality every time?`,
          `* Does it hold up for the time between baking and eating, including transport?`,
          `* Does it make money after ingredients, packaging, and my time?`,
          `## Build a menu in three tiers`,
          `* One signature item that people remember you for, such as a specific cookie, a sourdough loaf, or a cinnamon roll.`,
          `* Three to five core items that you make all the time and that are easy to produce in batches.`,
          `* A rotating seasonal item that creates urgency and gives people a reason to come back.`,
          `## Pick products with good margins`,
          `Some items look impressive but take hours of labor for small profit. Others, like cookies, loaves, and scones, can be profitable with efficient batching. Track your time on every new product before you decide to keep it.`,
          `## Think about the customer`,
          `Who will buy this and when? Gift buyers, office orders, holiday shoppers, and weekly regulars all behave differently. Offer a few sizes and price points so there is an easy entry choice and a premium option.`,
          `## Test the market before you scale`,
          `Share samples with friends, family, and neighbors where your state allows it, ask for honest feedback, and take a small test batch to a market. Let real demand tell you what to scale.`,
        ],
      },
      {
        id: 'recipe-testing',
        title: 'Standardizing and Testing Your Recipes',
        minutes: 14,
        body: [
          `A family recipe that works for a dozen cookies does not always work for a hundred. Professional bakers standardize recipes so every batch tastes the same.`,
          `## Weigh, do not scoop`,
          `Convert your recipes to weights. A kitchen scale makes batches more consistent than cups and spoons, because a cup of flour can vary widely. Record weights in grams for accuracy.`,
          `## Write recipes as procedures`,
          `For each product, write the ingredients by weight, the equipment, the mixing method and times, the oven temperature and bake time, the cooling method, the yield, and the packaging. Anyone who follows it should get the same result.`,
          `## Test in stages`,
          `* Test the recipe at your normal size several times until results are consistent.`,
          `* Scale up to production size and test again. Mixing times, bake times, and spread can change.`,
          `* Test with your real oven, your real pans, and your real packaging.`,
          `## Test shelf life honestly`,
          `Bake a batch and keep samples packaged the way you will sell them. Check them over several days for staleness, mold, texture, and flavor. Your testing tells you how long you can honestly say a product is at its best. Do not guess.`,
          `## Record changes`,
          `Keep a recipe log with the date, what you changed, and the result. When a customer loves something, you want to be able to make it the same way again.`,
          `## Check your recipe against your rules`,
          `Before you sell any recipe, confirm that its ingredients and its finished form fit your state's allowed foods. Pay particular attention to fillings, frostings, and toppings, and ask your agency in writing when unsure.`,
        ],
      },
      {
        id: 'shelf-life',
        title: 'Shelf Life, Freshness, and Storage Instructions',
        minutes: 10,
        body: [
          `Customers want to know how long your product will stay good. You want to make sure it is still good when they eat it. Clear storage guidance protects both of you.`,
          `## What affects shelf life`,
          `* Moisture: higher moisture products spoil faster and are more likely to grow mold.`,
          `* Packaging: air, humidity, and temperature all change how long a product stays fresh.`,
          `* Ingredients: fruit fillings, nuts, and dairy ingredients can change quality over time.`,
          `* Storage conditions: heat and humidity shorten shelf life.`,
          `## Match packaging to the product`,
          `Cookies often keep best in a sealed bag or box. Breads can go soft in plastic and dry out in paper, so test what works best. Cakes can be protected in boxes with clean lids. Moist products may need tighter protection.`,
          `## Date your products`,
          `Many bakers add a baked on date or a best by date to labels. Check whether your state requires or restricts dating, and use dates you have tested.`,
          `## Give storage instructions`,
          `Tell customers how to store the product, such as keep in a cool dry place, eat within a number of days, or freeze for longer storage if that is safe for the product. A short line on the label or the package card is enough.`,
          `## Leftovers and unsold products`,
          `Decide in advance what you do with unsold products. Do not sell old products past your tested date. Donating or discarding is better than risking quality.`,
        ],
      },
    ],
  },
  {
    id: 'equipment-packaging',
    title: 'Module 6: Equipment, Packaging, and Where to Buy',
    lessons: [
      {
        id: 'kitchen-equipment',
        title: 'Equipment: What You Need and What Can Wait',
        minutes: 12,
        body: [
          `You do not need a commercial kitchen's worth of equipment to start. You do need reliable basics. Buy in stages as sales justify it.`,
          `## Starter essentials`,
          `* A reliable oven and an oven thermometer to confirm real temperatures.`,
          `* A digital kitchen scale that weighs in grams.`,
          `* A stand mixer or a strong hand mixer, plus mixing bowls in a few sizes.`,
          `* Sheet pans, cooling racks, parchment, and silicone baking mats.`,
          `* Measuring tools, scrapers, spatulas, whisks, and a bench scraper.`,
          `* A digital probe thermometer.`,
          `* Food safe storage containers with lids, and labels for dating.`,
          `* Sanitizer, sanitizing test strips if your sanitizer calls for them, and clean towels.`,
          `## Next stage upgrades`,
          `* A second oven or extra racks to increase batch size.`,
          `* A larger mixer and extra bowls for bigger batches.`,
          `* A dough sheeter or proofing equipment if you make bread or laminated dough.`,
          `* A label printer and a heat sealer if you package a lot.`,
          `* Extra refrigerator or freezer space for ingredients.`,
          `## Buy smart`,
          `Restaurant supply stores and warehouse clubs often have better prices and sturdier products than home retail stores. Look for used equipment from retiring bakeries, but inspect it carefully, and make sure anything touching food is clean and safe.`,
          `## Keep home and business gear separate`,
          `Where possible, use equipment, containers, and tools reserved for your bakery. It keeps personal items out of production and makes cleaning easier.`,
        ],
        links: [
          { label: 'ThermoWorks food thermometers', url: 'https://www.thermoworks.com' },
        ],
      },
      {
        id: 'packaging-types',
        title: 'Packaging by Product Type',
        minutes: 12,
        body: [
          `Packaging protects your food, tells your story, and affects what customers will pay. It is also part of your food safety plan, so choose with care.`,
          `## What good packaging does`,
          `* Protects products from dust, pests, and handling.`,
          `* Keeps products fresh and prevents damage in transport.`,
          `* Carries your label with ingredients, allergens, and required statements.`,
          `* Looks good enough to gift and photograph.`,
          `## Matching packaging to products`,
          `* Cookies: clear cello bags with a seal, or small boxes with a window. Add a card or sticker for branding.`,
          `* Bread: paper bags with a window, or bread bags. Breathable options keep crusts crisp, while sealed bags keep soft breads moist.`,
          `* Cupcakes and cakes: sturdy boxes with inserts that hold each cupcake in place. Make sure the lid does not press into frosting.`,
          `* Brownies, bars, and scones: grease resistant bakery boxes or sealed bags.`,
          `* Gift sets: boxes or tins with dividers, ribbons, and a short note.`,
          `## Food grade and safe`,
          `Use packaging made for direct contact with food. Grease resistant paper and food safe liners are available for greasy items. Avoid packaging that sheds fibers or has strong odors.`,
          `## Tamper evident and secure`,
          `A sticker seal across the closure shows that the package has not been opened. It is a small cost that builds trust and is required in some situations.`,
          `## Sustainability and brand`,
          `Many customers like recyclable or compostable packaging, and it can support a premium price. Do not claim a package is compostable or recyclable unless the supplier confirms it.`,
          `## Test before you buy in bulk`,
          `Order samples first. Pack your real products, shake the box, and leave the packaged items for a few days to check freshness and stability.`,
        ],
      },
      {
        id: 'where-to-buy',
        title: 'Where to Buy Ingredients, Packaging, and Supplies',
        minutes: 14,
        body: [
          `Finding good suppliers early saves money and stress. Here are common sources bakers use, with reasons to use each. Always compare prices and shipping costs before you commit, because they vary by region and by order size.`,
          `## Packaging and bakery supplies`,
          `* Uline: a large supplier of boxes, bags, shipping supplies, and packaging materials, with quick shipping in many areas.`,
          `* WebstaurantStore: a large online restaurant supply with bakery boxes, bags, pans, tools, and food service equipment.`,
          `* Nashville Wraps: packaging focused on bakery and gift presentation, including bags, boxes, ribbons, and cello.`,
          `* Bakedeco: baking tools, decorating supplies, boxes, and packaging for bakeries.`,
          `* Papermart: bags, boxes, and wrapping supplies in many sizes.`,
          `## Bulk ingredients and equipment`,
          `* Restaurant Depot: a membership based wholesale supplier for food service buyers. Check its membership requirements.`,
          `* Costco Business Center and Sam's Club: bulk pricing on common baking staples, with membership.`,
          `* Local restaurant supply stores: often have used equipment, local advice, and no shipping costs.`,
          `* Farmers, local mills, and regional distributors: sometimes the best option for specialty flours, eggs, and seasonal produce.`,
          `## Labels and custom branding`,
          `* Avery: label templates and printable label stock for home printers.`,
          `* OnlineLabels: label sheets in many shapes and materials, with free templates.`,
          `* Etsy: custom stickers and branded packaging from small makers.`,
          `* Canva: design tools for logos, labels, menus, and signs.`,
          `## Marketplaces`,
          `* Amazon Business: convenient for tools, containers, and small equipment, with business pricing for registered buyers.`,
          `## How to evaluate a supplier`,
          `* Is the packaging food grade and clearly described?`,
          `* What is the minimum order, shipping cost, and lead time?`,
          `* Can you order samples first?`,
          `* Do they publish ingredient and allergen information for food products?`,
          `* What is their return or replacement policy?`,
          `## Keep your receipts`,
          `Your purchase records support your taxes and your traceability. Create a folder for them from the start.`,
        ],
        links: [
          { label: 'Uline', url: 'https://www.uline.com' },
          { label: 'WebstaurantStore', url: 'https://www.webstaurantstore.com' },
          { label: 'Nashville Wraps', url: 'https://www.nashvillewraps.com' },
          { label: 'Bakedeco', url: 'https://www.bakedeco.com' },
          { label: 'Papermart', url: 'https://www.papermart.com' },
          { label: 'Restaurant Depot', url: 'https://www.restaurantdepot.com' },
          { label: 'Costco Business Center', url: 'https://www.costcobusinessdelivery.com' },
          { label: 'Sam\'s Club', url: 'https://www.samsclub.com' },
          { label: 'Amazon Business', url: 'https://business.amazon.com' },
          { label: 'Avery label templates', url: 'https://www.avery.com/templates' },
          { label: 'OnlineLabels', url: 'https://www.onlinelabels.com' },
          { label: 'Canva', url: 'https://www.canva.com' },
          { label: 'Etsy', url: 'https://www.etsy.com' },
        ],
      },
      {
        id: 'booth-gear',
        title: 'Booth and Market Setup Gear',
        minutes: 12,
        body: [
          `A market booth is your storefront. A clean, welcoming, well organized booth builds trust and sells more. Here is what to plan.`,
          `## The structure`,
          `* A sturdy pop up canopy with weights on every leg, because wind can lift an unweighted canopy and cause injuries.`,
          `* One or two tables that are the right height for your customers.`,
          `* Table covers that reach the ground to hide storage and give a polished look.`,
          `## The display`,
          `* Risers, tiered stands, and baskets that add height so products can be seen from a distance.`,
          `* Cake stands and clean display containers with lids to keep products covered.`,
          `* A neat, readable sign with your name and logo, large enough to read from several feet away.`,
          `* Price signs for every item, in the same style.`,
          `## Safety and compliance on the table`,
          `* Labels on every package as your state requires.`,
          `* A handwashing station or sanitizer and wipes, and clean tongs or wax paper for handling.`,
          `* A copy of your registration, permit, or required statement as your state or market asks.`,
          `* Insurance certificate if the market requires it.`,
          `## Payments`,
          `A small card reader lets customers pay with cards and phones, and most customers prefer it. Bring a little cash for change, and keep money handling separate from food handling.`,
          `## Comfort and extras`,
          `* A cooler with ice packs for any ingredients or products that need temperature control, if your state allows them.`,
          `* Bags, boxes, and gift wrap.`,
          `* Business cards or a small card with your handle and ordering information.`,
          `* Water, a chair, sun protection, and a first aid kit.`,
          `## Practice your setup at home`,
          `Time yourself setting up and breaking down. Aim for a setup that one person can handle in under an hour. Take photos of your best layout so you can repeat it.`,
        ],
        links: [
          { label: 'Square: card readers and payments', url: 'https://squareup.com' },
          { label: 'USDA farmers market directory', url: 'https://www.ams.usda.gov/local-food-directories/farmersmarkets' },
        ],
      },
    ],
  },
  {
    id: 'labels',
    title: 'Module 7: Labels and Compliance',
    lessons: [
      {
        id: 'label-basics',
        title: 'What a Cottage Food Label Must Include',
        minutes: 14,
        body: [
          `Labels are the most common compliance problem for home bakers, and the easiest to prevent. Almost every state requires one, and the exact rules differ.`,
          `## Common required elements`,
          `* The name of the product.`,
          `* Your business name and either your address or a state issued ID number, depending on your state.`,
          `* A full ingredient list, in descending order by weight.`,
          `* Allergens identified in the way your state and federal rules require.`,
          `* The net weight or quantity of the package.`,
          `* A statement that the food was made in a home kitchen that is not inspected. Many states set this wording exactly.`,
          `## Use the state's exact wording`,
          `Close does not count. Texas, Florida, and Georgia, for example, each require different wording and some specify a minimum type size. Get your required statement from your state agency, not from a template you found online.`,
          `## Placement and readability`,
          `Place the label on the package where customers can see it. Use clear fonts, good contrast, and a size that meets any minimum your state sets. If you pack items in a box, label each individual package or follow your state's guidance for how to label the outer container.`,
          `## Optional but helpful`,
          `* A best by or baked on date.`,
          `* Storage instructions.`,
          `* Your website, handle, or a QR code that links to your ordering page.`,
          `## Review before you print`,
          `Have another person read your label. Check spelling, ingredients, allergens, and the required statement. Ask your agency or health department whether they review labels, since some states and counties do.`,
          `## Keep a master label file`,
          `Keep a digital file for every product with its recipe, its label, and the date you last verified it. When a rule changes, you can update all labels quickly.`,
        ],
        links: [
          { label: 'FDA: Food allergies', url: 'https://www.fda.gov/food/nutrition-food-labeling-and-critical-foods/food-allergies' },
        ],
      },
      {
        id: 'ingredients-allergens',
        title: 'Ingredient Lists and Allergen Statements',
        minutes: 14,
        body: [
          `The ingredient list and the allergen statement are the parts of your label that protect people the most. Do them carefully.`,
          `## How to write the ingredient list`,
          `List every ingredient in your product from the greatest weight to the least. Use common names that customers can understand. If an ingredient has its own ingredients, such as chocolate chips or a purchased mix, list the sub ingredients in parentheses after it, as the original package does.`,
          `## Identify the major allergens`,
          `The major allergens are milk, eggs, fish, shellfish, tree nuts, peanuts, wheat, soybeans, and sesame. A common way to do this is with a Contains statement after the ingredient list, such as Contains: wheat, milk, eggs, and soy. Follow your state's rules and federal labeling rules for exact format.`,
          `## Read every package`,
          `Ingredients you buy can contain allergens that you do not expect. A chocolate chip may include soy lecithin. A flavoring may include milk. Check every label whenever you buy and whenever the package changes.`,
          `## Keep a master ingredient sheet`,
          `For each recipe, list every ingredient with the brand you use and its allergens. When you update a brand, update the sheet and the label.`,
          `## Be careful with claims`,
          `Do not use terms like gluten free, vegan, or nut free unless you can truly support them, and check what your state and federal rules require for those claims. A home kitchen that also handles wheat and nuts cannot honestly promise it. Safer wording is made without a certain ingredient, with a note that cross contact is possible.`,
          `## Special diets and custom orders`,
          `For custom orders, confirm allergens in writing with the customer before you bake, and update the label for that order. Never improvise ingredients on the day.`,
        ],
      },
      {
        id: 'label-design',
        title: 'Designing and Printing Labels',
        minutes: 10,
        body: [
          `A good label is correct first and beautiful second. Once yours is correct, design it so that it also sells.`,
          `## Start with the template`,
          `Use a label template for the size of label you will print. Free templates are available from label suppliers and design tools. Match the template to your label stock.`,
          `## Layout tips`,
          `* Put your logo and product name at the top where customers see them first.`,
          `* Group the required legal information together at the bottom or on the side in a clean, readable block.`,
          `* Use at least the minimum type size your state requires, and make sure it is easy to read.`,
          `* Keep colors consistent with your brand.`,
          `## Choose the right label stock`,
          `* Paper labels are inexpensive, but can smudge if they get oily or wet.`,
          `* Waterproof or oil resistant labels hold up better on greasy or cold items.`,
          `* Make sure the adhesive is safe for the package and does not touch food directly unless it is food safe.`,
          `## Print and test`,
          `Print a few test labels, put them on real packages, and check readability and smudging. Try them in the fridge, in a hot car, and in a box together to see how they behave.`,
          `## Save and organize`,
          `Name your label files by product and date. Keep the source file so you can make changes quickly when a rule or a recipe changes.`,
        ],
        links: [
          { label: 'Avery label templates', url: 'https://www.avery.com/templates' },
          { label: 'OnlineLabels templates', url: 'https://www.onlinelabels.com' },
          { label: 'Canva', url: 'https://www.canva.com' },
        ],
      },
      {
        id: 'label-mistakes',
        title: 'Common Compliance Mistakes and a Final Checklist',
        minutes: 10,
        body: [
          `Most home food businesses that run into trouble make the same few mistakes. Learn them now and avoid them.`,
          `## Mistakes to avoid`,
          `* Using the wrong disclaimer wording or leaving it off.`,
          `* Forgetting an allergen, or relying on memory instead of reading the package.`,
          `* Selling a product that is not on your state's allowed list.`,
          `* Exceeding the yearly sales cap without a plan.`,
          `* Selling in a way your state does not allow, such as shipping across state lines, selling online where it is not allowed, or selling to stores for resale where it is banned.`,
          `* Ignoring local zoning or business license rules.`,
          `* Skipping required training or registration.`,
          `* Changing a recipe or an ingredient brand without updating the label.`,
          `## Your pre sale checklist`,
          `* I have confirmed my state's rules, in writing where possible.`,
          `* I have checked local zoning, my HOA or lease, and my county health department.`,
          `* I completed any required training or registration.`,
          `* Every product qualifies under my state's allowed list.`,
          `* Every label has the exact required wording, ingredients, allergens, and weight.`,
          `* I have insurance, a business bank account, and a way to track my sales against my cap.`,
          `* I have a food safety routine and records in place.`,
          `## Review often`,
          `Run through this checklist before your first sale, again every quarter, and again each January.`,
        ],
      },
    ],
  },
  {
    id: 'pricing',
    title: 'Module 8: Pricing and Profit',
    lessons: [
      {
        id: 'cost-per-unit',
        title: 'Know Your Real Cost Per Unit',
        minutes: 15,
        body: [
          `Many home bakers underprice because they only count ingredients. A real price covers every cost, including your time. Start by knowing what each item truly costs.`,
          `## The cost categories`,
          `* Ingredients: the cost of every ingredient used, including a share of things like salt, spices, and extracts.`,
          `* Packaging: bags, boxes, liners, labels, ribbons, and cards.`,
          `* Labor: your time, valued at a fair hourly rate.`,
          `* Overhead: utilities, equipment wear, insurance, registration fees, and software.`,
          `* Selling costs: market booth fees, card processing fees, delivery costs, and marketing.`,
          `* Waste: failed batches and unsold product.`,
          `## Calculate ingredient cost per unit`,
          `Add up the cost of every ingredient in a recipe, then divide by the number of finished units. For example, if a batch of 24 cookies uses $9.60 of ingredients, the ingredient cost is 40 cents per cookie.`,
          `## Add packaging and labor`,
          `If each cookie uses 35 cents of packaging and label, and the batch takes two hours including mixing, baking, cooling, and packing at a labor value of $20 an hour, labor for the batch is $40, which is about $1.67 per cookie.`,
          `## Add overhead and fees`,
          `Spread your overhead across your units. A simple way is to add a percentage, such as 10 to 15 percent, to account for it, then adjust once you have real numbers.`,
          `## The total`,
          `In this example, ingredients 40 cents, packaging 35 cents, labor $1.67, and overhead of about 25 cents give a cost near $2.67 per cookie. Your price must be well above that to earn a profit.`,
          `## Why this matters`,
          `If you sell that cookie for $2, you lose money on every sale and work for free. Knowing your real cost lets you price confidently.`,
        ],
      },
      {
        id: 'price-strategy',
        title: 'Setting Prices That Pay You',
        minutes: 14,
        body: [
          `Once you know your cost, you can set a price that makes sense for you and for your customers.`,
          `## Start with a target margin`,
          `Many food businesses aim for ingredient and packaging costs of roughly 25 to 35 percent of the selling price, then rely on the rest to cover labor, overhead, and profit. Use this as a rule of thumb and check it against your real numbers.`,
          `## Compare with your local market`,
          `Look at what local bakeries and market vendors charge for similar items. Home bakers who sell handmade, high quality products often price at or above local bakery prices, because customers pay for the quality and the story.`,
          `## Price with confidence`,
          `* Do not apologize for your prices. Your prices reflect real costs and real skill.`,
          `* Customers who value quality will pay it. Customers who only want the lowest price are not your customers.`,
          `* Raise prices gradually as demand grows and costs rise.`,
          `## Use price tiers`,
          `Offer a small single item at an easy price, a box of several at a better per unit price, and a premium gift box. Tiered options raise your average order.`,
          `## Custom orders and special designs`,
          `Charge more for custom work, rush orders, and elaborate designs. Include design time and any special supplies in your quote.`,
          `## Wholesale pricing, if your state allows it`,
          `If your state allows selling to stores or restaurants, wholesale prices are often around half of retail, so your costs and volume must support it. Many cottage food laws do not allow wholesale at all, so check first.`,
          `## Review prices every quarter`,
          `Ingredient costs change. Recalculate your costs every quarter and adjust prices when you need to.`,
        ],
      },
      {
        id: 'cap-and-growth-math',
        title: 'Your Sales Cap, Break Even, and Growth Math',
        minutes: 12,
        body: [
          `Your bakery's numbers should be simple enough to check in minutes. These three calculations will keep you on track.`,
          `## 1. Your monthly sales target`,
          `If your state has a cap, divide it by 12 for an average monthly pace. For a $50,000 cap, that is about $4,167 a month. If you have no cap, set your own target based on the income you want and the hours you can work.`,
          `## 2. Your break even`,
          `Add your fixed monthly costs, such as insurance, software, registration, and a share of equipment. Divide by the profit per unit to see how many units you need to cover them. Anything beyond that is profit.`,
          `## 3. Units needed to reach a goal`,
          `If you want $2,000 a month in profit and you earn $2 of profit per cookie after labor, you need to sell 1,000 cookies a month. That is about 250 a week. Knowing that number helps you decide if the goal is realistic with your time.`,
          `## Track weekly`,
          `Each week, record sales, costs, hours, and units sold. After a few weeks you will see which products and which channels pay best, and you can focus your time there.`,
          `## Keep an eye on your cap`,
          `If you are in a capped state, track your year to date total and compare it with your cap on the first of each month. Use the numbers to decide when to raise prices, add a higher tier, or move to a shared commercial kitchen.`,
          `## Save for slow months`,
          `Baking can be seasonal. Set aside part of your best months to cover slow ones, and to cover taxes, insurance, and equipment repairs.`,
        ],
      },
    ],
  },
];
